package renderer

import (
	"sort"

	"github.com/kunorikiku/yet-another-overlay-generator/internal/compiler"
	"github.com/kunorikiku/yet-another-overlay-generator/internal/model"
)

// babelLocalPort is the default port for the babeld control socket (local-port).
// The spec (docs/spec/compiler/routing-modes.md "Role-preset timers and control port")
// requires that it come from a documented named constant rather than a literal in the
// template, so it can be adjusted in one place (dossier D78).
const babelLocalPort = 33123

// BabelConfig holds the data for rendering a single node's Babel configuration.
type BabelConfig struct {
	// Node information.
	NodeName string
	NodeRole string

	// Babel router-id (MAC-48 format).
	RouterID string

	// babeld control socket port (from the babelLocalPort constant).
	LocalPort int

	// Interface timers (from the role preset; 0 = omit the corresponding token and
	// use babeld's built-in default).
	HelloInterval  int
	UpdateInterval int

	// List of WireGuard interfaces that Babel binds to.
	Interfaces []BabelInterface

	// LocalRedistributePrefixes are the prefixes redistributed via
	// `redistribute local ip <prefix> allow`. `redistribute local` only matches kernel
	// local/connected routes, so this holds only the categories that currently do have a
	// corresponding kernel route on the node (or are a known deferred item):
	//   - self-/32      : the overlay IP on dummy0 (the only path that actually takes effect
	//                     on deployed clusters, a protected invariant)
	//   - client-/32    : the client overlay IP injected on the router side via the PostUp
	//                     ip route replace
	//   - domain-CIDR   : the aggregate route has no corresponding kernel route on any node;
	//                     this is a plan-6.5 deferred item and, per the deferral decision, its
	//                     current no-op local line is kept unchanged (see the comment at the
	//                     write site below)
	LocalRedistributePrefixes []string

	// KernelRedistributePrefixes are the prefixes redistributed via
	// `redistribute ip <prefix> allow` (without the local keyword). These prefixes have a
	// real kernel route on the node, but it is not a dummy0 connected route, so they must use
	// the non-local form to make babeld match the real kernel route (dossier D40/D41):
	//   - default route 0.0.0.0/0 : the real WAN default route on a gateway
	//   - extra_prefixes          : connected routes for the node's real LAN segments
	KernelRedistributePrefixes []string

	// Whether IP forwarding is enabled.
	EnableForwarding bool
}

// BabelInterface describes the configuration for a single Babel interface.
type BabelInterface struct {
	// Interface name (e.g. wg-dmit).
	Name string

	// Type: tunnel (WireGuard point-to-point interfaces should use tunnel).
	Type string

	// rxcost (optional; 0 means omit the rxcost token and use babeld's built-in default).
	Cost int
}

const babelConfigTemplate = `# Babel configuration for {{ .NodeName }}
# Generated by Overlay Network Config Orchestrator
# Role: {{ .NodeRole }}

router-id {{ .RouterID }}
local-port {{ .LocalPort }}
skip-kernel-setup false

# Route redistribution
{{ range .LocalRedistributePrefixes -}}
redistribute local ip {{ . }} allow
{{ end -}}
{{ range .KernelRedistributePrefixes -}}
redistribute ip {{ . }} allow
{{ end -}}
# Deny all other local routes
redistribute local deny

# WireGuard tunnel interfaces
{{ range .Interfaces -}}
interface {{ .Name }} type {{ .Type }}{{ if gt $.HelloInterval 0 }} hello-interval {{ $.HelloInterval }}{{ end }}{{ if gt $.UpdateInterval 0 }} update-interval {{ $.UpdateInterval }}{{ end }}{{ if gt .Cost 0 }} rxcost {{ .Cost }}{{ end }}
{{ end }}`

// RenderBabelConfig renders the Babel configuration for a single node.
func RenderBabelConfig(node *model.Node, peers []compiler.PeerInfo, domain *model.Domain) (string, error) {
	// Decide whether Babel is needed.
	if !shouldRunBabel(node, domain) {
		return "", nil
	}

	// Role semantics.
	semantics := compiler.DeriveRoleSemantics(node)
	preset := GetBabelRolePreset(node.Role)

	// Generate the router-id.
	routerID := node.RouterID
	if routerID == "" {
		routerID = compiler.GenerateRouterID(node.ID)
	}

	config := BabelConfig{
		NodeName:         node.Name,
		NodeRole:         node.Role,
		RouterID:         routerID,
		LocalPort:        babelLocalPort,
		HelloInterval:    preset.HelloInterval,
		UpdateInterval:   preset.UpdateInterval,
		EnableForwarding: semantics.EnableForwarding,
	}

	// Render interface and client-/32 lines in a STABLE order: a node's peer slice is
	// built in topology edge-array order (peers.go Pass 2), so a benign edge reorder
	// would otherwise churn this node's babeld.conf bytes / bundle digest (C1 — it broke
	// the incremental-deploy byte-stability the pin/reserve/heal apparatus protects).
	// Sort by the unique per-peer InterfaceName so the output depends only on link
	// identity, not edge-array position.
	sortedPeers := append([]compiler.PeerInfo(nil), peers...)
	sort.Slice(sortedPeers, func(i, j int) bool {
		return sortedPeers[i].InterfaceName < sortedPeers[j].InterfaceName
	})

	// Each peer corresponds to one WireGuard tunnel interface.
	// D73: tunnels that connect to a client (IsClientPeer) must be skipped — the client
	// does not run babeld, and declaring that tunnel as a babel interface would make the
	// router unicast hello/update to it forever. Client reachability is instead carried by
	// the client-/32 redistribution below.
	for _, p := range sortedPeers {
		if p.IsClientPeer {
			continue
		}
		// D63: rxcost prefers the edge's LinkCost (> 0 means the operator explicitly set a
		// priority/weight); when unset (0) it falls back to the role preset's DefaultCost.
		cost := preset.DefaultCost
		if p.LinkCost > 0 {
			cost = p.LinkCost
		}
		iface := BabelInterface{
			Name: p.InterfaceName,
			Type: "tunnel",
			Cost: cost,
		}
		config.Interfaces = append(config.Interfaces, iface)
	}

	// ===== Redistribution rules =====
	//
	// self-/32: uses `redistribute local` — dummy0 carries the OverlayIP/32 connected route,
	// which is currently the only announcement path that actually takes effect on deployed
	// clusters and must be kept byte-for-byte unchanged (a protected invariant).
	if semantics.BabelAnnounce.AnnounceSelf && node.OverlayIP != "" {
		config.LocalRedistributePrefixes = append(config.LocalRedistributePrefixes, node.OverlayIP+"/32")
	}

	// domain-CIDR aggregate: no node has a corresponding kernel route (no node owns the
	// aggregate). Fixing its matching would require anchoring an aggregate local route in
	// the install script, which is a plan-6.5 deferred item (see the stop-loss note in
	// docs/spec/compiler/routing-modes.md). Until then, keep its current no-op
	// `redistribute local` line unchanged and do not switch it to the non-local form.
	if semantics.BabelAnnounce.AnnounceDomainCIDR && domain != nil && domain.CIDR != "" {
		config.LocalRedistributePrefixes = append(config.LocalRedistributePrefixes, domain.CIDR)
	}

	// extra_prefixes: kernel connected routes for the node's real LAN segments, so they use
	// the non-local form `redistribute ip <prefix> allow` to make babeld match the real
	// kernel route (D41).
	if semantics.BabelAnnounce.AnnounceExtraPrefixes {
		config.KernelRedistributePrefixes = append(config.KernelRedistributePrefixes, node.ExtraPrefixes...)
	}

	// default route 0.0.0.0/0: the real WAN default route on a gateway; uses the non-local
	// form so babeld matches that real kernel route and announces the exit into the overlay
	// (D40).
	if semantics.BabelAnnounce.AnnounceDefault {
		config.KernelRedistributePrefixes = append(config.KernelRedistributePrefixes, "0.0.0.0/0")
	}

	// client-/32: the router side injects the kernel route for the client overlay IP via the
	// tunnel's PostUp ip route replace, so it uses `redistribute local` — this is how client
	// reachability is carried (the client itself does not run babeld).
	for _, p := range sortedPeers {
		if p.IsClientPeer && p.ClientOverlayIP != "" {
			config.LocalRedistributePrefixes = append(config.LocalRedistributePrefixes, p.ClientOverlayIP+"/32")
		}
	}

	return renderTemplate("babeld.conf", babelConfigTemplate, config)
}

// RenderAllBabelConfigs renders the Babel configuration for every node.
func RenderAllBabelConfigs(topo *model.Topology, peerMap map[string][]compiler.PeerInfo) (map[string]string, error) {
	configs := make(map[string]string)

	// Domain index.
	domainMap := make(map[string]*model.Domain)
	for i := range topo.Domains {
		domainMap[topo.Domains[i].ID] = &topo.Domains[i]
	}

	// Node index.
	nodeMap := make(map[string]*model.Node)
	for i := range topo.Nodes {
		nodeMap[topo.Nodes[i].ID] = &topo.Nodes[i]
	}

	for nodeID, peers := range peerMap {
		node := nodeMap[nodeID]
		if node == nil {
			continue
		}

		domain := domainMap[node.DomainID]

		config, err := RenderBabelConfig(node, peers, domain)
		if err != nil {
			return nil, err
		}

		// Only include nodes that have a Babel configuration.
		if config != "" {
			configs[nodeID] = config
		}
	}

	return configs, nil
}

// shouldRunBabel reports whether the node needs to run Babel.
func shouldRunBabel(node *model.Node, domain *model.Domain) bool {
	// Client nodes do not run Babel.
	if node.Role == "client" {
		return false
	}
	// Do not start Babel in a non-babel routing mode.
	if domain != nil && domain.RoutingMode != "babel" {
		return false
	}
	return true
}
