package renderer

import (
	"github.com/kunorikiku/yet-another-overlay-generator/internal/compiler"
	"github.com/kunorikiku/yet-another-overlay-generator/internal/model"
)

// BabelConfig Babel 配置
type BabelConfig struct {
	// 节点信息
	NodeName string
	NodeRole string

	// Babel router-id（MAC-48 格式）
	RouterID string

	// Babel 绑定的 WireGuard 接口列表
	Interfaces []BabelInterface

	// 重分发前缀
	RedistributePrefixes []string

	// 是否启用 IP 转发
	EnableForwarding bool
}

// BabelInterface Babel 接口配置
type BabelInterface struct {
	// 接口名（如 wg-dmit）
	Name string

	// 类型：tunnel（WireGuard 点对点接口应该用 tunnel）
	Type string

	// rxcost（可选，0 表示使用默认值）
	Cost int
}

const babelConfigTemplate = `# Babel configuration for {{ .NodeName }}
# Generated by Overlay Network Config Orchestrator
# Role: {{ .NodeRole }}

router-id {{ .RouterID }}
local-port 33123
skip-kernel-setup false

# Route redistribution
{{ range .RedistributePrefixes -}}
redistribute local ip {{ . }} allow
{{ end -}}
# Deny all other local routes
redistribute local deny

# WireGuard tunnel interfaces
{{ range .Interfaces -}}
interface {{ .Name }} type {{ .Type }} hello-interval 4 update-interval 16{{ if gt .Cost 0 }} rxcost {{ .Cost }}{{ end }}
{{ end }}`

// RenderBabelConfig 渲染单个节点的 Babel 配置
func RenderBabelConfig(node *model.Node, peers []compiler.PeerInfo, domain *model.Domain) (string, error) {
	// 判断是否需要 Babel
	if !shouldRunBabel(node, domain) {
		return "", nil
	}

	// 角色语义
	semantics := compiler.DeriveRoleSemantics(node)
	preset := GetBabelRolePreset(node.Role)

	// 生成 router-id
	routerID := node.RouterID
	if routerID == "" {
		routerID = compiler.GenerateRouterID(node.ID)
	}

	config := BabelConfig{
		NodeName:         node.Name,
		NodeRole:         node.Role,
		RouterID:         routerID,
		EnableForwarding: semantics.EnableForwarding,
	}

	// 每个 peer 对应一个 WireGuard tunnel 接口
	for _, p := range peers {
		cost := preset.DefaultCost
		iface := BabelInterface{
			Name: p.InterfaceName,
			Type: "tunnel",
			Cost: cost,
		}
		config.Interfaces = append(config.Interfaces, iface)
	}

	// 重分发规则
	if semantics.BabelAnnounce.AnnounceSelf && node.OverlayIP != "" {
		config.RedistributePrefixes = append(config.RedistributePrefixes, node.OverlayIP+"/32")
	}

	if semantics.BabelAnnounce.AnnounceDomainCIDR && domain != nil && domain.CIDR != "" {
		config.RedistributePrefixes = append(config.RedistributePrefixes, domain.CIDR)
	}

	if semantics.BabelAnnounce.AnnounceExtraPrefixes {
		config.RedistributePrefixes = append(config.RedistributePrefixes, node.ExtraPrefixes...)
	}

	if semantics.BabelAnnounce.AnnounceDefault {
		config.RedistributePrefixes = append(config.RedistributePrefixes, "0.0.0.0/0")
	}

	return renderTemplate("babeld.conf", babelConfigTemplate, config)
}

// RenderAllBabelConfigs 渲染所有节点的 Babel 配置
func RenderAllBabelConfigs(topo *model.Topology, peerMap map[string][]compiler.PeerInfo) (map[string]string, error) {
	configs := make(map[string]string)

	// Domain 索引
	domainMap := make(map[string]*model.Domain)
	for i := range topo.Domains {
		domainMap[topo.Domains[i].ID] = &topo.Domains[i]
	}

	// 节点索引
	nodeMap := make(map[string]*model.Node)
	for i := range topo.Nodes {
		nodeMap[topo.Nodes[i].ID] = &topo.Nodes[i]
	}

	for nodeID, peers := range peerMap {
		node := nodeMap[nodeID]
		if node == nil {
			continue
		}

		domain := domainMap[node.DomainID]

		config, err := RenderBabelConfig(node, peers, domain)
		if err != nil {
			return nil, err
		}

		// 有 Babel 配置时才加入
		if config != "" {
			configs[nodeID] = config
		}
	}

	return configs, nil
}

// shouldRunBabel 判断节点是否需要运行 Babel
func shouldRunBabel(node *model.Node, domain *model.Domain) bool {
	// 非 babel 路由模式不启动
	if domain != nil && domain.RoutingMode != "babel" {
		return false
	}
	return true
}
