package renderer

import (
	"fmt"
	"strings"

	"github.com/kunorikiku/yet-another-overlay-generator/internal/model"
)

// DeployNodeInfo holds per-node SSH and artifact info for deploy script generation
type DeployNodeInfo struct {
	NodeName   string
	SSHTarget  string // ssh_alias or user@host
	SSHPort    int
	SSHKeyPath string
	HasSSH     bool
}

// DeployScriptConfig holds all nodes for one combined deploy script
type DeployScriptConfig struct {
	ProjectName string
	Nodes       []DeployNodeInfo
}

// RenderDeployScripts generates a bash deploy script and a PowerShell deploy script.
// Both scripts iterate all nodes that have SSH details configured, SCP the
// self-extracting installer to the remote, and execute it via sudo.
// Returns (bashScript, ps1Script, error).
func RenderDeployScripts(topo *model.Topology) (string, string, error) {
	config := DeployScriptConfig{
		ProjectName: topo.Project.Name,
	}

	for _, node := range topo.Nodes {
		info := DeployNodeInfo{
			NodeName: node.Name,
			SSHPort:  22,
		}

		if node.SSHAlias != "" {
			info.SSHTarget = node.SSHAlias
			info.HasSSH = true
		} else if node.SSHHost != "" {
			user := node.SSHUser
			if user == "" {
				user = "root"
			}
			info.SSHTarget = fmt.Sprintf("%s@%s", user, node.SSHHost)
			info.HasSSH = true
		}

		if node.SSHPort > 0 {
			info.SSHPort = node.SSHPort
		}
		info.SSHKeyPath = node.SSHKeyPath

		config.Nodes = append(config.Nodes, info)
	}

	bash, err := renderBashDeploy(config)
	if err != nil {
		return "", "", err
	}

	ps1, err := renderPS1Deploy(config)
	if err != nil {
		return "", "", err
	}

	return bash, ps1, nil
}

func renderBashDeploy(config DeployScriptConfig) (string, error) {
	var b strings.Builder

	b.WriteString(`#!/usr/bin/env bash
# Auto-deploy script for project: ` + config.ProjectName + `
# Generated by Overlay Network Config Orchestrator
#
# Usage: bash deploy-all.sh [--clean] <path-to-artifacts.zip>
#
# Options:
#   --clean    Remove ALL existing WireGuard interfaces (wg*) before deploying.
#              Use this when switching from a single-interface (wg0) layout to
#              per-peer interfaces, or vice versa.
#
# This script SSHs into each configured node, uploads the self-extracting
# installer, and executes it with sudo. Nodes without SSH details are skipped.
# SSH failures are caught per-node and do not abort the entire run.

set -uo pipefail

CLEAN=0
ARTIFACTS_ZIP=""

for arg in "$@"; do
    case "$arg" in
        --clean) CLEAN=1 ;;
        *) ARTIFACTS_ZIP="$arg" ;;
    esac
done

if [ -z "$ARTIFACTS_ZIP" ]; then
    echo "Usage: $0 [--clean] <path-to-artifacts.zip>"
    echo ""
    echo "Options:"
    echo "  --clean    Remove all existing WireGuard interfaces before deploying"
    echo ""
    echo "Download the artifacts ZIP from the web UI (Export Artifacts button),"
    echo "then run this script pointing at the downloaded file."
    exit 1
fi

if [ ! -f "$ARTIFACTS_ZIP" ]; then
    echo "ERROR: File not found: $ARTIFACTS_ZIP" >&2
    exit 1
fi

# Extract to a temp directory
WORKDIR="$(mktemp -d -t overlay-deploy-XXXXXX)"
cleanup() { rm -rf "$WORKDIR"; }
trap cleanup EXIT

echo "Extracting artifacts..."
unzip -q "$ARTIFACTS_ZIP" -d "$WORKDIR"

FAILED=0
SKIPPED=0
SUCCESS=0

`)

	// Build the remote clean command used when --clean is passed
	cleanCmd := `for iface in $(ip -o link show type wireguard 2>/dev/null | awk -F: '{print \\$2}' | tr -d ' '); do wg-quick down \\\"\\$iface\\\" 2>/dev/null || ip link del \\\"\\$iface\\\" 2>/dev/null || true; done; rm -f /etc/wireguard/wg*.conf`

	for _, node := range config.Nodes {
		b.WriteString(fmt.Sprintf("# --- Node: %s ---\n", node.NodeName))

		installerFile := node.NodeName + ".install.sh"

		if !node.HasSSH {
			b.WriteString(fmt.Sprintf(`echo ""
echo "=== %s: SKIPPED (no SSH details configured) ==="
SKIPPED=$((SKIPPED + 1))
`, node.NodeName))
			b.WriteString("\n")
			continue
		}

		sshOpts := fmt.Sprintf("-o StrictHostKeyChecking=accept-new -o ConnectTimeout=15 -p %d", node.SSHPort)
		scpPort := fmt.Sprintf("-P %d", node.SSHPort)
		if node.SSHKeyPath != "" {
			sshOpts += fmt.Sprintf(" -i %q", node.SSHKeyPath)
			scpPort += fmt.Sprintf(" -i %q", node.SSHKeyPath)
		}

		b.WriteString(fmt.Sprintf(`echo ""
echo "=== Deploying to %s (%s) ==="
INSTALLER="$WORKDIR/%s"
if [ ! -f "$INSTALLER" ]; then
    echo "  WARNING: Installer %s not found in archive, skipping."
    SKIPPED=$((SKIPPED + 1))
else
    # Test SSH connectivity first
    if ! ssh %s %s "echo ok" >/dev/null 2>&1; then
        echo "  ERROR: SSH connection to %s failed (timeout or auth error)." >&2
        FAILED=$((FAILED + 1))
    else
        # Clean previous WireGuard configs if requested
        if [ "$CLEAN" -eq 1 ]; then
            echo "  Cleaning existing WireGuard interfaces on %s..."
            ssh %s %s "sudo bash -c '%s'" 2>/dev/null || true
        fi

        if scp %s "$INSTALLER" %s:/tmp/%s; then
            if ssh %s %s "sudo bash /tmp/%s && rm -f /tmp/%s"; then
                echo "  SUCCESS: %s deployed."
                SUCCESS=$((SUCCESS + 1))
            else
                echo "  ERROR: Installation script failed on %s (exit code: $?)." >&2
                FAILED=$((FAILED + 1))
            fi
        else
            echo "  ERROR: SCP upload to %s failed." >&2
            FAILED=$((FAILED + 1))
        fi
    fi
fi
`,
			node.NodeName, node.SSHTarget,
			installerFile,
			installerFile,
			// SSH connectivity test
			sshOpts, node.SSHTarget,
			node.NodeName,
			// Clean step
			node.NodeName,
			sshOpts, node.SSHTarget, cleanCmd,
			// SCP + install
			scpPort, node.SSHTarget, installerFile,
			sshOpts, node.SSHTarget, installerFile, installerFile,
			node.NodeName,
			node.NodeName,
			node.NodeName,
		))
		b.WriteString("\n")
	}

	b.WriteString(`echo ""
echo "============================================================"
echo "  Deploy Summary"
echo "  Success: $SUCCESS  Skipped: $SKIPPED  Failed: $FAILED"
echo "============================================================"

if [ "$FAILED" -gt 0 ]; then
    exit 1
fi
`)

	return b.String(), nil
}

func renderPS1Deploy(config DeployScriptConfig) (string, error) {
	var b strings.Builder

	b.WriteString(`# Auto-deploy script for project: ` + config.ProjectName + `
# Generated by Overlay Network Config Orchestrator
#
# Usage: .\deploy-all.ps1 -ArtifactsZip <path-to-artifacts.zip> [-Clean]
#
# Options:
#   -Clean     Remove ALL existing WireGuard interfaces (wg*) before deploying.
#              Use this when switching from a single-interface (wg0) layout to
#              per-peer interfaces, or vice versa.
#
# This script SSHs into each configured node, uploads the self-extracting
# installer, and executes it with sudo. Nodes without SSH details are skipped.
# Requires OpenSSH client (ssh/scp) in PATH.

param(
    [Parameter(Mandatory=$true)]
    [string]$ArtifactsZip,

    [switch]$Clean
)

$ErrorActionPreference = "Continue"

if (-not (Test-Path $ArtifactsZip)) {
    Write-Error "File not found: $ArtifactsZip"
    exit 1
}

# Extract to temp
$WorkDir = Join-Path ([System.IO.Path]::GetTempPath()) ("overlay-deploy-" + [System.Guid]::NewGuid().ToString("N").Substring(0,8))
New-Item -ItemType Directory -Path $WorkDir -Force | Out-Null

try {
    Write-Host "Extracting artifacts..."
    Expand-Archive -Path $ArtifactsZip -DestinationPath $WorkDir -Force

    $Failed = 0
    $Skipped = 0
    $Success = 0

`)

	cleanCmd := `for iface in \\$(ip -o link show type wireguard 2>/dev/null | awk -F: '{print \\$2}' | tr -d ' '); do wg-quick down \\$iface 2>/dev/null || ip link del \\$iface 2>/dev/null || true; done; rm -f /etc/wireguard/wg*.conf`

	for _, node := range config.Nodes {
		installerFile := node.NodeName + ".install.sh"

		if !node.HasSSH {
			b.WriteString(fmt.Sprintf(`    Write-Host ""
    Write-Host "=== %s: SKIPPED (no SSH details configured) ==="
    $Skipped++
`, node.NodeName))
			b.WriteString("\n")
			continue
		}

		sshOpts := fmt.Sprintf("-o StrictHostKeyChecking=accept-new -o ConnectTimeout=15 -p %d", node.SSHPort)
		scpPort := fmt.Sprintf("-P %d", node.SSHPort)
		if node.SSHKeyPath != "" {
			sshOpts += fmt.Sprintf(` -i "%s"`, node.SSHKeyPath)
			scpPort += fmt.Sprintf(` -i "%s"`, node.SSHKeyPath)
		}

		b.WriteString(fmt.Sprintf(`    Write-Host ""
    Write-Host "=== Deploying to %s (%s) ==="
    $Installer = Join-Path $WorkDir "%s"
    if (-not (Test-Path $Installer)) {
        Write-Warning "Installer %s not found in archive, skipping."
        $Skipped++
    } else {
        # Test SSH connectivity first
        $sshTest = & ssh %s %s "echo ok" 2>&1
        if ($LASTEXITCODE -ne 0) {
            Write-Host "  ERROR: SSH connection to %s failed (timeout or auth error)." -ForegroundColor Red
            $Failed++
        } else {
            # Clean previous WireGuard configs if requested
            if ($Clean) {
                Write-Host "  Cleaning existing WireGuard interfaces on %s..."
                & ssh %s %s "sudo bash -c '%s'" 2>$null
            }

            & scp %s $Installer "%s:/tmp/%s"
            if ($LASTEXITCODE -ne 0) {
                Write-Host "  ERROR: SCP upload to %s failed." -ForegroundColor Red
                $Failed++
            } else {
                & ssh %s %s "sudo bash /tmp/%s && rm -f /tmp/%s"
                if ($LASTEXITCODE -ne 0) {
                    Write-Host "  ERROR: Installation script failed on %s (exit code: $LASTEXITCODE)." -ForegroundColor Red
                    $Failed++
                } else {
                    Write-Host "  SUCCESS: %s deployed."
                    $Success++
                }
            }
        }
    }
`,
			node.NodeName, node.SSHTarget,
			installerFile,
			installerFile,
			// SSH test
			sshOpts, node.SSHTarget,
			node.NodeName,
			// Clean step
			node.NodeName,
			sshOpts, node.SSHTarget, cleanCmd,
			// SCP + install
			scpPort, node.SSHTarget, installerFile,
			node.NodeName,
			sshOpts, node.SSHTarget, installerFile, installerFile,
			node.NodeName,
			node.NodeName,
		))
		b.WriteString("\n")
	}

	b.WriteString(`    Write-Host ""
    Write-Host "============================================================"
    Write-Host "  Deploy Summary"
    Write-Host "  Success: $Success  Skipped: $Skipped  Failed: $Failed"
    Write-Host "============================================================"

    if ($Failed -gt 0) {
        exit 1
    }
} finally {
    Remove-Item -Recurse -Force $WorkDir -ErrorAction SilentlyContinue
}
`)

	return b.String(), nil
}
