package renderer

import (
	"fmt"
	"strings"

	"github.com/kunorikiku/yet-another-overlay-generator/internal/compiler"
	"github.com/kunorikiku/yet-another-overlay-generator/internal/model"
	"github.com/kunorikiku/yet-another-overlay-generator/internal/naming"
)

// DeployNodeInfo holds per-node SSH and artifact info for deploy script generation
type DeployNodeInfo struct {
	NodeID            string // unique node ID; keys the remote upload path (/tmp/<NodeID>-install.sh)
	NodeName          string
	SafeInstallerName string // safe file name for the installer (e.g. "node-name.install.sh")
	SSHTarget         string // ssh_alias or user@host
	SSHPort           int
	SSHKeyPath        string
	HasSSH            bool
	WgInterfaces      []string // WireGuard interface names (e.g. "wg-alpha", "wg-beta")
	HasBabel          bool     // whether this node runs Babel
	IsClient          bool     // client nodes use wg0 instead of per-peer interfaces
}

// DeployScriptConfig holds all nodes for one combined deploy script
type DeployScriptConfig struct {
	ProjectName string
	Nodes       []DeployNodeInfo
}

// RenderDeployScripts generates a bash deploy script and a PowerShell deploy script.
// Both scripts iterate all nodes that have SSH details configured, SCP the
// self-extracting installer to the remote, and execute it via sudo.
// In uninstall mode, the scripts SSH in and run teardown commands directly
// without uploading any installer.
// Returns (bashScript, ps1Script, error).
func RenderDeployScripts(topo *model.Topology, peerMap map[string][]compiler.PeerInfo, babelConfigs map[string]string) (string, string, error) {
	config := DeployScriptConfig{
		ProjectName: topo.Project.Name,
	}

	// Domain 索引：HasBabel 的回退判断需要按节点所属域的 routing_mode 决定，
	// 与 shouldRunBabel 一致（见下方 D61 修复）。
	domainMap := make(map[string]*model.Domain)
	for i := range topo.Domains {
		domainMap[topo.Domains[i].ID] = &topo.Domains[i]
	}

	for i := range topo.Nodes {
		node := topo.Nodes[i]
		info := DeployNodeInfo{
			NodeID:            node.ID,
			NodeName:          node.Name,
			SafeInstallerName: naming.SafeInstallerFileName(node.Name),
			SSHPort:           22,
			IsClient:          node.Role == "client",
		}

		if node.SSHAlias != "" {
			info.SSHTarget = node.SSHAlias
			info.SSHPort = 0 // alias → let ssh_config decide
			info.HasSSH = true
		} else if node.SSHHost != "" {
			user := node.SSHUser
			if user == "" {
				user = "root"
			}
			info.SSHTarget = fmt.Sprintf("%s@%s", user, node.SSHHost)
			info.HasSSH = true
		}

		if node.SSHPort > 0 {
			info.SSHPort = node.SSHPort
		}
		info.SSHKeyPath = node.SSHKeyPath

		// Collect WireGuard interface names from peer map
		if peers, ok := peerMap[node.ID]; ok {
			for _, p := range peers {
				info.WgInterfaces = append(info.WgInterfaces, p.InterfaceName)
			}
		}
		if info.IsClient {
			info.WgInterfaces = []string{"wg0"}
		}

		// Check if this node runs Babel: use compiled configs if available,
		// otherwise fall back to a domain-aware decision that mirrors
		// shouldRunBabel (D61). The previous role-only fallback marked every
		// non-client node as Babel-bearing, which is wrong when the node's
		// domain uses a non-babel routing_mode — uninstall would then try to
		// tear down a Babel daemon that was never deployed.
		if babelConfigs != nil {
			if _, ok := babelConfigs[node.ID]; ok {
				info.HasBabel = true
			}
		} else {
			info.HasBabel = shouldRunBabel(&topo.Nodes[i], domainMap[node.DomainID])
		}

		config.Nodes = append(config.Nodes, info)
	}

	bash, err := renderBashDeploy(config)
	if err != nil {
		return "", "", err
	}

	ps1, err := renderPS1Deploy(config)
	if err != nil {
		return "", "", err
	}

	return bash, ps1, nil
}

// buildSSHOpts returns (sshOpts, scpOpts) strings.
// sshOpts has a leading space if non-empty (for "ssh%s target" formatting).
// scpOpts has NO leading space (for "scp %s ..." formatting).
func buildSSHOpts(node DeployNodeInfo, quoteStyle string) (string, string) {
	var sshParts, scpParts []string

	if node.SSHPort > 0 {
		sshParts = append(sshParts, fmt.Sprintf("-p %d", node.SSHPort))
		scpParts = append(scpParts, fmt.Sprintf("-P %d", node.SSHPort))
	}
	if node.SSHKeyPath != "" {
		switch quoteStyle {
		case "go": // Go %q quoting for bash
			sshParts = append(sshParts, fmt.Sprintf("-i %q", node.SSHKeyPath))
			scpParts = append(scpParts, fmt.Sprintf("-i %q", node.SSHKeyPath))
		case "dquote": // double-quote for PowerShell
			sshParts = append(sshParts, fmt.Sprintf(`-i "%s"`, node.SSHKeyPath))
			scpParts = append(scpParts, fmt.Sprintf(`-i "%s"`, node.SSHKeyPath))
		}
	}

	sshOpts := ""
	if len(sshParts) > 0 {
		sshOpts = " " + strings.Join(sshParts, " ")
	}
	scpOpts := strings.Join(scpParts, " ")
	return sshOpts, scpOpts
}

func renderBashDeploy(config DeployScriptConfig) (string, error) {
	var b strings.Builder

	b.WriteString(`#!/usr/bin/env bash
# Auto-deploy script for project: ` + config.ProjectName + `
# Generated by Overlay Network Config Orchestrator
#
# Usage:
#   bash deploy-all.sh [--clean] <path-to-artifacts.zip>    Deploy overlay
#   bash deploy-all.sh --uninstall <path-to-artifacts.zip>   Remove overlay from all nodes
#
# Options:
#   --clean      Remove ALL existing WireGuard interfaces (wg*) before deploying.
#                Use this when switching from a single-interface (wg0) layout to
#                per-peer interfaces, or vice versa.
#   --uninstall  Completely remove the overlay from all nodes via SSH.
#                Stops all WireGuard interfaces, removes configs, stops Babel,
#                removes dummy0, and reloads systemd. No installer upload needed.
#
# This script SSHs into each configured node. Nodes without SSH details are skipped.
# SSH failures are caught per-node and do not abort the entire run.

set -uo pipefail

CLEAN=0
UNINSTALL=0
ARTIFACTS_ZIP=""

for arg in "$@"; do
    case "$arg" in
        --clean) CLEAN=1 ;;
        --uninstall|-u) UNINSTALL=1 ;;
        *) ARTIFACTS_ZIP="$arg" ;;
    esac
done

if [ "$UNINSTALL" -eq 0 ] && [ -z "$ARTIFACTS_ZIP" ]; then
    echo "Usage: $0 [--clean] <path-to-artifacts.zip>"
    echo "       $0 --uninstall"
    echo ""
    echo "Options:"
    echo "  --clean      Remove all existing WireGuard interfaces before deploying"
    echo "  --uninstall  Completely remove the overlay from all nodes"
    echo ""
    echo "Download the artifacts ZIP from the web UI (Export Artifacts button),"
    echo "then run this script pointing at the downloaded file."
    exit 1
fi

WORKDIR=""
if [ -n "$ARTIFACTS_ZIP" ]; then
    if [ ! -f "$ARTIFACTS_ZIP" ]; then
        echo "ERROR: File not found: $ARTIFACTS_ZIP" >&2
        exit 1
    fi

    # Extract to a temp directory
    WORKDIR="$(mktemp -d -t overlay-deploy-XXXXXX)"
    cleanup() { rm -rf "$WORKDIR"; }
    trap cleanup EXIT

    echo "Extracting artifacts..."
    unzip -q "$ARTIFACTS_ZIP" -d "$WORKDIR"
fi

if [ "$UNINSTALL" -eq 1 ]; then
    echo ""
    echo "*** UNINSTALL MODE — overlay will be removed from all nodes ***"
    echo ""
fi

FAILED=0
SKIPPED=0
SUCCESS=0

`)

	for _, node := range config.Nodes {
		b.WriteString(fmt.Sprintf("# --- Node: %s ---\n", node.NodeName))

		// Shell-escaped forms used at every interpolation site below. SSHTarget
		// (ssh_alias or user@ssh_host) and NodeName are user-supplied and are
		// spliced into a script that runs on the OPERATOR's machine; without
		// quoting an ssh_host of "x; rm -rf $HOME #" injects commands locally
		// (D7) and a single quote in a node name breaks the echo / heredoc
		// (D16). targetQuoted is a single-quoted bash token suitable wherever
		// the target was a bare argument (ssh / scp), and nameQuoted is the same
		// for echo arguments. This mirrors the existing %q treatment of
		// SSHKeyPath in buildSSHOpts.
		targetQuoted := bashSingleQuote(node.SSHTarget)
		nameQuoted := bashSingleQuote(node.NodeName)

		// installerFile is the ZIP-entry / local-lookup name (canonical safe
		// name). remoteInstaller is the remote upload path, keyed on the unique
		// node ID so two nodes whose names sanitize identically cannot clobber
		// each other's payload at /tmp (D31). The SCP destination, the ssh
		// execute path, and the rm cleanup MUST all use remoteInstaller.
		installerFile := node.SafeInstallerName
		remoteInstaller := node.NodeID + "-install.sh"
		if !node.HasSSH {
			b.WriteString(fmt.Sprintf(`echo ""
echo "=== "%s": SKIPPED (no SSH details configured) ==="
SKIPPED=$((SKIPPED + 1))
`, nameQuoted))
			b.WriteString("\n")
			continue
		}

		sshOpts, scpOpts := buildSSHOpts(node, "go")

		// scpCmd: "scp -P 22 -i key" or just "scp" when no opts
		scpCmd := "scp"
		if scpOpts != "" {
			scpCmd = "scp " + scpOpts
		}

		// Build the inline uninstall script for this node. These echo lines run
		// on the REMOTE node inside a quoted heredoc, but NodeName is still
		// interpolated into single-quoted echo strings here — a single quote in
		// the name would terminate the echo string early (D16). Splice the
		// bashSingleQuote token rather than the raw name so the name is always a
		// single inert shell token.
		var uninstallCmds strings.Builder
		uninstallCmds.WriteString("set -uo pipefail\n")
		uninstallCmds.WriteString(fmt.Sprintf("echo '[Stage 1/4] Stopping WireGuard interfaces on '%s'...'\n", nameQuoted))

		// Stop and disable WireGuard interfaces
		for _, iface := range node.WgInterfaces {
			uninstallCmds.WriteString(fmt.Sprintf("wg-quick down %s 2>/dev/null || true\n", iface))
			uninstallCmds.WriteString(fmt.Sprintf("systemctl disable wg-quick@%s 2>/dev/null || true\n", iface))
			uninstallCmds.WriteString(fmt.Sprintf("rm -f /etc/wireguard/%s.conf\n", iface))
		}

		// Stop any remaining WireGuard interfaces
		uninstallCmds.WriteString("for _i in $(wg show interfaces 2>/dev/null); do wg-quick down \"$_i\" 2>/dev/null || true; systemctl disable \"wg-quick@$_i\" 2>/dev/null || true; done\n")
		uninstallCmds.WriteString("rm -f /etc/wireguard/*.conf\n")

		if node.HasBabel {
			uninstallCmds.WriteString(fmt.Sprintf("echo '[Stage 2/4] Stopping Babel routing daemon on '%s'...'\n", nameQuoted))
			uninstallCmds.WriteString("systemctl stop babeld 2>/dev/null || true\n")
			uninstallCmds.WriteString("systemctl disable babeld 2>/dev/null || true\n")
			uninstallCmds.WriteString("rm -f /etc/babel/babeld.conf /etc/babeld.conf\n")
			uninstallCmds.WriteString("rm -rf /etc/systemd/system/babeld.service.d\n")
		}

		// Remove sysctl overlay config
		uninstallCmds.WriteString(fmt.Sprintf("echo '[Stage 3/4] Removing overlay network configuration on '%s'...'\n", nameQuoted))
		uninstallCmds.WriteString("rm -f /etc/sysctl.d/99-overlay.conf\n")
		uninstallCmds.WriteString("sysctl --system > /dev/null 2>&1 || true\n")

		if !node.IsClient {
			// Remove overlay SNAT rule and service
			uninstallCmds.WriteString("nft delete table inet overlay-snat 2>/dev/null || true\n")
			uninstallCmds.WriteString("iptables -t nat -D POSTROUTING -o 'wg-+' -s 10.10.0.0/24 -j SNAT --to-source $(ip -4 addr show dummy0 2>/dev/null | grep -oP 'inet \\K[^/]+' || echo 0.0.0.0) 2>/dev/null || true\n")
			uninstallCmds.WriteString("systemctl disable overlay-snat.service 2>/dev/null || true\n")
			uninstallCmds.WriteString("rm -f /etc/systemd/system/overlay-snat.service\n")
			// Remove dummy0 overlay interface
			uninstallCmds.WriteString("ip link del dummy0 2>/dev/null || true\n")
			uninstallCmds.WriteString("systemctl disable overlay-dummy.service 2>/dev/null || true\n")
			uninstallCmds.WriteString("rm -f /etc/systemd/system/overlay-dummy.service\n")
		}

		uninstallCmds.WriteString(fmt.Sprintf("echo '[Stage 4/4] Reloading systemd on '%s'...'\n", nameQuoted))
		uninstallCmds.WriteString("systemctl daemon-reload || { echo 'ERROR: systemctl daemon-reload failed' >&2; exit 1; }\n")
		uninstallCmds.WriteString(fmt.Sprintf("echo 'Overlay removed from '%s'.'\n", nameQuoted))

		// Every %s that carries SSHTarget is filled with targetQuoted (a
		// single-quoted bash token), and every %s that carries NodeName is
		// filled with nameQuoted. The echo lines break out of their surrounding
		// double quotes ("...text..."<token>"...text...") so the spliced token
		// stays single-quoted and inert; the ssh / scp argument sites take the
		// token in place of the previously-bare target. The scp destination
		// renders as 'target':/tmp/<id>-install.sh — the :/tmp suffix sits
		// outside the closing quote, which is valid scp syntax.
		b.WriteString(fmt.Sprintf(`echo ""
if [ "$UNINSTALL" -eq 1 ]; then
    echo "=== Uninstalling from "%s" ("%s") ==="
    if ! ssh%s %s "echo ok" >/dev/null 2>&1; then
        echo "  ERROR: SSH connection to "%s" failed." >&2
        FAILED=$((FAILED + 1))
    else
        if ssh%s %s sudo bash -s <<'UNINSTALL_EOF'; then
%s
UNINSTALL_EOF
            echo "  SUCCESS: "%s" uninstalled."
            SUCCESS=$((SUCCESS + 1))
        else
            echo "  ERROR: Uninstall failed on "%s" (exit code: $?)." >&2
            FAILED=$((FAILED + 1))
        fi
    fi
else
    echo "=== Deploying to "%s" ("%s") ==="
    INSTALLER="$WORKDIR/%s"
    if [ ! -f "$INSTALLER" ]; then
        echo "  WARNING: Installer %s not found in archive, skipping."
        SKIPPED=$((SKIPPED + 1))
    else
        # Test SSH connectivity first
        if ! ssh%s %s "echo ok" >/dev/null 2>&1; then
            echo "  ERROR: SSH connection to "%s" failed." >&2
            FAILED=$((FAILED + 1))
        else
            # Clean previous WireGuard configs if requested
            if [ "$CLEAN" -eq 1 ]; then
                echo "  Cleaning existing WireGuard interfaces on "%s"..."
                ssh%s %s sudo bash -s <<'CLEAN_EOF' 2>/dev/null || true
for iface in $(ip -o link show type wireguard 2>/dev/null | awk -F: '{print $2}' | tr -d ' '); do
    wg-quick down "$iface" 2>/dev/null || ip link del "$iface" 2>/dev/null || true
done
rm -f /etc/wireguard/wg*.conf
nft delete table inet overlay-snat 2>/dev/null || true
_snat_ip=$(ip -4 addr show dummy0 2>/dev/null | grep -oP 'inet \K[^/]+' || true)
[ -n "$_snat_ip" ] && iptables -t nat -D POSTROUTING -o 'wg-+' -s 10.10.0.0/24 -j SNAT --to-source "$_snat_ip" 2>/dev/null || true
systemctl disable overlay-snat.service 2>/dev/null || true
rm -f /etc/systemd/system/overlay-snat.service
CLEAN_EOF
            fi

            if %s "$INSTALLER" %s:/tmp/%s; then
                if ssh%s %s "sudo bash /tmp/%s && rm -f /tmp/%s"; then
                    echo "  SUCCESS: "%s" deployed."
                    SUCCESS=$((SUCCESS + 1))
                else
                    echo "  ERROR: Installation script failed on "%s" (exit code: $?)." >&2
                    FAILED=$((FAILED + 1))
                fi
            else
                echo "  ERROR: SCP upload to "%s" failed." >&2
                FAILED=$((FAILED + 1))
            fi
        fi
    fi
fi
`,
			// Uninstall branch
			nameQuoted, targetQuoted,
			sshOpts, targetQuoted,
			nameQuoted,
			sshOpts, targetQuoted,
			uninstallCmds.String(),
			nameQuoted,
			nameQuoted,
			// Deploy branch
			nameQuoted, targetQuoted,
			installerFile,
			installerFile,
			sshOpts, targetQuoted,
			nameQuoted,
			// Clean step
			nameQuoted,
			sshOpts, targetQuoted,
			// SCP + install (remote path keyed on node ID, D31)
			scpCmd, targetQuoted, remoteInstaller,
			sshOpts, targetQuoted, remoteInstaller, remoteInstaller,
			nameQuoted,
			nameQuoted,
			nameQuoted,
		))
		b.WriteString("\n")
	}

	b.WriteString(`echo ""
echo "============================================================"
if [ "$UNINSTALL" -eq 1 ]; then
    echo "  Uninstall Summary"
else
    echo "  Deploy Summary"
fi
echo "  Success: $SUCCESS  Skipped: $SKIPPED  Failed: $FAILED"
echo "============================================================"

if [ "$FAILED" -gt 0 ]; then
    exit 1
fi
`)

	return b.String(), nil
}

func renderPS1Deploy(config DeployScriptConfig) (string, error) {
	var b strings.Builder

	b.WriteString(`# Auto-deploy script for project: ` + config.ProjectName + `
# Generated by Overlay Network Config Orchestrator
#
# Usage:
#   .\deploy-all.ps1 -ArtifactsZip <path-to-artifacts.zip> [-Clean]    Deploy overlay
#   .\deploy-all.ps1 -Uninstall                                         Remove overlay
#
# Options:
#   -Clean      Remove ALL existing WireGuard interfaces (wg*) before deploying.
#   -Uninstall  Completely remove the overlay from all nodes via SSH.
#               No artifacts ZIP needed.

param(
    [string]$ArtifactsZip,

    [switch]$Clean,

    [switch]$Uninstall
)

$ErrorActionPreference = "Continue"

if (-not $Uninstall -and [string]::IsNullOrEmpty($ArtifactsZip)) {
    Write-Host "Usage: .\deploy-all.ps1 -ArtifactsZip <path> [-Clean]"
    Write-Host "       .\deploy-all.ps1 -Uninstall"
    exit 1
}

$WorkDir = $null

if (-not [string]::IsNullOrEmpty($ArtifactsZip)) {
    if (-not (Test-Path $ArtifactsZip)) {
        Write-Error "File not found: $ArtifactsZip"
        exit 1
    }

    # Extract to temp
    $WorkDir = Join-Path ([System.IO.Path]::GetTempPath()) ("overlay-deploy-" + [System.Guid]::NewGuid().ToString("N").Substring(0,8))
    New-Item -ItemType Directory -Path $WorkDir -Force | Out-Null
}

# Clean script sent to remote via stdin (single-quoted — no PS expansion)
$CleanScript = 'for iface in $(ip -o link show type wireguard 2>/dev/null | awk -F: ''{print $2}'' | tr -d " "); do wg-quick down "$iface" 2>/dev/null || ip link del "$iface" 2>/dev/null || true; done; rm -f /etc/wireguard/wg*.conf; nft delete table inet overlay-snat 2>/dev/null || true; _snat_ip=$(ip -4 addr show dummy0 2>/dev/null | grep -oP ''inet \K[^/]+'' || true); [ -n "$_snat_ip" ] && iptables -t nat -D POSTROUTING -o ''wg-+'' -s 10.10.0.0/24 -j SNAT --to-source "$_snat_ip" 2>/dev/null || true; systemctl disable overlay-snat.service 2>/dev/null || true; rm -f /etc/systemd/system/overlay-snat.service'

try {
    if ($WorkDir) {
        Write-Host "Extracting artifacts..."
        Expand-Archive -Path $ArtifactsZip -DestinationPath $WorkDir -Force
    }

    if ($Uninstall) {
        Write-Host ""
        Write-Host "*** UNINSTALL MODE — overlay will be removed from all nodes ***" -ForegroundColor Yellow
        Write-Host ""
    }

    $Failed = 0
    $Skipped = 0
    $Success = 0

`)

	for _, node := range config.Nodes {
		// installerFile is the ZIP-entry / local-lookup name (canonical safe
		// name). remoteInstaller is the remote upload path, keyed on the unique
		// node ID so identically-sanitizing names cannot clobber each other at
		// /tmp (D31). SCP destination, ssh execute, and rm cleanup use it.
		installerFile := node.SafeInstallerName
		remoteInstaller := node.NodeID + "-install.sh"

		// Shell-escaped forms for the two distinct quoting contexts of the PS1
		// script. PowerShell contexts (the & ssh / & scp call-operator arguments
		// and the Write-Host strings) take powerShellArgQuote: an unquoted target
		// splits on spaces and an embedded double quote breaks the one quoted scp
		// site (D43). The bash here-string body (@'...'@ piped to ssh ... bash)
		// is interpreted by the REMOTE shell, so NodeName interpolated into its
		// single-quoted echo lines takes bashSingleQuote, same idiom as the bash
		// renderer. scpDestPSArg wraps the whole "target:/tmp/<id>-install.sh"
		// destination as one escaped PowerShell argument.
		targetPSArg := powerShellArgQuote(node.SSHTarget)
		namePSStr := powerShellArgQuote(node.NodeName)
		nameBashQuoted := bashSingleQuote(node.NodeName)
		scpDestPSArg := powerShellArgQuote(node.SSHTarget + ":/tmp/" + remoteInstaller)

		if !node.HasSSH {
			b.WriteString(fmt.Sprintf(`    Write-Host ""
    Write-Host ("=== " + %s + ": SKIPPED (no SSH details configured) ===")
    $Skipped++
`, namePSStr))
			b.WriteString("\n")
			continue
		}

		sshOpts, scpOpts := buildSSHOpts(node, "dquote")

		scpCmd := "scp"
		if scpOpts != "" {
			scpCmd = "scp " + scpOpts
		}

		// Build the inline uninstall script for this node (multi-line, for PS1
		// here-string). The @'...'@ here-string is literal in PowerShell, but the
		// body is piped to ssh ... sudo bash -s and run on the REMOTE node, so
		// NodeName interpolated into these single-quoted echo lines is escaped for
		// the bash single-quote context (D16/D43) via nameBashQuoted.
		var uninstallCmds strings.Builder
		uninstallCmds.WriteString("set -uo pipefail\n")
		uninstallCmds.WriteString(fmt.Sprintf("echo '[Stage 1/4] Stopping WireGuard interfaces on '%s'...'\n", nameBashQuoted))
		for _, iface := range node.WgInterfaces {
			uninstallCmds.WriteString(fmt.Sprintf("wg-quick down %s 2>/dev/null || true\n", iface))
			uninstallCmds.WriteString(fmt.Sprintf("systemctl disable wg-quick@%s 2>/dev/null || true\n", iface))
			uninstallCmds.WriteString(fmt.Sprintf("rm -f /etc/wireguard/%s.conf\n", iface))
		}
		uninstallCmds.WriteString("for _i in $(wg show interfaces 2>/dev/null); do wg-quick down \"$_i\" 2>/dev/null || true; systemctl disable \"wg-quick@$_i\" 2>/dev/null || true; done\n")
		uninstallCmds.WriteString("rm -f /etc/wireguard/*.conf\n")
		if node.HasBabel {
			uninstallCmds.WriteString(fmt.Sprintf("echo '[Stage 2/4] Stopping Babel routing daemon on '%s'...'\n", nameBashQuoted))
			uninstallCmds.WriteString("systemctl stop babeld 2>/dev/null || true\n")
			uninstallCmds.WriteString("systemctl disable babeld 2>/dev/null || true\n")
			uninstallCmds.WriteString("rm -f /etc/babel/babeld.conf /etc/babeld.conf\n")
			uninstallCmds.WriteString("rm -rf /etc/systemd/system/babeld.service.d\n")
		}
		uninstallCmds.WriteString(fmt.Sprintf("echo '[Stage 3/4] Removing overlay network configuration on '%s'...'\n", nameBashQuoted))
		uninstallCmds.WriteString("rm -f /etc/sysctl.d/99-overlay.conf\n")
		uninstallCmds.WriteString("sysctl --system > /dev/null 2>&1 || true\n")
		if !node.IsClient {
			uninstallCmds.WriteString("nft delete table inet overlay-snat 2>/dev/null || true\n")
			uninstallCmds.WriteString("_snat_ip=$(ip -4 addr show dummy0 2>/dev/null | grep -oP 'inet \\K[^/]+' || true)\n")
			uninstallCmds.WriteString("[ -n \"$_snat_ip\" ] && iptables -t nat -D POSTROUTING -o 'wg-+' -s 10.10.0.0/24 -j SNAT --to-source \"$_snat_ip\" 2>/dev/null || true\n")
			uninstallCmds.WriteString("systemctl disable overlay-snat.service 2>/dev/null || true\n")
			uninstallCmds.WriteString("rm -f /etc/systemd/system/overlay-snat.service\n")
			uninstallCmds.WriteString("ip link del dummy0 2>/dev/null || true\n")
			uninstallCmds.WriteString("systemctl disable overlay-dummy.service 2>/dev/null || true\n")
			uninstallCmds.WriteString("rm -f /etc/systemd/system/overlay-dummy.service\n")
		}
		uninstallCmds.WriteString(fmt.Sprintf("echo '[Stage 4/4] Reloading systemd on '%s'...'\n", nameBashQuoted))
		uninstallCmds.WriteString("systemctl daemon-reload\n")
		uninstallCmds.WriteString(fmt.Sprintf("echo 'Overlay removed from '%s'.'\n", nameBashQuoted))

		// Each Write-Host line uses string concatenation (+) so the escaped
		// PowerShell value (namePSStr / targetPSArg, both already double-quoted
		// by powerShellArgQuote) is a complete sub-expression rather than text
		// spliced inside another double-quoted string where its own quotes would
		// collide. The & ssh / & scp call sites take targetPSArg in place of the
		// previously-bare target, and the one scp destination takes the whole
		// "target:/tmp/<id>-install.sh" pre-quoted as scpDestPSArg.
		b.WriteString(fmt.Sprintf(`    Write-Host ""
    if ($Uninstall) {
        Write-Host ("=== Uninstalling from " + %s + " (" + %s + ") ===")
        $sshTest = & ssh%s %s "echo ok" 2>&1
        if ($LASTEXITCODE -ne 0) {
            Write-Host ("  ERROR: SSH connection to " + %s + " failed.") -ForegroundColor Red
            $Failed++
        } else {
            $uninstallScript = @'
%s'@
            $uninstallScript | & ssh%s %s sudo bash -s
            if ($LASTEXITCODE -ne 0) {
                Write-Host ("  ERROR: Uninstall failed on " + %s + ".") -ForegroundColor Red
                $Failed++
            } else {
                Write-Host ("  SUCCESS: " + %s + " uninstalled.")
                $Success++
            }
        }
    } else {
        Write-Host ("=== Deploying to " + %s + " (" + %s + ") ===")
        $Installer = Join-Path $WorkDir "%s"
        if (-not (Test-Path $Installer)) {
            Write-Warning "Installer %s not found in archive, skipping."
            $Skipped++
        } else {
            $sshTest = & ssh%s %s "echo ok" 2>&1
            if ($LASTEXITCODE -ne 0) {
                Write-Host ("  ERROR: SSH connection to " + %s + " failed.") -ForegroundColor Red
                $Failed++
            } else {
                if ($Clean) {
                    Write-Host ("  Cleaning existing WireGuard interfaces on " + %s + "...")
                    $CleanScript | & ssh%s %s sudo bash -s 2>$null
                }

                & %s $Installer %s
                if ($LASTEXITCODE -ne 0) {
                    Write-Host ("  ERROR: SCP upload to " + %s + " failed.") -ForegroundColor Red
                    $Failed++
                } else {
                    & ssh%s %s "sudo bash /tmp/%s && rm -f /tmp/%s"
                    if ($LASTEXITCODE -ne 0) {
                        Write-Host ("  ERROR: Installation script failed on " + %s + " (exit code: $LASTEXITCODE).") -ForegroundColor Red
                        $Failed++
                    } else {
                        Write-Host ("  SUCCESS: " + %s + " deployed.")
                        $Success++
                    }
                }
            }
        }
    }
`,
			// Uninstall branch
			namePSStr, targetPSArg,
			sshOpts, targetPSArg,
			namePSStr,
			uninstallCmds.String(),
			sshOpts, targetPSArg,
			namePSStr,
			namePSStr,
			// Deploy branch
			namePSStr, targetPSArg,
			installerFile,
			installerFile,
			sshOpts, targetPSArg,
			namePSStr,
			// Clean step
			namePSStr,
			sshOpts, targetPSArg,
			// SCP + install (destination pre-quoted, remote path keyed on node ID, D31)
			scpCmd, scpDestPSArg,
			namePSStr,
			sshOpts, targetPSArg, remoteInstaller, remoteInstaller,
			namePSStr,
			namePSStr,
		))
		b.WriteString("\n")
	}

	b.WriteString(`    Write-Host ""
    Write-Host "============================================================"
    if ($Uninstall) {
        Write-Host "  Uninstall Summary"
    } else {
        Write-Host "  Deploy Summary"
    }
    Write-Host "  Success: $Success  Skipped: $Skipped  Failed: $Failed"
    Write-Host "============================================================"

    if ($Failed -gt 0) {
        exit 1
    }
} finally {
    if ($WorkDir) { Remove-Item -Recurse -Force $WorkDir -ErrorAction SilentlyContinue }
}
`)

	return b.String(), nil
}