package renderer

import (
	"github.com/kunorikiku/yet-another-overlay-generator/internal/model"
)

// InstallScriptConfig 
type InstallScriptConfig struct {
	NodeName       string
	NodeRole       string
	Platform       string
	OverlayIP      string
	MTU            int
	HasBabel       bool
	HasForward     bool
	WgConfName     string
	BabelConfName  string
	SysctlConfName string
}

const installScriptTemplate = `#!/usr/bin/env bash
# Install script for node: {{ .NodeName }}
# Generated by Overlay Network Config Orchestrator
# Platform: {{ .Platform }}
# Role: {{ .NodeRole }}

set -euo pipefail

# ============================================================
# Phase 0: Cleanup Previous Installation
# ============================================================

echo "=== Phase 0: Cleanup Previous Installation ==="

WG_IFACE="{{ .WgConfName }}"
WG_IFACE="${WG_IFACE%.conf}"

# Stop WireGuard interface if running
if command -v wg >/dev/null 2>&1 && wg show "$WG_IFACE" > /dev/null 2>&1; then
    echo "  Stopping existing WireGuard interface: $WG_IFACE..."
    wg-quick down "$WG_IFACE" 2>/dev/null || true
    echo "  WireGuard interface $WG_IFACE stopped"
fi

# Disable WireGuard auto-start
if systemctl is-enabled "wg-quick@$WG_IFACE" >/dev/null 2>&1; then
    systemctl disable "wg-quick@$WG_IFACE" 2>/dev/null || true
    echo "  Disabled wg-quick@$WG_IFACE auto-start"
fi

{{ if .HasBabel -}}
# Stop Babel if running
if systemctl is-active babeld >/dev/null 2>&1; then
    echo "  Stopping Babel daemon..."
    systemctl stop babeld 2>/dev/null || true
    echo "  Babel daemon stopped"
fi
if systemctl is-enabled babeld >/dev/null 2>&1; then
    systemctl disable babeld 2>/dev/null || true
    echo "  Disabled babeld auto-start"
fi
{{ end -}}

# Remove old configuration files
if [ -f "/etc/wireguard/{{ .WgConfName }}" ]; then
    rm -f "/etc/wireguard/{{ .WgConfName }}"
    echo "  Removed old WireGuard config: /etc/wireguard/{{ .WgConfName }}"
fi

{{ if .HasBabel -}}
# Clean old babel config from both legacy and standard locations
for _bcf in "/etc/babel/{{ .BabelConfName }}" "/etc/{{ .BabelConfName }}"; do
    if [ -f "$_bcf" ]; then
        rm -f "$_bcf"
        echo "  Removed old Babel config: $_bcf"
    fi
done
{{ end -}}

if [ -f "/etc/sysctl.d/{{ .SysctlConfName }}" ]; then
    rm -f "/etc/sysctl.d/{{ .SysctlConfName }}"
    echo "  Removed old sysctl config: /etc/sysctl.d/{{ .SysctlConfName }}"
fi

echo "Phase 0 complete."

# ============================================================
# Phase 1: Environment Preparation
# ============================================================

echo "=== Phase 1: Environment Preparation ==="

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Verify checksums if available
if [ -f "$SCRIPT_DIR/checksums.sha256" ]; then
    echo "Verifying file integrity..."
    cd "$SCRIPT_DIR"
    if ! sha256sum --status -c checksums.sha256; then
        echo "ERROR: Checksum validation failed! The configuration files may have been tampered with." >&2
        echo "If you intentionally modified them, update or remove checksums.sha256." >&2
        exit 1
    fi
    echo "Checksum validation passed."
    cd - >/dev/null
fi

# Check root
if [ "$(id -u)" -ne 0 ]; then
    echo "ERROR: This script must be run as root" >&2
    exit 1
fi

# Detect OS
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS_ID="$ID"
    OS_VERSION="$VERSION_ID"
    echo "Detected OS: $OS_ID $OS_VERSION"
else
    echo "ERROR: Cannot detect OS (no /etc/os-release)" >&2
    exit 1
fi

# Verify supported platform
case "$OS_ID" in
    debian|ubuntu)
        echo "Supported platform: $OS_ID"
        ;;
    *)
        echo "WARNING: Unsupported platform: $OS_ID (targeting Debian/Ubuntu)" >&2
        ;;
esac

# Install dependencies
echo "Installing dependencies..."

if [ "$OS_ID" = "debian" ] || [ "$OS_ID" = "ubuntu" ]; then
    export DEBIAN_FRONTEND=noninteractive

    ensure_pkg() {
        local pkg="$1"
        if dpkg -s "$pkg" >/dev/null 2>&1; then
            echo "  - $pkg already installed"
            return 0
        fi
        echo "  - installing $pkg"
        apt-get install -y -qq "$pkg"
    }

    apt-get update -qq

    # Base runtime tools
    ensure_pkg iproute2
    ensure_pkg ca-certificates
    ensure_pkg coreutils

    # WireGuard stack
    ensure_pkg wireguard
    ensure_pkg wireguard-tools

{{ if .HasBabel -}}
    # Dynamic routing daemon
    ensure_pkg babeld
{{ end -}}
else
    echo "Automatic installation is not supported on $OS_ID; checking existing dependencies..."

    missing_bins=""

    require_bin() {
        local bin="$1"
        if ! command -v "$bin" >/dev/null 2>&1; then
            missing_bins="$missing_bins $bin"
        fi
    }

    require_bin wg
    require_bin wg-quick
    require_bin ip
    require_bin sha256sum
{{ if .HasBabel -}}
    require_bin babeld
{{ end -}}

    if [ -n "$missing_bins" ]; then
        echo "ERROR: Missing required commands on $OS_ID:$missing_bins" >&2
        echo "Please install the corresponding packages manually, then rerun this script." >&2
        exit 1
    fi

    echo "All required dependencies are present on $OS_ID."
fi

# Create directories
mkdir -p /etc/wireguard
{{ if .HasBabel -}}
mkdir -p /etc/babel
{{ end -}}

echo "Phase 1 complete."

# ============================================================
# Phase 2: Deploy Configuration
# ============================================================

echo "=== Phase 2: Deploy Configuration ==="

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Deploy WireGuard configuration
echo "Deploying WireGuard configuration..."
cp "$SCRIPT_DIR/wireguard/{{ .WgConfName }}" /etc/wireguard/{{ .WgConfName }}
chmod 600 /etc/wireguard/{{ .WgConfName }}
echo "  WireGuard config deployed: /etc/wireguard/{{ .WgConfName }}"

{{ if .HasBabel -}}
# Deploy Babel configuration
echo "Deploying Babel configuration..."
cp "$SCRIPT_DIR/babel/{{ .BabelConfName }}" /etc/babel/{{ .BabelConfName }}
echo "  Babel config deployed: /etc/babel/{{ .BabelConfName }}"
{{ end -}}

# Deploy sysctl configuration
echo "Deploying sysctl configuration..."
cp "$SCRIPT_DIR/sysctl/{{ .SysctlConfName }}" /etc/sysctl.d/{{ .SysctlConfName }}
echo "  Sysctl config deployed: /etc/sysctl.d/{{ .SysctlConfName }}"

echo "Phase 2 complete."

# ============================================================
# Phase 3: Activate and Verify
# ============================================================

echo "=== Phase 3: Activate and Verify ==="

# Apply sysctl
echo "Applying sysctl settings..."
sysctl --system > /dev/null 2>&1
{{ if .HasForward -}}
echo "  IPv4 forwarding: $(cat /proc/sys/net/ipv4/ip_forward)"
{{ end -}}

# Start WireGuard
echo "Starting WireGuard interface: $WG_IFACE..."
wg-quick up "$WG_IFACE"
echo "  WireGuard interface $WG_IFACE is up"

# Enable WireGuard on boot
systemctl enable wg-quick@"$WG_IFACE" 2>/dev/null || true

{{ if .HasBabel -}}
# Configure babeld systemd service to use our config and depend on WireGuard
echo "Configuring babeld systemd service..."
mkdir -p /etc/systemd/system/babeld.service.d
cat > /etc/systemd/system/babeld.service.d/override.conf << 'BABEL_OVERRIDE'
[Unit]
Description=Babel routing daemon (overlay)
After=network.target wg-quick@{{ .WgConfName }}.service
Wants=wg-quick@{{ .WgConfName }}.service

[Service]
Type=simple
ExecStart=
ExecStart=/usr/sbin/babeld -c /etc/babel/{{ .BabelConfName }}
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
BABEL_OVERRIDE
# Strip the .conf suffix for wg-quick@ service name
sed -i "s/wg-quick@{{ .WgConfName }}/wg-quick@${WG_IFACE}/g" /etc/systemd/system/babeld.service.d/override.conf
systemctl daemon-reload

# Start Babel
echo "Starting Babel..."
systemctl restart babeld
systemctl enable babeld
echo "  Babel daemon started"
{{ end -}}

# Show status
echo ""
echo "============================================================"
echo "  Node: {{ .NodeName }}"
echo "  Overlay IP: {{ .OverlayIP }}"
echo "  Role: {{ .NodeRole }}"
{{- if gt .MTU 0 }}
echo "  MTU: {{ .MTU }}"
{{- end }}
echo "============================================================"
echo ""
echo "WireGuard status:"
wg show "$WG_IFACE"
echo ""
{{ if .HasBabel -}}
echo "Babel status:"
echo "  Check with: babeld -d 1"
echo ""
{{ end -}}
echo "Installation complete!"
echo "Note: If peers are not yet online, connections will establish once they come up."
`

// RenderInstallScript 
func RenderInstallScript(node *model.Node, hasBabel bool) (string, error) {
	config := InstallScriptConfig{
		NodeName:       node.Name,
		NodeRole:       node.Role,
		Platform:       node.Platform,
		OverlayIP:      node.OverlayIP,
		MTU:            node.MTU,
		HasBabel:       hasBabel,
		HasForward:     node.Capabilities.CanForward,
		WgConfName:     "wg0.conf",
		BabelConfName:  "babeld.conf",
		SysctlConfName: "99-overlay.conf",
	}

	if config.Platform == "" {
		config.Platform = "debian"
	}

	return renderTemplate("install.sh", installScriptTemplate, config)
}
