package renderer

import (
	"github.com/kunorikiku/yet-another-overlay-generator/internal/compiler"
	"github.com/kunorikiku/yet-another-overlay-generator/internal/model"
)

// InstallScriptConfig 安装脚本配置
type InstallScriptConfig struct {
	NodeName       string
	NodeRole       string
	Platform       string
	OverlayIP      string
	MTU            int
	HasBabel       bool
	HasForward     bool
	// per-peer 接口列表
	WgInterfaces   []WgIfaceInfo
	BabelConfName  string
	SysctlConfName string
}

// WgIfaceInfo 单个 WireGuard 接口信息
type WgIfaceInfo struct {
	Name     string // 接口名，如 wg-beta
	ConfName string // 配置文件名，如 wg-beta.conf
}

const installScriptTemplate = `#!/usr/bin/env bash
# Install script for node: {{ .NodeName }}
# Generated by Overlay Network Config Orchestrator
# Platform: {{ .Platform }}
# Role: {{ .NodeRole }}
# Architecture: per-peer WireGuard interfaces

set -euo pipefail

# ============================================================
# Phase 0: Cleanup Previous Installation
# ============================================================

echo "=== Phase 0: Cleanup Previous Installation ==="

# Stop all WireGuard interfaces managed by this overlay
{{ range .WgInterfaces -}}
if command -v wg >/dev/null 2>&1 && wg show "{{ .Name }}" > /dev/null 2>&1; then
    echo "  Stopping WireGuard interface: {{ .Name }}..."
    wg-quick down "{{ .Name }}" 2>/dev/null || true
fi
if systemctl is-enabled "wg-quick@{{ .Name }}" >/dev/null 2>&1; then
    systemctl disable "wg-quick@{{ .Name }}" 2>/dev/null || true
fi
if [ -f "/etc/wireguard/{{ .ConfName }}" ]; then
    rm -f "/etc/wireguard/{{ .ConfName }}"
    echo "  Removed old config: /etc/wireguard/{{ .ConfName }}"
fi
{{ end -}}

# Also clean up legacy single-interface config if present
if command -v wg >/dev/null 2>&1 && wg show "wg0" > /dev/null 2>&1; then
    echo "  Stopping legacy WireGuard interface: wg0..."
    wg-quick down "wg0" 2>/dev/null || true
fi
if [ -f "/etc/wireguard/wg0.conf" ]; then
    rm -f "/etc/wireguard/wg0.conf"
    echo "  Removed legacy config: /etc/wireguard/wg0.conf"
fi

{{ if .HasBabel -}}
# Stop Babel if running
if systemctl is-active babeld >/dev/null 2>&1; then
    echo "  Stopping Babel daemon..."
    systemctl stop babeld 2>/dev/null || true
fi
if systemctl is-enabled babeld >/dev/null 2>&1; then
    systemctl disable babeld 2>/dev/null || true
fi
for _bcf in "/etc/babel/{{ .BabelConfName }}" "/etc/{{ .BabelConfName }}"; do
    if [ -f "$_bcf" ]; then
        rm -f "$_bcf"
        echo "  Removed old Babel config: $_bcf"
    fi
done
{{ end -}}

if [ -f "/etc/sysctl.d/{{ .SysctlConfName }}" ]; then
    rm -f "/etc/sysctl.d/{{ .SysctlConfName }}"
    echo "  Removed old sysctl config"
fi

echo "Phase 0 complete."

# ============================================================
# Phase 1: Environment Preparation
# ============================================================

echo "=== Phase 1: Environment Preparation ==="

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Verify checksums if available
if [ -f "$SCRIPT_DIR/checksums.sha256" ]; then
    echo "Verifying file integrity..."
    cd "$SCRIPT_DIR"
    if ! sha256sum --status -c checksums.sha256; then
        echo "ERROR: Checksum validation failed!" >&2
        exit 1
    fi
    echo "Checksum validation passed."
    cd - >/dev/null
fi

# Check root
if [ "$(id -u)" -ne 0 ]; then
    echo "ERROR: This script must be run as root" >&2
    exit 1
fi

# Detect OS
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS_ID="$ID"
    OS_VERSION="$VERSION_ID"
    echo "Detected OS: $OS_ID $OS_VERSION"
else
    echo "ERROR: Cannot detect OS" >&2
    exit 1
fi

# Install dependencies
echo "Installing dependencies..."

if [ "$OS_ID" = "debian" ] || [ "$OS_ID" = "ubuntu" ]; then
    export DEBIAN_FRONTEND=noninteractive

    ensure_pkg() {
        local pkg="$1"
        if dpkg -s "$pkg" >/dev/null 2>&1; then
            echo "  - $pkg already installed"
            return 0
        fi
        echo "  - installing $pkg"
        apt-get install -y -qq "$pkg"
    }

    apt-get update -qq
    ensure_pkg iproute2
    ensure_pkg ca-certificates
    ensure_pkg coreutils
    ensure_pkg wireguard
    ensure_pkg wireguard-tools
{{ if .HasBabel -}}
    ensure_pkg babeld
{{ end -}}
else
    echo "Checking dependencies on $OS_ID..."
    missing_bins=""
    require_bin() {
        if ! command -v "$1" >/dev/null 2>&1; then
            missing_bins="$missing_bins $1"
        fi
    }
    require_bin wg
    require_bin wg-quick
    require_bin ip
{{ if .HasBabel -}}
    require_bin babeld
{{ end -}}
    if [ -n "$missing_bins" ]; then
        echo "ERROR: Missing:$missing_bins" >&2
        exit 1
    fi
fi

mkdir -p /etc/wireguard
{{ if .HasBabel -}}
mkdir -p /etc/babel
{{ end -}}

# Create dummy0 interface for stable overlay address
if ! ip link show dummy0 >/dev/null 2>&1; then
    echo "Creating dummy0 interface for overlay address..."
    ip link add dummy0 type dummy
fi
ip addr flush dev dummy0 2>/dev/null || true
ip addr add {{ .OverlayIP }}/32 dev dummy0
ip link set dummy0 up
echo "  Overlay address {{ .OverlayIP }}/32 assigned to dummy0"

# Make dummy0 persistent across reboots
cat > /etc/systemd/system/overlay-dummy.service << 'DUMMY_SVC'
[Unit]
Description=Overlay dummy interface
Before=network.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/sbin/ip link add dummy0 type dummy
ExecStart=/sbin/ip addr add {{ .OverlayIP }}/32 dev dummy0
ExecStart=/sbin/ip link set dummy0 up
ExecStop=/sbin/ip link del dummy0

[Install]
WantedBy=multi-user.target
DUMMY_SVC
systemctl daemon-reload
systemctl enable overlay-dummy.service 2>/dev/null || true

echo "Phase 1 complete."

# ============================================================
# Phase 2: Deploy Configuration
# ============================================================

echo "=== Phase 2: Deploy Configuration ==="

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Deploy per-peer WireGuard configurations
echo "Deploying WireGuard per-peer configurations..."
{{ range .WgInterfaces -}}
cp "$SCRIPT_DIR/wireguard/{{ .ConfName }}" /etc/wireguard/{{ .ConfName }}
chmod 600 /etc/wireguard/{{ .ConfName }}
echo "  Deployed: /etc/wireguard/{{ .ConfName }}"
{{ end -}}

{{ if .HasBabel -}}
# Deploy Babel configuration
echo "Deploying Babel configuration..."
cp "$SCRIPT_DIR/babel/{{ .BabelConfName }}" /etc/babel/{{ .BabelConfName }}
echo "  Deployed: /etc/babel/{{ .BabelConfName }}"
{{ end -}}

# Deploy sysctl configuration
cp "$SCRIPT_DIR/sysctl/{{ .SysctlConfName }}" /etc/sysctl.d/{{ .SysctlConfName }}
echo "  Deployed: /etc/sysctl.d/{{ .SysctlConfName }}"

echo "Phase 2 complete."

# ============================================================
# Phase 3: Activate and Verify
# ============================================================

echo "=== Phase 3: Activate and Verify ==="

# Apply sysctl
echo "Applying sysctl settings..."
sysctl --system > /dev/null 2>&1
{{ if .HasForward -}}
echo "  IPv4 forwarding: $(cat /proc/sys/net/ipv4/ip_forward)"
{{ end -}}

# Start all WireGuard per-peer interfaces
echo "Starting WireGuard interfaces..."
{{ range .WgInterfaces -}}
echo "  Starting {{ .Name }}..."
wg-quick up "{{ .Name }}"
systemctl enable wg-quick@"{{ .Name }}" 2>/dev/null || true
{{ end -}}

{{ if .HasBabel -}}
# Configure babeld systemd service
echo "Configuring babeld systemd service..."
mkdir -p /etc/systemd/system/babeld.service.d
cat > /etc/systemd/system/babeld.service.d/override.conf << 'BABEL_OVERRIDE'
[Unit]
Description=Babel routing daemon (overlay)
After=network.target{{ range .WgInterfaces }} wg-quick@{{ .Name }}.service{{ end }}
Wants={{ range $i, $iface := .WgInterfaces }}{{ if $i }} {{ end }}wg-quick@{{ $iface.Name }}.service{{ end }}

[Service]
Type=simple
ExecStart=
ExecStart=/usr/sbin/babeld -c /etc/babel/{{ .BabelConfName }}
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
BABEL_OVERRIDE
systemctl daemon-reload
systemctl restart babeld
systemctl enable babeld
echo "  Babel daemon started"
{{ end -}}

# Show status
echo ""
echo "============================================================"
echo "  Node: {{ .NodeName }}"
echo "  Overlay IP: {{ .OverlayIP }} (on dummy0)"
echo "  Role: {{ .NodeRole }}"
echo "  WireGuard interfaces: {{ range .WgInterfaces }}{{ .Name }} {{ end }}"
{{- if gt .MTU 0 }}
echo "  MTU: {{ .MTU }}"
{{- end }}
echo "============================================================"
echo ""
echo "WireGuard status:"
{{ range .WgInterfaces -}}
echo "--- {{ .Name }} ---"
wg show "{{ .Name }}" 2>/dev/null || echo "  (not yet connected)"
{{ end -}}
echo ""
{{ if .HasBabel -}}
echo "Babel status:"
echo "  Check with: nc ::1 33123 (then type 'dump')"
echo ""
{{ end -}}
echo "Installation complete!"
echo "Note: If peers are not yet online, connections will establish once they come up."
`

// RenderInstallScript 渲染安装脚本
func RenderInstallScript(node *model.Node, peers []compiler.PeerInfo, hasBabel bool) (string, error) {
	// 构建 WireGuard 接口列表
	var wgIfaces []WgIfaceInfo
	for _, p := range peers {
		wgIfaces = append(wgIfaces, WgIfaceInfo{
			Name:     p.InterfaceName,
			ConfName: p.InterfaceName + ".conf",
		})
	}

	config := InstallScriptConfig{
		NodeName:       node.Name,
		NodeRole:       node.Role,
		Platform:       node.Platform,
		OverlayIP:      node.OverlayIP,
		MTU:            node.MTU,
		HasBabel:       hasBabel,
		HasForward:     node.Capabilities.CanForward,
		WgInterfaces:   wgIfaces,
		BabelConfName:  "babeld.conf",
		SysctlConfName: "99-overlay.conf",
	}

	if config.Platform == "" {
		config.Platform = "debian"
	}

	return renderTemplate("install.sh", installScriptTemplate, config)
}
