package renderer

import (
	"sort"

	"github.com/kunorikiku/yet-another-overlay-generator/internal/compiler"
	"github.com/kunorikiku/yet-another-overlay-generator/internal/model"
)

// InstallScriptConfig 安装脚本配置
type InstallScriptConfig struct {
	NodeName string // 原始节点名，仅用于脚本头部注释（注释在 bash 中不会被求值）
	// NodeNameQuoted 是经 bashSingleQuote 转义后的节点名，作为单引号 shell token
	// 拼接进 root 身份执行的 echo 行。模板里凡是把节点名放入 echo 的位置都必须用
	// 这个字段而非 NodeName，否则形如 x$(touch /tmp/pwned) 的节点名会在 root 下
	// 触发命令替换（审计 T4 / D15）。把转义放在数据装填阶段，使模板保持可读。
	NodeNameQuoted string
	NodeRole       string
	Platform       string
	OverlayIP      string
	DomainCIDR     string // domain CIDR for source routing rule
	// TransitCIDRs 是该节点所属域解析后的 transit 地址池（domain.TransitCIDR，
	// 留空时回退默认 10.10.0.0/24）。SNAT 源地址修复必须按这些池下发规则：把落在
	// transit 池里的源地址改写为 overlay IP。硬编码 10.10.0.0/24 会让任何自定义
	// transit_cidr 的节点静默失效——包到达后源地址仍是未改写的 transit 地址，
	// 路由不可达（审计 D38/D39）。模板对每个 CIDR各下发一条规则；为空时由
	// RenderInstallScript 兜底为默认池，保证旧调用方行为不变。
	TransitCIDRs []string
	MTU          int
	HasBabel     bool
	HasForward   bool
	// HasMimic 表示本节点有至少一条 transport=="tcp" 的链路，需要在安装/卸载脚本里
	// 装配 mimic（eBPF UDP→伪 TCP 整形）。见 docs/spec/artifacts/mimic.md。
	HasMimic bool
	// MimicPorts 是本节点所有 mimic 接口的监听端口（已排序、去重）。mimic 附着在
	// egress NIC 上（运行时探测），每个监听端口下发一条 filter 行
	// （local=<egress_ip>:<port>）。YAOG 只提供端口集合；egress if/ip 由 bash 在
	// 安装时探测——见 docs/spec/artifacts/mimic.md「Attaches to the egress NIC」。
	MimicPorts []int
	// MimicXDPMode 是写入 mimic 配置的 xdp_mode（"skb" 或 "native"，已归一，绝不为空）。
	// 默认 "skb"（通用 XDP，兼容不支持 native 的 VPS 网卡）；节点显式设 "native" 时为 "native"。
	MimicXDPMode string
	// per-peer 接口列表
	WgInterfaces   []WgIfaceInfo
	BabelConfName  string
	SysctlConfName string
	// SigningPubkeyPEM is the Ed25519 verifying public key (PKIX/PKCS8 PEM) pinned into the
	// install script when bundle signing is enabled. The export path sets it (via
	// RenderInstallScriptSigned) only when the operator configured a signing key; otherwise it
	// is empty and the template emits no signature-verification block, so an unsigned bundle's
	// install.sh is byte-identical to the pre-signing output (opt-in back-compat). When non-empty
	// the template, before the existing sha256sum -c, verifies bundle.sig (raw Ed25519, base64)
	// over checksums.sha256 against this pinned key using openssl, failing clearly if bundle.sig
	// is present but openssl/Ed25519 is unavailable. See docs/spec/controller/signing.md.
	SigningPubkeyPEM string
	// SplicePlaceholder enables the AgentHeld custody splice block in Phase 2: after each
	// per-peer conf is copied to /etc/wireguard, the copied conf's placeholder PrivateKey line is
	// replaced in place with the node's locally-held private key read from /etc/wireguard/agent.key.
	// False (the default) emits no splice block, so the air-gap install.sh stays byte-identical to
	// the pre-splice output. The bundled confs are never touched, so the signed bundle stays pristine
	// and re-runs remain idempotent. See docs/spec/controller/key-custody.md.
	SplicePlaceholder bool
	// SplicePlaceholderToken is the exact sentinel that appears as the value of the [Interface]
	// PrivateKey line under AgentHeld custody (PrivateKeyPlaceholder, e.g. "PRIVATEKEY_PLACEHOLDER").
	// The splice block matches the literal line 'PrivateKey = <token>' and replaces only that line.
	// Only meaningful when SplicePlaceholder is true.
	SplicePlaceholderToken string
}

// WgIfaceInfo 单个 WireGuard 接口信息
type WgIfaceInfo struct {
	Name     string // 接口名，如 wg-beta
	ConfName string // 配置文件名，如 wg-beta.conf
}

const installScriptTemplate = `#!/usr/bin/env bash
# Install script for node: {{ .NodeName }}
# Generated by Overlay Network Config Orchestrator
# Platform: {{ .Platform }}
# Role: {{ .NodeRole }}
# Architecture: per-peer WireGuard interfaces
#
# Usage:
#   sudo bash install.sh              # Install / upgrade overlay
#   sudo bash install.sh --uninstall  # Completely remove overlay

set -euo pipefail

UNINSTALL=0
for arg in "$@"; do
    case "$arg" in
        --uninstall|-u) UNINSTALL=1 ;;
    esac
done

# ============================================================
# Uninstall All
# ============================================================

if [ "$UNINSTALL" -eq 1 ]; then
    # Check root
    if [ "$(id -u)" -ne 0 ]; then
        echo "ERROR: This script must be run as root" >&2
        exit 1
    fi

    echo "=== Uninstalling overlay from node: "{{ .NodeNameQuoted }}" ==="

{{ if .HasMimic -}}
    # Tear down mimic TCP-shaping transport (docs/spec/artifacts/mimic.md): stop/disable the
    # mimic@<egress> unit and remove its config. Re-detect the egress NIC the same way the
    # installer did; tolerate absence (mimic may already be gone / no default route).
    _mimic_egress_if="$(ip route show default 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="dev"){print $(i+1); exit}}')"
    if [ -n "$_mimic_egress_if" ]; then
        echo "  Stopping mimic@$_mimic_egress_if..."
        systemctl disable --now "mimic@$_mimic_egress_if" 2>/dev/null || true
        rm -f "/etc/mimic/$_mimic_egress_if.conf"
    fi
{{ end -}}

    # Stop and disable all managed WireGuard interfaces
    {{ range .WgInterfaces -}}
    if command -v wg >/dev/null 2>&1 && wg show "{{ .Name }}" > /dev/null 2>&1; then
        echo "  Stopping WireGuard interface: {{ .Name }}..."
        wg-quick down "{{ .Name }}" 2>/dev/null || true
    fi
    if systemctl is-enabled "wg-quick@{{ .Name }}" >/dev/null 2>&1; then
        systemctl disable "wg-quick@{{ .Name }}" 2>/dev/null || true
    fi
    rm -f "/etc/wireguard/{{ .ConfName }}"
    {{ end -}}

    # Stop and disable ALL remaining WireGuard interfaces
    if command -v wg >/dev/null 2>&1; then
        for _iface in $(wg show interfaces 2>/dev/null); do
            echo "  Stopping WireGuard interface: $_iface..."
            wg-quick down "$_iface" 2>/dev/null || true
            systemctl disable "wg-quick@$_iface" 2>/dev/null || true
        done
    fi
    rm -f /etc/wireguard/*.conf

{{ if .HasBabel -}}
    # Stop and disable Babel
    if systemctl is-active babeld >/dev/null 2>&1; then
        echo "  Stopping Babel daemon..."
        systemctl stop babeld 2>/dev/null || true
    fi
    if systemctl is-enabled babeld >/dev/null 2>&1; then
        systemctl disable babeld 2>/dev/null || true
    fi
    rm -f "/etc/babel/{{ .BabelConfName }}" "/etc/{{ .BabelConfName }}"
    rm -rf /etc/systemd/system/babeld.service.d
{{ end -}}

    # Remove sysctl config
    rm -f "/etc/sysctl.d/{{ .SysctlConfName }}"
    sysctl --system > /dev/null 2>&1

    # Remove overlay SNAT rule and service
    #
    # D52: same as _overlay_snat_cleanup - delete each rule whole, matched by wg interface + transit
    # source pool and ignoring --to-source, so uninstall fully clears even stale rules left by a prior overlay IP change.
    if command -v nft >/dev/null 2>&1; then
        nft delete table inet overlay-snat 2>/dev/null || true
    fi
    if command -v iptables >/dev/null 2>&1 && command -v iptables-save >/dev/null 2>&1; then
        {{ range .TransitCIDRs -}}
        # Chained grep -F deletes each matching rule whole, order-independent; see Phase 1's _overlay_snat_cleanup.
        # grep returns 1 on no match; with set -o pipefail that makes the pipe non-zero and aborts under set -e, so || true guards it.
        iptables-save -t nat 2>/dev/null \
            | grep -E '^-A POSTROUTING ' \
            | grep -F -- '-j SNAT' \
            | grep -F -- '-o wg-+' \
            | grep -F -- '-s {{ . }}' \
            | while IFS= read -r _snat_rule; do
                _snat_del="${_snat_rule/#-A/-D}"
                # shellcheck disable=SC2086
                iptables -t nat $_snat_del 2>/dev/null || true
            done || true
        {{ end -}}
    fi
    if systemctl is-enabled overlay-snat.service >/dev/null 2>&1; then
        systemctl disable overlay-snat.service 2>/dev/null || true
    fi
    rm -f /etc/systemd/system/overlay-snat.service

    # Remove dummy0 overlay interface and its systemd service
    if ip link show dummy0 >/dev/null 2>&1; then
        echo "  Removing dummy0 interface..."
        ip link del dummy0 2>/dev/null || true
    fi
    if systemctl is-enabled overlay-dummy.service >/dev/null 2>&1; then
        systemctl disable overlay-dummy.service 2>/dev/null || true
    fi
    rm -f /etc/systemd/system/overlay-dummy.service
    systemctl daemon-reload

    echo ""
    echo "============================================================"
    echo "  Overlay completely removed from node: "{{ .NodeNameQuoted }}
    echo "============================================================"
    exit 0
fi

# ============================================================
# Phase 0: Cleanup Previous Installation
# ============================================================

echo "=== Phase 0: Cleanup Previous Installation ==="

# Stop all WireGuard interfaces managed by this overlay
{{ range .WgInterfaces -}}
if command -v wg >/dev/null 2>&1 && wg show "{{ .Name }}" > /dev/null 2>&1; then
    echo "  Stopping WireGuard interface: {{ .Name }}..."
    wg-quick down "{{ .Name }}" 2>/dev/null || true
fi
if systemctl is-enabled "wg-quick@{{ .Name }}" >/dev/null 2>&1; then
    systemctl disable "wg-quick@{{ .Name }}" 2>/dev/null || true
fi
if [ -f "/etc/wireguard/{{ .ConfName }}" ]; then
    rm -f "/etc/wireguard/{{ .ConfName }}"
    echo "  Removed old config: /etc/wireguard/{{ .ConfName }}"
fi
{{ end -}}

# Clean up ALL legacy/stale WireGuard interfaces and configs
# This catches wg0, wg1, wg-overlay, or any other leftover profiles
if command -v wg >/dev/null 2>&1; then
    for _legacy_iface in $(wg show interfaces 2>/dev/null); do
        # Skip interfaces managed by this overlay (already handled above)
        _is_managed=false
        {{ range .WgInterfaces -}}
        [ "$_legacy_iface" = "{{ .Name }}" ] && _is_managed=true
        {{ end -}}
        if [ "$_is_managed" = "false" ]; then
            echo "  Stopping legacy WireGuard interface: $_legacy_iface..."
            wg-quick down "$_legacy_iface" 2>/dev/null || true
            if systemctl is-enabled "wg-quick@$_legacy_iface" >/dev/null 2>&1; then
                systemctl disable "wg-quick@$_legacy_iface" 2>/dev/null || true
            fi
        fi
    done
fi
# Remove any leftover WireGuard config files not managed by this overlay
for _legacy_conf in /etc/wireguard/*.conf; do
    [ -f "$_legacy_conf" ] || continue
    _legacy_name="$(basename "$_legacy_conf")"
    _is_managed=false
    {{ range .WgInterfaces -}}
    [ "$_legacy_name" = "{{ .ConfName }}" ] && _is_managed=true
    {{ end -}}
    if [ "$_is_managed" = "false" ]; then
        rm -f "$_legacy_conf"
        echo "  Removed legacy config: $_legacy_conf"
    fi
done

{{ if .HasBabel -}}
# Stop Babel if running
if systemctl is-active babeld >/dev/null 2>&1; then
    echo "  Stopping Babel daemon..."
    systemctl stop babeld 2>/dev/null || true
fi
if systemctl is-enabled babeld >/dev/null 2>&1; then
    systemctl disable babeld 2>/dev/null || true
fi
for _bcf in "/etc/babel/{{ .BabelConfName }}" "/etc/{{ .BabelConfName }}"; do
    if [ -f "$_bcf" ]; then
        rm -f "$_bcf"
        echo "  Removed old Babel config: $_bcf"
    fi
done
{{ end -}}

if [ -f "/etc/sysctl.d/{{ .SysctlConfName }}" ]; then
    rm -f "/etc/sysctl.d/{{ .SysctlConfName }}"
    echo "  Removed old sysctl config"
fi

echo "Phase 0 complete."

# ============================================================
# Phase 1: Environment Preparation
# ============================================================

echo "=== Phase 1: Environment Preparation ==="

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

{{ if .SigningPubkeyPEM -}}
# Verify the bundle's Ed25519 signature BEFORE the checksum check (docs/spec/controller/signing.md).
# bundle.sig is base64(raw 64-byte Ed25519 signature) over the exact bytes of checksums.sha256
# (the canonical bundle digest). The verifying public key is pinned below at generation time, so a
# tampered checksums.sha256 (even with matching file hashes) is rejected before any root action.
if [ -f "$SCRIPT_DIR/bundle.sig" ]; then
    echo "Verifying bundle signature..."
    if ! command -v openssl >/dev/null 2>&1; then
        # bundle.sig is present but we cannot verify it: fail clearly, never silently skip.
        echo "ERROR: bundle.sig present but openssl is not installed; cannot verify signature" >&2
        exit 1
    fi
    # Write the pinned verifying public key to a temp file for openssl pkeyutl -pubin.
    _sig_pubkey="$(mktemp)"
    _sig_raw="$(mktemp)"
    cleanup_sig() {
        rm -f "$_sig_pubkey" "$_sig_raw"
    }
    trap cleanup_sig EXIT
    cat > "$_sig_pubkey" << 'YAOG_SIGNING_PUBKEY_PEM'
{{ .SigningPubkeyPEM }}
YAOG_SIGNING_PUBKEY_PEM
    # Decode base64 signature to raw bytes for openssl -rawin verification.
    if ! base64 -d "$SCRIPT_DIR/bundle.sig" > "$_sig_raw" 2>/dev/null; then
        echo "ERROR: failed to decode bundle.sig (not valid base64)" >&2
        exit 1
    fi
    # Ed25519 is a one-shot (raw) signature: -rawin feeds the message directly, no pre-hash.
    # openssl without Ed25519 support exits nonzero here, satisfying the fail-clear requirement.
    if ! openssl pkeyutl -verify -pubin -inkey "$_sig_pubkey" -rawin -sigfile "$_sig_raw" -in "$SCRIPT_DIR/checksums.sha256" >/dev/null 2>&1; then
        echo "ERROR: bundle signature verification failed (openssl missing Ed25519 support or signature invalid)" >&2
        exit 1
    fi
    echo "Bundle signature verification passed."
    cleanup_sig
    trap - EXIT
else
    # This install.sh was rendered with signing enabled, so bundle.sig is MANDATORY: a missing
    # signature is signature-stripping tamper, not an unsigned bundle. We KNOW the bundle was
    # signed at generation time (the verifying key is pinned above), so refuse to proceed rather
    # than fall through to the bare checksum check an attacker could satisfy with rewritten files.
    echo "ERROR: bundle was signed at generation but bundle.sig is missing; refusing to proceed (possible signature-stripping tamper)" >&2
    exit 1
fi

{{ end -}}
# Verify checksums if available
if [ -f "$SCRIPT_DIR/checksums.sha256" ]; then
    echo "Verifying file integrity..."
    cd "$SCRIPT_DIR"
    if ! sha256sum --status -c checksums.sha256; then
        echo "ERROR: Checksum validation failed!" >&2
        exit 1
    fi
    echo "Checksum validation passed."
    cd - >/dev/null
fi

# Check root
if [ "$(id -u)" -ne 0 ]; then
    echo "ERROR: This script must be run as root" >&2
    exit 1
fi

# Detect OS
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS_ID="$ID"
    OS_VERSION="$VERSION_ID"
    echo "Detected OS: $OS_ID $OS_VERSION"
else
    echo "ERROR: Cannot detect OS" >&2
    exit 1
fi

# Install dependencies (cross-distro, idempotent)
#
# This runs on EVERY controller apply (the daemon re-runs install.sh per generation) and on a
# manual air-gap run, so it is a fast no-op once the tools exist: each MISSING command is mapped
# to a package and installed via the detected manager. Supported: apt / dnf / yum / zypper /
# pacman / apk. Package names match across managers except iproute2 -> iproute on dnf/yum/zypper.
# An unknown manager with tools still missing fails with an explicit list (no confusing mid-run error).
echo "Installing dependencies..."

YAOG_PM=""
for _c in apt-get dnf yum zypper pacman apk; do
    if command -v "$_c" >/dev/null 2>&1; then YAOG_PM="$_c"; break; fi
done

_pm_pkg() { # map a generic package name to this manager's concrete name
    case "$1:$YAOG_PM" in
        iproute2:dnf|iproute2:yum|iproute2:zypper) echo iproute ;;
        *) echo "$1" ;;
    esac
}

_PM_REFRESHED=0
_pm_install() {
    local _pkg; _pkg="$(_pm_pkg "$1")"
    if [ "$_PM_REFRESHED" -eq 0 ]; then
        case "$YAOG_PM" in
            apt-get) apt-get update -qq || true ;;
            apk)     apk update >/dev/null 2>&1 || true ;;
        esac
        _PM_REFRESHED=1
    fi
    case "$YAOG_PM" in
        apt-get) DEBIAN_FRONTEND=noninteractive apt-get install -y -qq "$_pkg" ;;
        dnf)     dnf install -y "$_pkg" ;;
        yum)     yum install -y "$_pkg" ;;
        zypper)  zypper --non-interactive install "$_pkg" ;;
        pacman)  pacman -Sy --noconfirm "$_pkg" ;;
        apk)     apk add --no-progress "$_pkg" ;;
        *)       return 1 ;;
    esac
}

YAOG_MISSING=""
ensure_cmd() { # ensure_cmd <command> <generic-package>: install only if the command is absent
    command -v "$1" >/dev/null 2>&1 && return 0
    if [ -n "$YAOG_PM" ]; then
        echo "  - installing $2 (provides '$1')"
        _pm_install "$2" || true
    fi
    command -v "$1" >/dev/null 2>&1 || YAOG_MISSING="$YAOG_MISSING $1"
}

ensure_cmd wg       wireguard-tools
ensure_cmd wg-quick wireguard-tools
ensure_cmd ip       iproute2
ensure_cmd openssl  openssl
# SNAT uses nft when present, else iptables (+iptables-save, same package) — ensure one exists.
if ! command -v nft >/dev/null 2>&1 && ! command -v iptables >/dev/null 2>&1; then
    ensure_cmd iptables iptables
fi
{{ if .HasBabel -}}
ensure_cmd babeld babeld
{{ end -}}
{{ if .HasMimic -}}
# mimic TCP-shaping transport (docs/spec/artifacts/mimic.md): a link uses transport="tcp".
# YAOG ships no mimic binary — install it from the distro / AUR.
ensure_cmd mimic mimic
# Kernel/eBPF sanity: mimic is an eBPF (TC/XDP) program; warn early if BPF looks absent.
if [ ! -d /sys/fs/bpf ] && ! grep -qw bpf /proc/filesystems 2>/dev/null; then
    echo "WARNING: eBPF/BPF filesystem not detected; mimic requires kernel eBPF support" >&2
fi
{{ end -}}

if [ -n "$YAOG_MISSING" ]; then
    echo "ERROR: missing required tools:$YAOG_MISSING" >&2
    echo "  No supported package manager installed them automatically. Install the equivalents of" >&2
    echo "  wireguard-tools (wg, wg-quick), iproute2 (ip), openssl, iptables or nftables{{ if .HasBabel }}, babeld{{ end }}{{ if .HasMimic }}, mimic{{ end }}, then re-run." >&2
    exit 1
fi

# WireGuard kernel module: built into Linux >= 5.6; load it (best-effort) on older kernels.
# If it is genuinely unavailable, wg-quick below surfaces the real error per interface.
modprobe wireguard 2>/dev/null || true

mkdir -p /etc/wireguard
{{ if .HasBabel -}}
mkdir -p /etc/babel
{{ end -}}

# Create dummy0 interface for stable overlay address
if ! ip link show dummy0 >/dev/null 2>&1; then
    echo "Creating dummy0 interface for overlay address..."
    ip link add dummy0 type dummy
fi
ip addr flush dev dummy0 2>/dev/null || true
ip addr add {{ .OverlayIP }}/32 dev dummy0
ip link set dummy0 up
echo "  Overlay address {{ .OverlayIP }}/32 assigned to dummy0"

# Make dummy0 persistent across reboots
cat > /etc/systemd/system/overlay-dummy.service << 'DUMMY_SVC'
[Unit]
Description=Overlay dummy interface
Before=network.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/sbin/ip link add dummy0 type dummy
ExecStart=/sbin/ip addr add {{ .OverlayIP }}/32 dev dummy0
ExecStart=/sbin/ip link set dummy0 up
ExecStop=/sbin/ip link del dummy0

[Install]
WantedBy=multi-user.target
DUMMY_SVC
systemctl daemon-reload
systemctl enable overlay-dummy.service 2>/dev/null || true

# Fix source address selection for overlay traffic
# Without this, packets to overlay IPs use the transit IP (10.10.0.x) as source
# instead of the overlay IP, causing silent failures for plain "ping <overlay_ip>"
echo "Configuring overlay source address fix..."

# Remove any previous overlay SNAT rules
#
# D52: we cannot delete by an exact rule (with --to-source <current overlay IP>): after an overlay IP change a
# reinstall would leave the old --to-source rule in POSTROUTING, wrongly source-rewriting packets to the old address.
# Instead: parse iptables-save and delete EVERY POSTROUTING SNAT rule matching the wg interface + transit source
# pool, whole, regardless of its --to-source. The nft path drops the whole table and has no such problem, so it is left as-is.
_overlay_snat_cleanup() {
    if command -v nft >/dev/null 2>&1; then
        nft delete table inet overlay-snat 2>/dev/null || true
    fi
    if command -v iptables >/dev/null 2>&1 && command -v iptables-save >/dev/null 2>&1; then
        {{ range .TransitCIDRs -}}
        # Delete rule by rule: in the iptables-save output, every POSTROUTING rule whose out interface is wg-+, source is {{ . }},
        # and action is SNAT is turned into a -D delete using its full parameters (ignoring the specific --to-source value).
        # Use chained grep -F rather than a single order-assuming regex: iptables-save normalizes parameter order
        # (usually -s before -o), so fixed-string matching is order-independent and needs no escaping of the . and / in the CIDR.
        # grep returns 1 on no match; with set -o pipefail the whole pipe returns non-zero, and under set -e
        # that would abort the script. The || true here swallows the normal "no old rule to delete" case.
        iptables-save -t nat 2>/dev/null \
            | grep -E '^-A POSTROUTING ' \
            | grep -F -- '-j SNAT' \
            | grep -F -- '-o wg-+' \
            | grep -F -- '-s {{ . }}' \
            | while IFS= read -r _snat_rule; do
                _snat_del="${_snat_rule/#-A/-D}"
                # shellcheck disable=SC2086
                iptables -t nat $_snat_del 2>/dev/null || true
            done || true
        {{ end -}}
    fi
}
_overlay_snat_cleanup

# Add SNAT rule: rewrite transit source IPs to overlay IP on WG interfaces
# Use nftables if available, fall back to iptables
if command -v nft >/dev/null 2>&1; then
    nft -f - <<'NFT_EOF'
table inet overlay-snat {
    chain postrouting {
        type nat hook postrouting priority srcnat; policy accept;
        {{ range .TransitCIDRs -}}
        oifname "wg-*" ip saddr {{ . }} snat to {{ $.OverlayIP }}
        {{ end -}}
    }
}
NFT_EOF
    {{ range .TransitCIDRs -}}
    echo "  SNAT (nftables): transit {{ . }} → {{ $.OverlayIP }} on wg-* interfaces"
    {{ end -}}
elif command -v iptables >/dev/null 2>&1; then
    {{ range .TransitCIDRs -}}
    iptables -t nat -C POSTROUTING -o "wg-+" -s {{ . }} -j SNAT --to-source {{ $.OverlayIP }} 2>/dev/null || \
        iptables -t nat -A POSTROUTING -o "wg-+" -s {{ . }} -j SNAT --to-source {{ $.OverlayIP }}
    echo "  SNAT (iptables): transit {{ . }} → {{ $.OverlayIP }} on wg-* interfaces"
    {{ end -}}
fi

# Persist SNAT rule via systemd
cat > /etc/systemd/system/overlay-snat.service << 'SNAT_SVC'
[Unit]
Description=Overlay SNAT rule for source address fix
After=network.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/bin/bash -c 'if command -v nft >/dev/null 2>&1; then nft delete table inet overlay-snat 2>/dev/null || true; nft add table inet overlay-snat; nft add chain inet overlay-snat postrouting "{ type nat hook postrouting priority srcnat; policy accept; }"; {{ range .TransitCIDRs }}nft add rule inet overlay-snat postrouting oifname "wg-*" ip saddr {{ . }} snat to {{ $.OverlayIP }}; {{ end }}else {{ range .TransitCIDRs }}iptables -t nat -D POSTROUTING -o wg-+ -s {{ . }} -j SNAT --to-source {{ $.OverlayIP }} 2>/dev/null || true; iptables -t nat -A POSTROUTING -o wg-+ -s {{ . }} -j SNAT --to-source {{ $.OverlayIP }}; {{ end }}fi'
ExecStop=/bin/bash -c 'if command -v nft >/dev/null 2>&1; then nft delete table inet overlay-snat 2>/dev/null || true; else {{ range .TransitCIDRs }}iptables -t nat -D POSTROUTING -o wg-+ -s {{ . }} -j SNAT --to-source {{ $.OverlayIP }} 2>/dev/null || true; {{ end }}fi'

[Install]
WantedBy=multi-user.target
SNAT_SVC
systemctl daemon-reload
systemctl enable overlay-snat.service 2>/dev/null || true

echo "Phase 1 complete."

# ============================================================
# Phase 2: Deploy Configuration
# ============================================================

echo "=== Phase 2: Deploy Configuration ==="

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Deploy per-peer WireGuard configurations
echo "Deploying WireGuard per-peer configurations..."
{{ range .WgInterfaces -}}
cp "$SCRIPT_DIR/wireguard/{{ .ConfName }}" /etc/wireguard/{{ .ConfName }}
chmod 600 /etc/wireguard/{{ .ConfName }}
echo "  Deployed: /etc/wireguard/{{ .ConfName }}"
{{ if $.SplicePlaceholder -}}
# AgentHeld custody: splice the node's locally-held private key into the COPIED conf (never the
# bundle conf — the signed bundle stays pristine so re-runs keep passing sha256sum -c). This runs
# in Phase 2, AFTER the Phase-1 signature/checksum verify (over the pristine placeholder bundle) and
# BEFORE wg-quick up. Injection-safe: no sed/regex; the key is read once and the file rewritten line
# by line. Re-run safe: the preceding cp restores the placeholder conf, so each run re-splices the
# same stable key deterministically; the grep guard skips only a conf that carries no placeholder
# (e.g. an air-gap bundle, which never renders this block).
if grep -qxF 'PrivateKey = {{ $.SplicePlaceholderToken }}' "/etc/wireguard/{{ .ConfName }}"; then
    if [ ! -s /etc/wireguard/agent.key ]; then
        echo "ERROR: /etc/wireguard/{{ .ConfName }} expects an agent-held private key but /etc/wireguard/agent.key is missing or empty" >&2
        exit 1
    fi
    # Command substitution strips the trailing newline, yielding the bare base64 key.
    _agent_key="$(cat /etc/wireguard/agent.key)"
    _spliced="$(mktemp)"
    # The scratch file transiently holds the real private key; remove it on any exit.
    trap 'rm -f "$_spliced"' EXIT
    while IFS= read -r line || [ -n "$line" ]; do
        if [ "$line" = 'PrivateKey = {{ $.SplicePlaceholderToken }}' ]; then
            printf 'PrivateKey = %s\n' "$_agent_key" >> "$_spliced"
        else
            printf '%s\n' "$line" >> "$_spliced"
        fi
    done < "/etc/wireguard/{{ .ConfName }}"
    cat "$_spliced" > "/etc/wireguard/{{ .ConfName }}"
    rm -f "$_spliced"
    trap - EXIT
    chmod 600 /etc/wireguard/{{ .ConfName }}
    echo "  Spliced agent-held private key into /etc/wireguard/{{ .ConfName }}"
fi
{{ end -}}
{{ end -}}

{{ if .HasBabel -}}
# Deploy Babel configuration
echo "Deploying Babel configuration..."
cp "$SCRIPT_DIR/babel/{{ .BabelConfName }}" /etc/babel/{{ .BabelConfName }}
echo "  Deployed: /etc/babel/{{ .BabelConfName }}"
{{ end -}}

# Deploy sysctl configuration
cp "$SCRIPT_DIR/sysctl/{{ .SysctlConfName }}" /etc/sysctl.d/{{ .SysctlConfName }}
echo "  Deployed: /etc/sysctl.d/{{ .SysctlConfName }}"

echo "Phase 2 complete."

# ============================================================
# Phase 3: Activate and Verify
# ============================================================

echo "=== Phase 3: Activate and Verify ==="

# Apply sysctl
echo "Applying sysctl settings..."
sysctl --system > /dev/null 2>&1
{{ if .HasForward -}}
echo "  IPv4 forwarding: $(cat /proc/sys/net/ipv4/ip_forward)"
{{ end -}}

{{ if .HasMimic -}}
# Provision mimic TCP-shaping transport BEFORE bringing WireGuard up, so the shaping is in
# place when the tunnel handshakes (docs/spec/artifacts/mimic.md «Ordering»).
#
# mimic attaches to the EGRESS NIC (the default-route interface), NOT the wg interface; the
# egress if/ip are not known at compile time, so detect them here at runtime. YAOG only supplies
# the mimic listen-port set via the template.
echo "Provisioning mimic TCP-shaping transport..."
MIMIC_EGRESS_IF="$(ip route show default 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="dev"){print $(i+1); exit}}')"
MIMIC_EGRESS_IP="$(ip route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src"){print $(i+1); exit}}')"
if [ -z "$MIMIC_EGRESS_IF" ] || [ -z "$MIMIC_EGRESS_IP" ]; then
    echo "ERROR: could not detect egress interface/IP for mimic (no default route?)" >&2
    exit 1
fi
echo "  mimic egress: $MIMIC_EGRESS_IF ($MIMIC_EGRESS_IP)"
mkdir -p /etc/mimic
# One filter per mimic listen port on this node; all OR'ed by mimic. xdp_mode is operator-selectable
# per node (default skb for portability; native opt-in via Node.xdp_mode) — see mimic.md.
{
    {{ range .MimicPorts -}}
    echo "filter = local=${MIMIC_EGRESS_IP}:{{ . }}"
    {{ end -}}
    echo "xdp_mode = {{ .MimicXDPMode }}"
} > "/etc/mimic/${MIMIC_EGRESS_IF}.conf"
echo "  Wrote /etc/mimic/${MIMIC_EGRESS_IF}.conf"
# The distro mimic package ships mimic@<iface>.service (Requires=modprobe@mimic.service, so the
# kernel module auto-loads). Enable+start it on the egress NIC before WireGuard comes up.
systemctl enable --now "mimic@${MIMIC_EGRESS_IF}"
echo "  Started mimic@${MIMIC_EGRESS_IF}"
{{ end -}}

# Start all WireGuard per-peer interfaces
#
# D53: the script runs under set -euo pipefail. If one interface's wg-quick up failed without being tolerated,
# the whole script would abort before configuring babeld, leaving a "half-started" node (some tunnels up but the
# routing daemon unconfigured). So collect each interface's start failure (appended to FAILED_INTERFACES),
# warn on stderr and continue so babeld and later steps still run; print a failure summary at the end and
# exit non-zero if any failed (so the deploy tool still sees it), but only after the remaining steps have run.
# Note the set -e interaction: use the 'if ! wg-quick up ...; then' form, or the non-zero return would abort outright.
echo "Starting WireGuard interfaces..."
FAILED_INTERFACES=""
{{ range .WgInterfaces -}}
echo "  Starting {{ .Name }}..."
if ! wg-quick up "{{ .Name }}"; then
    echo "WARNING: failed to bring up WireGuard interface {{ .Name }}; continuing with remaining setup" >&2
    FAILED_INTERFACES="$FAILED_INTERFACES {{ .Name }}"
fi
systemctl enable wg-quick@"{{ .Name }}" 2>/dev/null || true
{{ end -}}

{{ if .HasBabel -}}
# Configure babeld systemd service
echo "Configuring babeld systemd service..."
mkdir -p /etc/systemd/system/babeld.service.d
cat > /etc/systemd/system/babeld.service.d/override.conf << 'BABEL_OVERRIDE'
[Unit]
Description=Babel routing daemon (overlay)
After=network.target{{ range .WgInterfaces }} wg-quick@{{ .Name }}.service{{ end }}
Wants={{ range $i, $iface := .WgInterfaces }}{{ if $i }} {{ end }}wg-quick@{{ $iface.Name }}.service{{ end }}

[Service]
Type=simple
ExecStart=
ExecStart=/usr/sbin/babeld -c /etc/babel/{{ .BabelConfName }}
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
BABEL_OVERRIDE
systemctl daemon-reload
systemctl restart babeld
systemctl enable babeld
echo "  Babel daemon started"
{{ end -}}

# Show status
echo ""
echo "============================================================"
echo "  Node: "{{ .NodeNameQuoted }}
echo "  Overlay IP: {{ .OverlayIP }} (on dummy0)"
echo "  Role: {{ .NodeRole }}"
echo "  WireGuard interfaces: {{ range .WgInterfaces }}{{ .Name }} {{ end }}"
{{- if gt .MTU 0 }}
echo "  MTU: {{ .MTU }}"
{{- end }}
echo "============================================================"
echo ""
echo "WireGuard status:"
{{ range .WgInterfaces -}}
echo "--- {{ .Name }} ---"
wg show "{{ .Name }}" 2>/dev/null || echo "  (not yet connected)"
{{ end -}}
echo ""
{{ if .HasBabel -}}
echo "Babel status:"
echo "  Check with: nc ::1 33123 (then type 'dump')"
echo ""
{{ end -}}
echo "Installation complete!"
echo "Note: If peers are not yet online, connections will establish once they come up."

# D53: summarize the WireGuard interface start results. If any failed to start, print the failure list and exit
# non-zero so the upstream deploy tool can detect it - but this exit happens after babeld config, status display,
# and the other remaining steps have all completed, so the node is never left in a "half-started" state.
if [ -n "$FAILED_INTERFACES" ]; then
    echo ""
    echo "WARNING: the following WireGuard interface(s) failed to start:$FAILED_INTERFACES" >&2
    echo "         the rest of the installation completed; re-run 'wg-quick up <iface>' to retry." >&2
    exit 1
fi
`

// defaultTransitCIDR 是 transit 地址池的默认值，与 allocateTransitPair 的回退一致。
const defaultTransitCIDR = "10.10.0.0/24"

// RenderInstallScript 渲染安装脚本。
//
// transitCIDRs 是该节点所属域解析后的 transit 地址池列表，用于参数化 SNAT 源地址
// 修复规则（审计 D38/D39）。调用方应传入 node 所属 domain 的 transit_cidr（留空时
// 回退默认 10.10.0.0/24）。该参数为可变参以保持对既有三参调用方的兼容：不传时
// 兜底为默认池，行为与历史一致。空字符串项会被忽略并以默认池补位，重复项去重，
// 以保证「每个 distinct CIDR 一条 SNAT 规则」。
func RenderInstallScript(node *model.Node, peers []compiler.PeerInfo, hasBabel bool, transitCIDRs ...string) (string, error) {
	config := buildInstallScriptConfig(node, peers, hasBabel, transitCIDRs)
	return renderTemplate("install.sh", installScriptTemplate, config)
}

// CustodySplice carries the AgentHeld custody-splice parameters into the *Signed renderers.
//
// When Enabled is true, the rendered install.sh gains a Phase-2 block that, after copying each conf
// to /etc/wireguard, replaces the placeholder PrivateKey line (value == Token) in the COPIED conf
// with the node's locally-held key from /etc/wireguard/agent.key. The zero value (Enabled:false)
// emits no splice block, so the air-gap install.sh stays byte-identical to the pre-splice output.
// See docs/spec/controller/key-custody.md.
type CustodySplice struct {
	// Enabled turns the custody-splice block on. False = no splice = byte-identical to today.
	Enabled bool
	// Token is the exact PrivateKey value to match for replacement (PrivateKeyPlaceholder).
	Token string
}

// RenderInstallScriptSigned renders the per-peer install script with bundle-signature verification
// enabled: the rendered install.sh, before its existing sha256sum -c, verifies bundle.sig over
// checksums.sha256 against the pinned signingPubkeyPEM (PKIX/PKCS8 PEM) using openssl.
//
// splice gates the AgentHeld custody-splice block (CustodySplice{} disables it, keeping output
// byte-identical to the pre-splice path). This is the entry point the export path calls only when an
// operator signing key is configured (YAOG_BUNDLE_SIGNING_KEY). When signingPubkeyPEM is empty, the
// output is byte-identical to RenderInstallScript (opt-in back-compat). All other parameters match
// RenderInstallScript. See docs/spec/controller/signing.md and docs/spec/controller/key-custody.md.
func RenderInstallScriptSigned(node *model.Node, peers []compiler.PeerInfo, hasBabel bool, signingPubkeyPEM string, splice CustodySplice, transitCIDRs ...string) (string, error) {
	config := buildInstallScriptConfig(node, peers, hasBabel, transitCIDRs)
	config.SigningPubkeyPEM = signingPubkeyPEM
	config.SplicePlaceholder = splice.Enabled
	config.SplicePlaceholderToken = splice.Token
	return renderTemplate("install.sh", installScriptTemplate, config)
}

// buildInstallScriptConfig assembles the per-peer InstallScriptConfig shared by the plain and
// signed renderers. SigningPubkeyPEM is left empty here; signed callers set it after.
func buildInstallScriptConfig(node *model.Node, peers []compiler.PeerInfo, hasBabel bool, transitCIDRs []string) InstallScriptConfig {
	// 构建 WireGuard 接口列表
	var wgIfaces []WgIfaceInfo
	for _, p := range peers {
		wgIfaces = append(wgIfaces, WgIfaceInfo{
			Name:     p.InterfaceName,
			ConfName: p.InterfaceName + ".conf",
		})
	}

	resolvedTransitCIDRs := resolveTransitCIDRs(transitCIDRs)

	// mimic 端口集合：扫描 peers 收集所有 mimic 接口（p.Mimic）的监听端口，去重并排序。
	// renderer 据此为该节点的 egress NIC 下发每端口一条 filter 行（docs/spec/artifacts/mimic.md）。
	mimicPorts := collectMimicPorts(peers)

	config := InstallScriptConfig{
		NodeName:       node.Name,
		NodeNameQuoted: bashSingleQuote(node.Name),
		NodeRole:       node.Role,
		Platform:       node.Platform,
		OverlayIP:      node.OverlayIP,
		TransitCIDRs:   resolvedTransitCIDRs,
		MTU:            node.MTU,
		HasBabel:       hasBabel,
		HasForward:     node.Capabilities.CanForward,
		HasMimic:       len(mimicPorts) > 0,
		MimicPorts:     mimicPorts,
		MimicXDPMode:   resolveMimicXDPMode(node.XDPMode),
		WgInterfaces:   wgIfaces,
		BabelConfName:  "babeld.conf",
		SysctlConfName: "99-overlay.conf",
	}

	if config.Platform == "" {
		config.Platform = "debian"
	}

	return config
}

// resolveMimicXDPMode 把节点的 XDPMode 归一为写入 mimic 配置的值。
// 仅 "native" 透传；空、"skb" 及任何已被校验拒绝之外的值都回落到 "skb"（通用 XDP，
// 兼容不支持 native 的网卡）——这是默认且对 VPS virtio 网卡最稳妥的模式。
// 取值合法性由 validator 的 schema 阶段保证（""/"skb"/"native"）；这里仅做安全归一。
func resolveMimicXDPMode(mode string) string {
	if mode == "native" {
		return "native"
	}
	return "skb"
}

// collectMimicPorts 扫描一组 peer，收集所有 mimic 接口（p.Mimic==true）的监听端口，
// 去重并升序排序。mimic 附着在节点的 egress NIC 上，每个 mimic 监听端口对应 egress
// 配置里的一条 filter 行（local=<egress_ip>:<port>），见 docs/spec/artifacts/mimic.md。
// 仅收集 ListenPort>0 的端口：0 表示该接口未绑定监听端口，无法成为 mimic filter。
func collectMimicPorts(peers []compiler.PeerInfo) []int {
	seen := make(map[int]bool)
	var ports []int
	for _, p := range peers {
		if !p.Mimic || p.ListenPort <= 0 || seen[p.ListenPort] {
			continue
		}
		seen[p.ListenPort] = true
		ports = append(ports, p.ListenPort)
	}
	sort.Ints(ports)
	return ports
}

// NodeTransitCIDRs 解析某节点 SNAT 修复应覆盖的 transit 地址池。
//
// 节点的 per-peer transit 地址来自其所属 domain 的 transit 池（domain.TransitCIDR，
// 留空时回退默认 10.10.0.0/24，与 allocator/compiler 的解析规则一致）。一个节点只属于
// 一个 domain，因此通常返回单个 CIDR；返回切片是为了与 InstallScriptConfig.TransitCIDRs
// 的契约一致，并在未来跨域链路出现时无需改签名。调用方应把结果传给 RenderInstallScript。
func NodeTransitCIDRs(topo *model.Topology, node *model.Node) []string {
	if topo == nil || node == nil {
		return []string{defaultTransitCIDR}
	}
	for i := range topo.Domains {
		if topo.Domains[i].ID != node.DomainID {
			continue
		}
		if cidr := topo.Domains[i].TransitCIDR; cidr != "" {
			return []string{cidr}
		}
		return []string{defaultTransitCIDR}
	}
	return []string{defaultTransitCIDR}
}

// resolveTransitCIDRs 把调用方传入的 transit 地址池规整为「去重、非空、稳定顺序」的列表。
// 空字符串项被丢弃；整体为空时回退为默认池 [10.10.0.0/24]，保证 SNAT 规则始终有源池可写，
// 同时让既有三参调用方（不传 transitCIDRs）的行为与历史完全一致。
func resolveTransitCIDRs(transitCIDRs []string) []string {
	seen := make(map[string]bool)
	resolved := make([]string, 0, len(transitCIDRs))
	for _, cidr := range transitCIDRs {
		if cidr == "" || seen[cidr] {
			continue
		}
		seen[cidr] = true
		resolved = append(resolved, cidr)
	}
	if len(resolved) == 0 {
		return []string{defaultTransitCIDR}
	}
	return resolved
}

// ClientInstallScriptConfig client 安装脚本配置
type ClientInstallScriptConfig struct {
	NodeName string // 原始节点名，仅用于脚本头部注释（注释在 bash 中不会被求值）
	// NodeNameQuoted 同 InstallScriptConfig.NodeNameQuoted：经 bashSingleQuote
	// 转义的节点名，用于 root 身份执行的 echo 行，防止命令替换注入（D15）。
	NodeNameQuoted string
	NodeRole       string
	Platform       string
	OverlayIP      string
	MTU            int
	SysctlConfName string
	// HasMimic / MimicPorts 同 InstallScriptConfig：当 client 的唯一 wg0 链路
	// transport=="tcp" 时为真，MimicPorts 即 client wg0 的监听端口（单端口）。
	// 见 docs/spec/artifacts/mimic.md。
	HasMimic     bool
	MimicPorts   []int
	MimicXDPMode string // 归一后的 xdp_mode（"skb"/"native"），见 InstallScriptConfig
	// SigningPubkeyPEM is the pinned Ed25519 verifying public key (PEM) for bundle-signature
	// verification; same semantics as InstallScriptConfig.SigningPubkeyPEM. Empty when signing is
	// off (opt-in), keeping the client install.sh byte-identical to the pre-signing output.
	SigningPubkeyPEM string
	// SplicePlaceholder enables the AgentHeld custody splice block on the copied wg0.conf in Phase 2;
	// same semantics as InstallScriptConfig.SplicePlaceholder. False keeps the client install.sh
	// byte-identical to the pre-splice output. See docs/spec/controller/key-custody.md.
	SplicePlaceholder bool
	// SplicePlaceholderToken is the exact PrivateKey value to match for replacement
	// (PrivateKeyPlaceholder); same semantics as InstallScriptConfig.SplicePlaceholderToken. Only
	// meaningful when SplicePlaceholder is true.
	SplicePlaceholderToken string
}

const clientInstallScriptTemplate = `#!/usr/bin/env bash
# Install script for client node: {{ .NodeName }}
# Generated by Overlay Network Config Orchestrator
# Platform: {{ .Platform }}
# Role: {{ .NodeRole }}
# Architecture: single-interface (client)
#
# Usage:
#   sudo bash install.sh              # Install / upgrade overlay
#   sudo bash install.sh --uninstall  # Completely remove overlay

set -euo pipefail

UNINSTALL=0
for arg in "$@"; do
    case "$arg" in
        --uninstall|-u) UNINSTALL=1 ;;
    esac
done

# ============================================================
# Uninstall All
# ============================================================

if [ "$UNINSTALL" -eq 1 ]; then
    # Check root
    if [ "$(id -u)" -ne 0 ]; then
        echo "ERROR: This script must be run as root" >&2
        exit 1
    fi

    echo "=== Uninstalling overlay from client node: "{{ .NodeNameQuoted }}" ==="

{{ if .HasMimic -}}
    # Tear down mimic TCP-shaping transport (docs/spec/artifacts/mimic.md): re-detect the egress
    # NIC, stop/disable mimic@<egress> and remove its config. Tolerate absence.
    _mimic_egress_if="$(ip route show default 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="dev"){print $(i+1); exit}}')"
    if [ -n "$_mimic_egress_if" ]; then
        echo "  Stopping mimic@$_mimic_egress_if..."
        systemctl disable --now "mimic@$_mimic_egress_if" 2>/dev/null || true
        rm -f "/etc/mimic/$_mimic_egress_if.conf"
    fi
{{ end -}}

    # Stop and disable wg0
    if command -v wg >/dev/null 2>&1 && wg show "wg0" > /dev/null 2>&1; then
        echo "  Stopping WireGuard interface: wg0..."
        wg-quick down "wg0" 2>/dev/null || true
    fi
    if systemctl is-enabled "wg-quick@wg0" >/dev/null 2>&1; then
        systemctl disable "wg-quick@wg0" 2>/dev/null || true
    fi
    rm -f "/etc/wireguard/wg0.conf"

    # Stop and disable ALL remaining WireGuard interfaces
    if command -v wg >/dev/null 2>&1; then
        for _iface in $(wg show interfaces 2>/dev/null); do
            echo "  Stopping WireGuard interface: $_iface..."
            wg-quick down "$_iface" 2>/dev/null || true
            systemctl disable "wg-quick@$_iface" 2>/dev/null || true
        done
    fi
    rm -f /etc/wireguard/*.conf

    # Remove sysctl config
    rm -f "/etc/sysctl.d/{{ .SysctlConfName }}"
    sysctl --system > /dev/null 2>&1

    echo ""
    echo "============================================================"
    echo "  Overlay completely removed from client node: "{{ .NodeNameQuoted }}
    echo "============================================================"
    exit 0
fi

# ============================================================
# Phase 0: Cleanup Previous Installation
# ============================================================

echo "=== Phase 0: Cleanup Previous Installation ==="

# Stop WireGuard wg0 if running
if command -v wg >/dev/null 2>&1 && wg show "wg0" > /dev/null 2>&1; then
    echo "  Stopping WireGuard interface: wg0..."
    wg-quick down "wg0" 2>/dev/null || true
fi
if systemctl is-enabled "wg-quick@wg0" >/dev/null 2>&1; then
    systemctl disable "wg-quick@wg0" 2>/dev/null || true
fi
if [ -f "/etc/wireguard/wg0.conf" ]; then
    rm -f "/etc/wireguard/wg0.conf"
    echo "  Removed old config: /etc/wireguard/wg0.conf"
fi

# Clean up legacy WireGuard interfaces
if command -v wg >/dev/null 2>&1; then
    for _legacy_iface in $(wg show interfaces 2>/dev/null); do
        [ "$_legacy_iface" = "wg0" ] && continue
        echo "  Stopping legacy WireGuard interface: $_legacy_iface..."
        wg-quick down "$_legacy_iface" 2>/dev/null || true
        if systemctl is-enabled "wg-quick@$_legacy_iface" >/dev/null 2>&1; then
            systemctl disable "wg-quick@$_legacy_iface" 2>/dev/null || true
        fi
    done
fi
for _legacy_conf in /etc/wireguard/*.conf; do
    [ -f "$_legacy_conf" ] || continue
    _legacy_name="$(basename "$_legacy_conf")"
    [ "$_legacy_name" = "wg0.conf" ] && continue
    rm -f "$_legacy_conf"
    echo "  Removed legacy config: $_legacy_conf"
done

if [ -f "/etc/sysctl.d/{{ .SysctlConfName }}" ]; then
    rm -f "/etc/sysctl.d/{{ .SysctlConfName }}"
    echo "  Removed old sysctl config"
fi

echo "Phase 0 complete."

# ============================================================
# Phase 1: Environment Preparation
# ============================================================

echo "=== Phase 1: Environment Preparation ==="

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

{{ if .SigningPubkeyPEM -}}
# Verify the bundle's Ed25519 signature BEFORE the checksum check (docs/spec/controller/signing.md).
# bundle.sig is base64(raw 64-byte Ed25519 signature) over the exact bytes of checksums.sha256
# (the canonical bundle digest). The verifying public key is pinned below at generation time, so a
# tampered checksums.sha256 (even with matching file hashes) is rejected before any root action.
if [ -f "$SCRIPT_DIR/bundle.sig" ]; then
    echo "Verifying bundle signature..."
    if ! command -v openssl >/dev/null 2>&1; then
        # bundle.sig is present but we cannot verify it: fail clearly, never silently skip.
        echo "ERROR: bundle.sig present but openssl is not installed; cannot verify signature" >&2
        exit 1
    fi
    # Write the pinned verifying public key to a temp file for openssl pkeyutl -pubin.
    _sig_pubkey="$(mktemp)"
    _sig_raw="$(mktemp)"
    cleanup_sig() {
        rm -f "$_sig_pubkey" "$_sig_raw"
    }
    trap cleanup_sig EXIT
    cat > "$_sig_pubkey" << 'YAOG_SIGNING_PUBKEY_PEM'
{{ .SigningPubkeyPEM }}
YAOG_SIGNING_PUBKEY_PEM
    # Decode base64 signature to raw bytes for openssl -rawin verification.
    if ! base64 -d "$SCRIPT_DIR/bundle.sig" > "$_sig_raw" 2>/dev/null; then
        echo "ERROR: failed to decode bundle.sig (not valid base64)" >&2
        exit 1
    fi
    # Ed25519 is a one-shot (raw) signature: -rawin feeds the message directly, no pre-hash.
    # openssl without Ed25519 support exits nonzero here, satisfying the fail-clear requirement.
    if ! openssl pkeyutl -verify -pubin -inkey "$_sig_pubkey" -rawin -sigfile "$_sig_raw" -in "$SCRIPT_DIR/checksums.sha256" >/dev/null 2>&1; then
        echo "ERROR: bundle signature verification failed (openssl missing Ed25519 support or signature invalid)" >&2
        exit 1
    fi
    echo "Bundle signature verification passed."
    cleanup_sig
    trap - EXIT
else
    # This install.sh was rendered with signing enabled, so bundle.sig is MANDATORY: a missing
    # signature is signature-stripping tamper, not an unsigned bundle. We KNOW the bundle was
    # signed at generation time (the verifying key is pinned above), so refuse to proceed rather
    # than fall through to the bare checksum check an attacker could satisfy with rewritten files.
    echo "ERROR: bundle was signed at generation but bundle.sig is missing; refusing to proceed (possible signature-stripping tamper)" >&2
    exit 1
fi

{{ end -}}
# Verify checksums if available
if [ -f "$SCRIPT_DIR/checksums.sha256" ]; then
    echo "Verifying file integrity..."
    cd "$SCRIPT_DIR"
    if ! sha256sum --status -c checksums.sha256; then
        echo "ERROR: Checksum validation failed!" >&2
        exit 1
    fi
    echo "Checksum validation passed."
    cd - >/dev/null
fi

# Check root
if [ "$(id -u)" -ne 0 ]; then
    echo "ERROR: This script must be run as root" >&2
    exit 1
fi

# Detect OS
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS_ID="$ID"
    OS_VERSION="$VERSION_ID"
    echo "Detected OS: $OS_ID $OS_VERSION"
else
    echo "ERROR: Cannot detect OS" >&2
    exit 1
fi

# Install dependencies (cross-distro, idempotent; no Babel/iptables for a client)
#
# A client needs only the WireGuard userspace + iproute2 + openssl (signed bundles). Same
# fast-no-op-once-present logic as the router script: map each MISSING command to a package
# and install via the detected manager (apt/dnf/yum/zypper/pacman/apk). iproute2 -> iproute
# on dnf/yum/zypper. Unknown manager with tools still missing fails with an explicit list.
echo "Installing dependencies..."

YAOG_PM=""
for _c in apt-get dnf yum zypper pacman apk; do
    if command -v "$_c" >/dev/null 2>&1; then YAOG_PM="$_c"; break; fi
done

_pm_pkg() {
    case "$1:$YAOG_PM" in
        iproute2:dnf|iproute2:yum|iproute2:zypper) echo iproute ;;
        *) echo "$1" ;;
    esac
}

_PM_REFRESHED=0
_pm_install() {
    local _pkg; _pkg="$(_pm_pkg "$1")"
    if [ "$_PM_REFRESHED" -eq 0 ]; then
        case "$YAOG_PM" in
            apt-get) apt-get update -qq || true ;;
            apk)     apk update >/dev/null 2>&1 || true ;;
        esac
        _PM_REFRESHED=1
    fi
    case "$YAOG_PM" in
        apt-get) DEBIAN_FRONTEND=noninteractive apt-get install -y -qq "$_pkg" ;;
        dnf)     dnf install -y "$_pkg" ;;
        yum)     yum install -y "$_pkg" ;;
        zypper)  zypper --non-interactive install "$_pkg" ;;
        pacman)  pacman -Sy --noconfirm "$_pkg" ;;
        apk)     apk add --no-progress "$_pkg" ;;
        *)       return 1 ;;
    esac
}

YAOG_MISSING=""
ensure_cmd() {
    command -v "$1" >/dev/null 2>&1 && return 0
    if [ -n "$YAOG_PM" ]; then
        echo "  - installing $2 (provides '$1')"
        _pm_install "$2" || true
    fi
    command -v "$1" >/dev/null 2>&1 || YAOG_MISSING="$YAOG_MISSING $1"
}

ensure_cmd wg       wireguard-tools
ensure_cmd wg-quick wireguard-tools
ensure_cmd ip       iproute2
ensure_cmd openssl  openssl
{{ if .HasMimic -}}
# mimic TCP-shaping transport (docs/spec/artifacts/mimic.md): the client wg0 link uses
# transport="tcp". YAOG ships no mimic binary — install it from the distro / AUR.
ensure_cmd mimic mimic
if [ ! -d /sys/fs/bpf ] && ! grep -qw bpf /proc/filesystems 2>/dev/null; then
    echo "WARNING: eBPF/BPF filesystem not detected; mimic requires kernel eBPF support" >&2
fi
{{ end -}}

if [ -n "$YAOG_MISSING" ]; then
    echo "ERROR: missing required tools:$YAOG_MISSING" >&2
    echo "  No supported package manager installed them automatically. Install the equivalents of" >&2
    echo "  wireguard-tools (wg, wg-quick), iproute2 (ip), openssl{{ if .HasMimic }}, mimic{{ end }}, then re-run." >&2
    exit 1
fi

# WireGuard kernel module: built into Linux >= 5.6; load it (best-effort) on older kernels.
modprobe wireguard 2>/dev/null || true

mkdir -p /etc/wireguard

echo "Phase 1 complete."

# ============================================================
# Phase 2: Deploy Configuration
# ============================================================

echo "=== Phase 2: Deploy Configuration ==="

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Deploy WireGuard wg0 configuration
echo "Deploying WireGuard client configuration..."
cp "$SCRIPT_DIR/wireguard/wg0.conf" /etc/wireguard/wg0.conf
chmod 600 /etc/wireguard/wg0.conf
echo "  Deployed: /etc/wireguard/wg0.conf"
{{ if .SplicePlaceholder -}}
# AgentHeld custody: splice the node's locally-held private key into the COPIED wg0.conf (never the
# bundle conf — the signed bundle stays pristine so re-runs keep passing sha256sum -c). This runs
# in Phase 2, AFTER the Phase-1 signature/checksum verify (over the pristine placeholder bundle) and
# BEFORE wg-quick up. Injection-safe: no sed/regex; the key is read once and the file rewritten line
# by line. Re-run safe: the preceding cp restores the placeholder conf, so each run re-splices the
# same stable key deterministically; the grep guard skips only a conf that carries no placeholder
# (e.g. an air-gap bundle, which never renders this block).
if grep -qxF 'PrivateKey = {{ .SplicePlaceholderToken }}' /etc/wireguard/wg0.conf; then
    if [ ! -s /etc/wireguard/agent.key ]; then
        echo "ERROR: /etc/wireguard/wg0.conf expects an agent-held private key but /etc/wireguard/agent.key is missing or empty" >&2
        exit 1
    fi
    # Command substitution strips the trailing newline, yielding the bare base64 key.
    _agent_key="$(cat /etc/wireguard/agent.key)"
    _spliced="$(mktemp)"
    # The scratch file transiently holds the real private key; remove it on any exit.
    trap 'rm -f "$_spliced"' EXIT
    while IFS= read -r line || [ -n "$line" ]; do
        if [ "$line" = 'PrivateKey = {{ .SplicePlaceholderToken }}' ]; then
            printf 'PrivateKey = %s\n' "$_agent_key" >> "$_spliced"
        else
            printf '%s\n' "$line" >> "$_spliced"
        fi
    done < /etc/wireguard/wg0.conf
    cat "$_spliced" > /etc/wireguard/wg0.conf
    rm -f "$_spliced"
    trap - EXIT
    chmod 600 /etc/wireguard/wg0.conf
    echo "  Spliced agent-held private key into /etc/wireguard/wg0.conf"
fi
{{ end -}}

# Deploy sysctl configuration
cp "$SCRIPT_DIR/sysctl/{{ .SysctlConfName }}" /etc/sysctl.d/{{ .SysctlConfName }}
echo "  Deployed: /etc/sysctl.d/{{ .SysctlConfName }}"

echo "Phase 2 complete."

# ============================================================
# Phase 3: Activate and Verify
# ============================================================

echo "=== Phase 3: Activate and Verify ==="

# Apply sysctl
echo "Applying sysctl settings..."
sysctl --system > /dev/null 2>&1

{{ if .HasMimic -}}
# Provision mimic TCP-shaping transport BEFORE bringing wg0 up (docs/spec/artifacts/mimic.md
# «Ordering»). mimic attaches to the EGRESS NIC, detected at runtime; YAOG supplies the port set.
echo "Provisioning mimic TCP-shaping transport..."
MIMIC_EGRESS_IF="$(ip route show default 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="dev"){print $(i+1); exit}}')"
MIMIC_EGRESS_IP="$(ip route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src"){print $(i+1); exit}}')"
if [ -z "$MIMIC_EGRESS_IF" ] || [ -z "$MIMIC_EGRESS_IP" ]; then
    echo "ERROR: could not detect egress interface/IP for mimic (no default route?)" >&2
    exit 1
fi
echo "  mimic egress: $MIMIC_EGRESS_IF ($MIMIC_EGRESS_IP)"
mkdir -p /etc/mimic
{
    {{ range .MimicPorts -}}
    echo "filter = local=${MIMIC_EGRESS_IP}:{{ . }}"
    {{ end -}}
    echo "xdp_mode = {{ .MimicXDPMode }}"
} > "/etc/mimic/${MIMIC_EGRESS_IF}.conf"
echo "  Wrote /etc/mimic/${MIMIC_EGRESS_IF}.conf"
systemctl enable --now "mimic@${MIMIC_EGRESS_IF}"
echo "  Started mimic@${MIMIC_EGRESS_IF}"
{{ end -}}

# Start WireGuard wg0
echo "Starting WireGuard wg0..."
wg-quick up "wg0"
systemctl enable wg-quick@"wg0" 2>/dev/null || true

# Show status
echo ""
echo "============================================================"
echo "  Node: "{{ .NodeNameQuoted }}
echo "  Overlay IP: {{ .OverlayIP }} (on wg0)"
echo "  Role: {{ .NodeRole }}"
echo "  WireGuard interface: wg0"
{{- if gt .MTU 0 }}
echo "  MTU: {{ .MTU }}"
{{- end }}
echo "============================================================"
echo ""
echo "WireGuard status:"
echo "--- wg0 ---"
wg show "wg0" 2>/dev/null || echo "  (not yet connected)"
echo ""
echo "Installation complete!"
echo "Note: If the router is not yet online, connection will establish once it comes up."
`

// RenderClientInstallScript 渲染 client 节点的安装脚本。
//
// clientInfo 为可选变参，向后兼容既有的单参调用（不传时 mimic 字段保持零值，输出与旧实现
// 逐字节一致）。当 client 的唯一 wg0 链路 transport=="tcp"（clientInfo.Mimic==true）时，
// 取其 ListenPort 作为 mimic filter 端口，装配 mimic（见 docs/spec/artifacts/mimic.md）。
// 调用方（internal/render）应传入该 client 的 ClientPeerInfo 以启用 mimic 支持。
func RenderClientInstallScript(node *model.Node, clientInfo ...*compiler.ClientPeerInfo) (string, error) {
	config := buildClientInstallScriptConfig(node, clientInfo)
	return renderTemplate("client-install.sh", clientInstallScriptTemplate, config)
}

// RenderClientInstallScriptSigned renders the client install script with bundle-signature
// verification enabled (openssl Ed25519 verify of bundle.sig over checksums.sha256 against the
// pinned signingPubkeyPEM, before the existing sha256sum -c). splice gates the AgentHeld
// custody-splice block on the copied wg0.conf (CustodySplice{} disables it, keeping output
// byte-identical to the pre-splice path). Empty signingPubkeyPEM yields output byte-identical to
// RenderClientInstallScript (opt-in). The export path calls this only when an operator signing key
// is configured. See docs/spec/controller/signing.md and docs/spec/controller/key-custody.md.
func RenderClientInstallScriptSigned(node *model.Node, signingPubkeyPEM string, splice CustodySplice, clientInfo ...*compiler.ClientPeerInfo) (string, error) {
	config := buildClientInstallScriptConfig(node, clientInfo)
	config.SigningPubkeyPEM = signingPubkeyPEM
	config.SplicePlaceholder = splice.Enabled
	config.SplicePlaceholderToken = splice.Token
	return renderTemplate("client-install.sh", clientInstallScriptTemplate, config)
}

// buildClientInstallScriptConfig assembles the ClientInstallScriptConfig shared by the plain and
// signed client renderers. SigningPubkeyPEM is left empty here; signed callers set it after.
func buildClientInstallScriptConfig(node *model.Node, clientInfo []*compiler.ClientPeerInfo) ClientInstallScriptConfig {
	config := ClientInstallScriptConfig{
		NodeName:       node.Name,
		NodeNameQuoted: bashSingleQuote(node.Name),
		NodeRole:       node.Role,
		Platform:       node.Platform,
		OverlayIP:      node.OverlayIP,
		MTU:            node.MTU,
		MimicXDPMode:   resolveMimicXDPMode(node.XDPMode),
		SysctlConfName: "99-overlay.conf",
	}

	// client wg0 是单一链路：若其 transport=="tcp"（Mimic==true）且监听端口有效，
	// 装配 mimic，filter 端口即该 wg0 的监听端口。
	if len(clientInfo) > 0 && clientInfo[0] != nil {
		ci := clientInfo[0]
		if ci.Mimic && ci.ListenPort > 0 {
			config.HasMimic = true
			config.MimicPorts = []int{ci.ListenPort}
		}
	}

	if config.Platform == "" {
		config.Platform = "debian"
	}

	return config
}
