package renderer

import (
	"github.com/kunorikiku/yet-another-overlay-generator/internal/model"
)

// SysctlConfig holds the data used to render a node's sysctl configuration.
type SysctlConfig struct {
	NodeName         string
	EnableForwarding bool
}

const sysctlConfigTemplate = `# Sysctl configuration for {{ .NodeName }}
# Generated by Overlay Network Config Orchestrator

{{- if .EnableForwarding }}

#  IPv4 
net.ipv4.ip_forward = 1

#  IPv6 （）
# net.ipv6.conf.all.forwarding = 1

# （Babel ）
net.ipv4.conf.all.rp_filter = 0
net.ipv4.conf.default.rp_filter = 0
{{- else }}

# （ peer ）
#  rp_filter  Babel 
net.ipv4.conf.all.rp_filter = 2
net.ipv4.conf.default.rp_filter = 2
{{- end }}
`

// RenderSysctlConfig renders the sysctl configuration for a single node.
func RenderSysctlConfig(node *model.Node) (string, error) {
	config := SysctlConfig{
		NodeName:         node.Name,
		EnableForwarding: node.Capabilities.CanForward,
	}

	return renderTemplate("sysctl.conf", sysctlConfigTemplate, config)
}

// RenderAllSysctlConfigs renders the sysctl configuration for every node in the topology.
func RenderAllSysctlConfigs(topo *model.Topology) (map[string]string, error) {
	configs := make(map[string]string)

	for i := range topo.Nodes {
		node := &topo.Nodes[i]
		config, err := RenderSysctlConfig(node)
		if err != nil {
			return nil, err
		}
		configs[node.ID] = config
	}

	return configs, nil
}
