package renderer

import (
	"github.com/kunorikiku/yet-another-overlay-generator/internal/model"
)

// SysctlConfig sysctl 配置渲染数据
type SysctlConfig struct {
	NodeName         string
	EnableForwarding bool
}

const sysctlConfigTemplate = `# Sysctl configuration for {{ .NodeName }}
# Generated by Overlay Network Config Orchestrator

{{- if .EnableForwarding }}

# 启用 IPv4 转发
net.ipv4.ip_forward = 1

# 启用 IPv6 转发（如需要）
# net.ipv6.conf.all.forwarding = 1

# 放宽反向路径过滤（Babel 动态路由需要）
net.ipv4.conf.all.rp_filter = 0
net.ipv4.conf.default.rp_filter = 0
{{- else }}

# 此节点不启用转发（纯 peer 模式）
# 仍需放宽 rp_filter 以支持 Babel 学习的路由
net.ipv4.conf.all.rp_filter = 2
net.ipv4.conf.default.rp_filter = 2
{{- end }}
`

// RenderSysctlConfig 渲染单个节点的 sysctl 配置
func RenderSysctlConfig(node *model.Node) (string, error) {
	config := SysctlConfig{
		NodeName:         node.Name,
		EnableForwarding: node.Capabilities.CanForward,
	}

	return renderTemplate("sysctl.conf", sysctlConfigTemplate, config)
}

// RenderAllSysctlConfigs 渲染所有节点的 sysctl 配置
func RenderAllSysctlConfigs(topo *model.Topology) (map[string]string, error) {
	configs := make(map[string]string)

	for i := range topo.Nodes {
		node := &topo.Nodes[i]
		config, err := RenderSysctlConfig(node)
		if err != nil {
			return nil, err
		}
		configs[node.ID] = config
	}

	return configs, nil
}
