package renderer

import _ "embed"

// The install / client-install / sysctl renderers are text/template emitters whose bodies live in
// templates/*.tmpl and are embedded here via go:embed, rather than as inline Go string literals.
// The bodies are large shell scripts (the root-executed install path chief among them); keeping them
// as standalone files lets shellcheck lint the generated scripts directly (see script_shellcheck_test.go)
// and keeps script.go/sysctl.go focused on the typed config-struct builders that fill them
// (framework-refactor plan-6). The embedded bytes are the single source that renderTemplate parses;
// moving them out of Go changed no generated byte (proven by the localcompile golden corpus).

//go:embed templates/install.sh.tmpl
var installScriptTemplate string

//go:embed templates/client-install.sh.tmpl
var clientInstallScriptTemplate string

//go:embed templates/sysctl.conf.tmpl
var sysctlConfigTemplate string
