package renderer

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"

	"github.com/kunorikiku/yet-another-overlay-generator/internal/compiler"
	"github.com/kunorikiku/yet-another-overlay-generator/internal/model"
)

// WireGuardInterfaceConfig 单个 per-peer WireGuard 接口配置
type WireGuardInterfaceConfig struct {
	// 节点信息
	NodeName      string
	InterfaceName string
	PrivateKey    string
	TransitIP     string // 点对点 transit 地址
	ListenPort    int
	MTU           int

	// IPv6 link-local（Babel 需要）
	LocalLinkLocal string

	// Client overlay IP（仅当 IsClientPeer=true 时有值，用于 PostUp 路由注入）
	ClientOverlayIP string

	// 唯一的 Peer
	Peer WireGuardPeer
}

// WireGuardPeer WireGuard peer 配置
type WireGuardPeer struct {
	// 描述/名字
	Name string

	// 公钥
	PublicKey string

	// AllowedIPs
	AllowedIPs string

	// Endpoint（可选）
	Endpoint string

	// PersistentKeepalive（秒，0 表示不启用）
	PersistentKeepalive int
}

// per-peer 接口模板：每个接口只有一个 Peer
const wgPerPeerConfigTemplate = `# WireGuard per-peer interface: {{ .InterfaceName }}
# Node: {{ .NodeName }} -> Peer: {{ .Peer.Name }}
# Generated by Overlay Network Config Orchestrator

[Interface]
PrivateKey = {{ .PrivateKey }}
Address = {{ .TransitIP }}/32
Table = off
{{- if gt .ListenPort 0 }}
ListenPort = {{ .ListenPort }}
{{- end }}
{{- if gt .MTU 0 }}
MTU = {{ .MTU }}
{{- end }}

# Add IPv6 link-local for Babel
PostUp = ip -6 addr add {{ .LocalLinkLocal }}/64 dev %i 2>/dev/null || true
PostDown = ip -6 addr del {{ .LocalLinkLocal }}/64 dev %i 2>/dev/null || true
{{- if .ClientOverlayIP }}
# Route client overlay IP through this interface (discovered by Babel)
PostUp = ip route replace {{ .ClientOverlayIP }}/32 dev %i 2>/dev/null || true
PostDown = ip route del {{ .ClientOverlayIP }}/32 dev %i 2>/dev/null || true
{{- end }}

# Peer: {{ .Peer.Name }}
[Peer]
PublicKey = {{ .Peer.PublicKey }}
AllowedIPs = {{ .Peer.AllowedIPs }}
{{- if .Peer.Endpoint }}
Endpoint = {{ .Peer.Endpoint }}
{{- end }}
{{- if gt .Peer.PersistentKeepalive 0 }}
PersistentKeepalive = {{ .Peer.PersistentKeepalive }}
{{- end }}
`

// Client wg0 配置模板：单一接口，无 Table=off，无 transit IP
const wgClientConfigTemplate = `# WireGuard client interface: wg0
# Node: {{ .NodeName }} (client)
# Generated by Overlay Network Config Orchestrator

[Interface]
PrivateKey = {{ .PrivateKey }}
Address = {{ .OverlayIP }}/32
{{- if gt .ListenPort 0 }}
ListenPort = {{ .ListenPort }}
{{- end }}
{{- if gt .MTU 0 }}
MTU = {{ .MTU }}
{{- end }}

# Peer: Router
[Peer]
PublicKey = {{ .RouterPublicKey }}
AllowedIPs = {{ .AllowedIPs }}
{{- if .RouterEndpoint }}
Endpoint = {{ .RouterEndpoint }}
{{- end }}
PersistentKeepalive = 25
`

// WireGuardClientConfig client wg0 配置数据
type WireGuardClientConfig struct {
	NodeName        string
	PrivateKey      string
	OverlayIP       string
	ListenPort      int
	MTU             int
	RouterPublicKey string
	RouterEndpoint  string
	AllowedIPs      string
}

// RenderClientWireGuardConfig 渲染 client 节点的 wg0 配置
func RenderClientWireGuardConfig(clientInfo *compiler.ClientPeerInfo) (string, error) {
	allowedIPs := strings.Join(clientInfo.DomainCIDRs, ", ")
	if allowedIPs == "" {
		allowedIPs = "0.0.0.0/0"
	}

	config := WireGuardClientConfig{
		NodeName:        clientInfo.NodeName,
		PrivateKey:      clientInfo.PrivateKey,
		OverlayIP:       clientInfo.OverlayIP,
		ListenPort:      clientInfo.ListenPort,
		MTU:             clientInfo.MTU,
		RouterPublicKey: clientInfo.RouterPublicKey,
		RouterEndpoint:  clientInfo.RouterEndpoint,
		AllowedIPs:      allowedIPs,
	}

	return renderTemplate("wg0.conf", wgClientConfigTemplate, config)
}

// RenderPerPeerWireGuardConfig 渲染单个 per-peer WireGuard 接口配置。
//
// 接口 MTU 取自 peer.MTU（而非 node.MTU）：compiler 已按链路传输计算每个接口的有效 MTU——
// mimic 链路为 (node.MTU 或 1420) − 12（扣 mimic 的 12 字节开销，见 docs/spec/artifacts/mimic.md
// 「MTU −12」），非 mimic 链路 peer.MTU == node.MTU，因此非 mimic 输出与旧实现逐字节一致。
func RenderPerPeerWireGuardConfig(node *model.Node, peer compiler.PeerInfo, keys compiler.KeyPair) (string, error) {
	config := WireGuardInterfaceConfig{
		NodeName:        node.Name,
		InterfaceName:   peer.InterfaceName,
		PrivateKey:      keys.PrivateKey,
		TransitIP:       peer.LocalTransitIP,
		ListenPort:      peer.ListenPort,
		MTU:             peer.MTU, // 见函数 doc：mimic 链路 -12，非 mimic == node.MTU（逐字节不变）
		LocalLinkLocal:  peer.LocalLinkLocal,
		ClientOverlayIP: peer.ClientOverlayIP,
		Peer: WireGuardPeer{
			Name:                peer.NodeName,
			PublicKey:           peer.PublicKey,
			AllowedIPs:          strings.Join(peer.AllowedIPs, ", "),
			Endpoint:            peer.Endpoint,
			PersistentKeepalive: peer.PersistentKeepalive,
		},
	}

	return renderTemplate(peer.InterfaceName+".conf", wgPerPeerConfigTemplate, config)
}

// RenderAllWireGuardConfigs 渲染所有节点的所有 WireGuard 配置
// 返回 map[nodeID]map[interfaceName]configContent
func RenderAllWireGuardConfigs(topo *model.Topology, peerMap map[string][]compiler.PeerInfo, keys map[string]compiler.KeyPair) (map[string]string, error) {
	// 新架构：返回的 key 格式为 "nodeID:interfaceName"
	configs := make(map[string]string)

	nodeMap := make(map[string]*model.Node)
	for i := range topo.Nodes {
		nodeMap[topo.Nodes[i].ID] = &topo.Nodes[i]
	}

	for nodeID, peers := range peerMap {
		node := nodeMap[nodeID]
		if node == nil {
			continue
		}

		key, ok := keys[nodeID]
		if !ok {
			return nil, fmt.Errorf("node %s is missing its key", nodeID)
		}

		for _, peer := range peers {
			config, err := RenderPerPeerWireGuardConfig(node, peer, key)
			if err != nil {
				return nil, fmt.Errorf("rendering WireGuard config for %s failed: %w", node.Name, err)
			}

			// key 格式："nodeID:interfaceName"
			configKey := nodeID + ":" + peer.InterfaceName
			configs[configKey] = config
		}
	}

	return configs, nil
}

// templateFuncs are the helpers available to every renderer template. shq wraps a value as a
// single shell token via the audited bashSingleQuote escaper, so user-controlled text (e.g. a
// GitHub proxy URL) baked into a root-executed install.sh cannot break out of its quoting —
// the defense-in-depth half of the "generated scripts run as root" principle. Adding the
// func is output-neutral for templates that do not call it.
var templateFuncs = template.FuncMap{
	"shq": bashSingleQuote,
}

func renderTemplate(name, tmpl string, data interface{}) (string, error) {
	t, err := template.New(name).Funcs(templateFuncs).Parse(tmpl)
	if err != nil {
		return "", fmt.Errorf("template parse failed: %w", err)
	}

	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("template render failed: %w", err)
	}

	return buf.String(), nil
}
