package renderer

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"

	"github.com/kunorikiku/yet-another-overlay-generator/internal/compiler"
	"github.com/kunorikiku/yet-another-overlay-generator/internal/model"
)

// WireGuardInterfaceConfig is the configuration for a single per-peer WireGuard interface.
type WireGuardInterfaceConfig struct {
	// Node information
	NodeName      string
	InterfaceName string
	PrivateKey    string
	TransitIP     string // point-to-point transit address
	ListenPort    int
	MTU           int

	// IPv6 link-local (required by Babel)
	LocalLinkLocal string

	// Client overlay IP (set only when IsClientPeer=true, used for PostUp route injection)
	ClientOverlayIP string

	// The sole Peer
	Peer WireGuardPeer
}

// WireGuardPeer is the configuration for a WireGuard peer.
type WireGuardPeer struct {
	// Description / name
	Name string

	// Public key
	PublicKey string

	// AllowedIPs
	AllowedIPs string

	// Endpoint (optional)
	Endpoint string

	// PersistentKeepalive (seconds, 0 means disabled)
	PersistentKeepalive int
}

// per-peer interface template: each interface has exactly one Peer
const wgPerPeerConfigTemplate = `# WireGuard per-peer interface: {{ .InterfaceName }}
# Node: {{ .NodeName }} -> Peer: {{ .Peer.Name }}
# Generated by Overlay Network Config Orchestrator

[Interface]
PrivateKey = {{ .PrivateKey }}
Address = {{ .TransitIP }}/32
Table = off
{{- if gt .ListenPort 0 }}
ListenPort = {{ .ListenPort }}
{{- end }}
{{- if gt .MTU 0 }}
MTU = {{ .MTU }}
{{- end }}

# Add IPv6 link-local for Babel
PostUp = ip -6 addr add {{ .LocalLinkLocal }}/64 dev %i 2>/dev/null || true
PostDown = ip -6 addr del {{ .LocalLinkLocal }}/64 dev %i 2>/dev/null || true
{{- if .ClientOverlayIP }}
# Route client overlay IP through this interface (discovered by Babel)
PostUp = ip route replace {{ .ClientOverlayIP }}/32 dev %i 2>/dev/null || true
PostDown = ip route del {{ .ClientOverlayIP }}/32 dev %i 2>/dev/null || true
{{- end }}

# Peer: {{ .Peer.Name }}
[Peer]
PublicKey = {{ .Peer.PublicKey }}
AllowedIPs = {{ .Peer.AllowedIPs }}
{{- if .Peer.Endpoint }}
Endpoint = {{ .Peer.Endpoint }}
{{- end }}
{{- if gt .Peer.PersistentKeepalive 0 }}
PersistentKeepalive = {{ .Peer.PersistentKeepalive }}
{{- end }}
`

// Client wg0 config template: a single interface, no Table=off, no transit IP
const wgClientConfigTemplate = `# WireGuard client interface: wg0
# Node: {{ .NodeName }} (client)
# Generated by Overlay Network Config Orchestrator

[Interface]
PrivateKey = {{ .PrivateKey }}
Address = {{ .OverlayIP }}/32
{{- if gt .ListenPort 0 }}
ListenPort = {{ .ListenPort }}
{{- end }}
{{- if gt .MTU 0 }}
MTU = {{ .MTU }}
{{- end }}

# Peer: Router
[Peer]
PublicKey = {{ .RouterPublicKey }}
AllowedIPs = {{ .AllowedIPs }}
{{- if .RouterEndpoint }}
Endpoint = {{ .RouterEndpoint }}
{{- end }}
PersistentKeepalive = 25
`

// WireGuardClientConfig is the config data for a client's wg0 interface.
type WireGuardClientConfig struct {
	NodeName        string
	PrivateKey      string
	OverlayIP       string
	ListenPort      int
	MTU             int
	RouterPublicKey string
	RouterEndpoint  string
	AllowedIPs      string
}

// RenderClientWireGuardConfig renders the wg0 config for a client node.
func RenderClientWireGuardConfig(clientInfo *compiler.ClientPeerInfo) (string, error) {
	allowedIPs := strings.Join(clientInfo.DomainCIDRs, ", ")
	if allowedIPs == "" {
		allowedIPs = "0.0.0.0/0"
	}

	config := WireGuardClientConfig{
		NodeName:        clientInfo.NodeName,
		PrivateKey:      clientInfo.PrivateKey,
		OverlayIP:       clientInfo.OverlayIP,
		ListenPort:      clientInfo.ListenPort,
		MTU:             clientInfo.MTU,
		RouterPublicKey: clientInfo.RouterPublicKey,
		RouterEndpoint:  clientInfo.RouterEndpoint,
		AllowedIPs:      allowedIPs,
	}

	return renderTemplate("wg0.conf", wgClientConfigTemplate, config)
}

// RenderPerPeerWireGuardConfig renders the config for a single per-peer WireGuard interface.
//
// The interface MTU is taken from peer.MTU (not node.MTU): the compiler computes each
// interface's effective MTU from its link transport — a mimic link is (node.MTU or 1420) − 12
// (subtracting mimic's 12-byte overhead, see docs/spec/artifacts/mimic.md "MTU −12"), while a
// non-mimic link has peer.MTU == node.MTU, so non-mimic output is byte-for-byte identical to the
// old implementation.
func RenderPerPeerWireGuardConfig(node *model.Node, peer compiler.PeerInfo, keys compiler.KeyPair) (string, error) {
	config := WireGuardInterfaceConfig{
		NodeName:        node.Name,
		InterfaceName:   peer.InterfaceName,
		PrivateKey:      keys.PrivateKey,
		TransitIP:       peer.LocalTransitIP,
		ListenPort:      peer.ListenPort,
		MTU:             peer.MTU, // see function doc: mimic link -12, non-mimic == node.MTU (byte-for-byte unchanged)
		LocalLinkLocal:  peer.LocalLinkLocal,
		ClientOverlayIP: peer.ClientOverlayIP,
		Peer: WireGuardPeer{
			Name:                peer.NodeName,
			PublicKey:           peer.PublicKey,
			AllowedIPs:          strings.Join(peer.AllowedIPs, ", "),
			Endpoint:            peer.Endpoint,
			PersistentKeepalive: peer.PersistentKeepalive,
		},
	}

	return renderTemplate(peer.InterfaceName+".conf", wgPerPeerConfigTemplate, config)
}

// RenderAllWireGuardConfigs renders every WireGuard config for every node.
// Returns map[nodeID]map[interfaceName]configContent.
func RenderAllWireGuardConfigs(topo *model.Topology, peerMap map[string][]compiler.PeerInfo, keys map[string]compiler.KeyPair) (map[string]string, error) {
	// New architecture: the returned key has the format "nodeID:interfaceName"
	configs := make(map[string]string)

	nodeMap := make(map[string]*model.Node)
	for i := range topo.Nodes {
		nodeMap[topo.Nodes[i].ID] = &topo.Nodes[i]
	}

	for nodeID, peers := range peerMap {
		node := nodeMap[nodeID]
		if node == nil {
			continue
		}

		key, ok := keys[nodeID]
		if !ok {
			return nil, fmt.Errorf("node %s is missing its key", nodeID)
		}

		for _, peer := range peers {
			config, err := RenderPerPeerWireGuardConfig(node, peer, key)
			if err != nil {
				return nil, fmt.Errorf("rendering WireGuard config for %s failed: %w", node.Name, err)
			}

			// key format: "nodeID:interfaceName"
			configKey := nodeID + ":" + peer.InterfaceName
			configs[configKey] = config
		}
	}

	return configs, nil
}

// templateFuncs are the helpers available to every renderer template. shq wraps a value as a
// single shell token via the audited bashSingleQuote escaper, so user-controlled text (e.g. a
// GitHub proxy URL) baked into a root-executed install.sh cannot break out of its quoting —
// the defense-in-depth half of the "generated scripts run as root" principle. Adding the
// func is output-neutral for templates that do not call it.
var templateFuncs = template.FuncMap{
	"shq": bashSingleQuote,
}

func renderTemplate(name, tmpl string, data interface{}) (string, error) {
	t, err := template.New(name).Funcs(templateFuncs).Parse(tmpl)
	if err != nil {
		return "", fmt.Errorf("template parse failed: %w", err)
	}

	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("template render failed: %w", err)
	}

	return buf.String(), nil
}
