package model

// CurrentAllocSchemaVersion is the highest sticky-pin allocation-schema version this build
// understands (invariant I10). The compiler stamps it onto a compiled topology's
// AllocSchemaVersion; the validator fails closed on any INPUT topology stamped HIGHER than
// this (one written by a newer YAOG whose pin format we would otherwise misread as v1). It
// lives in model — alongside the AllocSchemaVersion field — so both the compiler (which
// stamps it) and the validator (which guards it) reference one source of truth without an
// import cycle (compiler imports validator, so the validator cannot import the compiler).
// See docs/spec/compiler/allocation-stability.md.
const CurrentAllocSchemaVersion = 1

// Topology is the complete network topology definition.
type Topology struct {
	// Project metadata.
	Project Project `json:"project"`

	// List of network domains.
	Domains []Domain `json:"domains"`

	// List of nodes.
	Nodes []Node `json:"nodes"`

	// List of edges (connections).
	Edges []Edge `json:"edges"`

	// Route policies (optional).
	RoutePolicies []RoutePolicy `json:"route_policies,omitempty"`

	// Allocation-schema version number (the schema version of sticky-pin allocation, see I10).
	// Lets future changes to the pin format be detected so old topologies can be migrated,
	// rather than silently misreading the old format as the new one.
	// On write-back the compiler stamps it uniformly as compiler.AllocationSchemaVersion (currently 1).
	// See docs/spec/compiler/allocation-stability.md (invariant I10).
	AllocSchemaVersion int `json:"alloc_schema_version,omitempty"`
}

// Project holds project metadata.
type Project struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description,omitempty"`
	Version     string `json:"version,omitempty"`
}

// Domain is a network-domain definition representing one overlay address space.
type Domain struct {
	ID             string   `json:"id"`
	Name           string   `json:"name"`
	CIDR           string   `json:"cidr"`
	Description    string   `json:"description,omitempty"`
	AllocationMode string   `json:"allocation_mode"` // "auto" | "manual"
	RoutingMode    string   `json:"routing_mode"`    // "static" | "babel" | "none"
	ReservedRanges []string `json:"reserved_ranges,omitempty"`

	// Transit (point-to-point link) address pool, used to allocate per-peer WireGuard interface addresses.
	// Defaults to 10.10.0.0/24 when empty.
	TransitCIDR string `json:"transit_cidr,omitempty"`
}

// Node is a network-node definition.
type Node struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Hostname string `json:"hostname,omitempty"`
	Platform string `json:"platform,omitempty"` // "debian" | "ubuntu"

	// Role: peer, router, relay, gateway, client.
	Role string `json:"role"`

	// DeploymentMode: "managed" (default) | "manual". ORTHOGONAL to Role. A "manual" node is deployed
	// BY HAND (no agent) inside a controller topology — typically because it is not publicly reachable
	// by the controller, or the operator does not want an agent on it. Empty == "managed" so every
	// existing topology is unchanged (mirrors Edge.Role's empty-default). A manual node carries its own
	// pre-known WireGuardPublicKey + a public endpoint in the topology (the controller never enrolls
	// it); the operator holds its private key off-controller, so zero-knowledge custody is preserved.
	// See implementation_plans/mixed-controller-local-mode-2026_06_25.
	DeploymentMode string `json:"deployment_mode,omitempty"`

	// Owning Domain ID (must reference an existing Domain).
	DomainID string `json:"domain_id"`

	// Overlay IP, auto-allocated at compile time.
	OverlayIP string `json:"overlay_ip,omitempty"`

	// WireGuard interface MTU (0 = use the system default, usually 1420).
	MTU int `json:"mtu,omitempty"`

	// XDP attach mode for mimic (transport=="tcp"): empty / "skb" / "native".
	// Empty is equivalent to "skb": generic XDP, compatible with almost all NICs (including
	// VPS virtio NICs that do not support native XDP), and is the default. "native" is
	// driver-level XDP, faster but requires NIC/driver support; set it only when the operator
	// has confirmed the node's NIC supports it. See docs/spec/artifacts/mimic.md.
	XDPMode string `json:"xdp_mode,omitempty"`

	// MimicEgressInterface overrides the auto-detected egress interface mimic binds to (by default the
	// default-route NIC). Empty = auto-detect (unchanged). Set it for multi-homed / policy-routing nodes
	// where the WG egress is not the default route (e.g. "wan0"). Only meaningful with a tcp link.
	MimicEgressInterface string `json:"mimic_egress_interface,omitempty"`

	// Babel router-id (MAC-48 format, e.g. 02:11:22:33:44:55).
	// Auto-generated by the compiler when left empty.
	RouterID string `json:"router_id,omitempty"`

	// Node capabilities.
	Capabilities NodeCapabilities `json:"capabilities"`

	// Whether the WireGuard key is fixed.
	FixedPrivateKey bool `json:"fixed_private_key,omitempty"`

	// WireGuard keys (only effective when fixed_private_key=true).
	WireGuardPrivateKey string `json:"wireguard_private_key,omitempty"`
	WireGuardPublicKey  string `json:"wireguard_public_key,omitempty"`

	// Public reachable address mappings (a node may have multiple endpoints).
	PublicEndpoints []PublicEndpoint `json:"public_endpoints,omitempty"`

	// Extra route prefixes (used by gateway: the prefixes announced outward).
	ExtraPrefixes []string `json:"extra_prefixes,omitempty"`

	// SSH connection info (used for automated deployment).
	SSHAlias   string `json:"ssh_alias,omitempty"`    // Host alias in ssh_config
	SSHHost    string `json:"ssh_host,omitempty"`     // SSH host address
	SSHPort    int    `json:"ssh_port,omitempty"`     // SSH port (default 22)
	SSHUser    string `json:"ssh_user,omitempty"`     // SSH username
	SSHKeyPath string `json:"ssh_key_path,omitempty"` // SSH private-key path

	// TelemetryProbes are operator-authorized active reachability checks run by this managed
	// node after the containing deployment bundle has passed the off-host keystone gate and
	// applied successfully. Host is an explicit IP literal or DNS hostname; it is intentionally
	// independent of topology membership so operators can monitor external dependencies. The
	// type discriminator is the extension boundary for future probe kinds (for example URL),
	// whose additional fields must be introduced and validated explicitly rather than smuggled
	// through Host.
	TelemetryProbes []TelemetryProbe `json:"telemetry_probes,omitempty"`
}

// TelemetryProbe is one manually configured active check. Zero interval/timeout values select
// the documented policy defaults. TCP accepts exactly one port; ICMP accepts none.
type TelemetryProbe struct {
	ID                  string `json:"id"`
	Type                string `json:"type"`
	Host                string `json:"host"`
	Port                int    `json:"port,omitempty"`
	IntervalSeconds     int    `json:"interval_seconds,omitempty"`
	TimeoutMilliseconds int    `json:"timeout_milliseconds,omitempty"`
}

const (
	TelemetryProbeICMP = "icmp"
	TelemetryProbeTCP  = "tcp"
)

// Value constants for Node.DeploymentMode. An empty value is equivalent to DeploymentManaged.
const (
	// DeploymentManaged is an agent-managed node (the default): it enrolls with the controller, which
	// learns its public key, and an agent pulls + applies its config. This is every pre-existing node.
	DeploymentManaged = "managed"
	// DeploymentManual is a hand-deployed node: no agent, never enrolls. Its identity (public key +
	// endpoint) is carried in the topology, the controller compiles + signs its bundle like any other
	// node, and the operator installs it by hand.
	DeploymentManual = "manual"
)

// IsManual reports whether the node is a hand-deployed (agent-less) manual node. Empty DeploymentMode
// is managed, so only an explicit "manual" returns true.
func (n Node) IsManual() bool {
	return n.DeploymentMode == DeploymentManual
}

// PublicEndpoint is a public reachable address mapping.
type PublicEndpoint struct {
	ID   string `json:"id"`
	Host string `json:"host"`
	Port int    `json:"port"`
	Note string `json:"note,omitempty"`
}

// NodeCapabilities declares a node's capabilities.
type NodeCapabilities struct {
	CanAcceptInbound bool `json:"can_accept_inbound"`
	CanForward       bool `json:"can_forward"`
	CanRelay         bool `json:"can_relay"`
	HasPublicIP      bool `json:"has_public_ip"`
}

// Value constants for Edge.Role. An empty value is equivalent to EdgeRolePrimary (both in the primary class).
const (
	// EdgeRolePrimary is the primary link: it folds together with the other non-backup edges into the single link for a pair of nodes.
	EdgeRolePrimary = "primary"
	// EdgeRoleBackup is the backup link: each backup edge becomes its own independent link (independent allocation + independent interface name).
	EdgeRoleBackup = "backup"
)

// Value constants for Edge.LinkDirection. An empty value is equivalent to EdgeLinkDirectionBoth.
// There is deliberately NO "reverse" value: single-linking is ALWAYS expressed as the drawn
// from→to direction (one spelling — a second spelling would force every direction-aware rule to
// handle both forever; owner decision D11). To single-link the other way, flip the edge (the
// editor's "to(A)" choice swaps from/to and mirrors the pin pairs — allocation-stable, since link
// identity and interface names are direction-agnostic).
const (
	// EdgeLinkDirectionBoth lets both sides initiate the WireGuard handshake (the default; the
	// forward peer dials edge.endpoint_host when set, the auto-reverse peer dials the from-node's
	// public endpoint when resolvable).
	EdgeLinkDirectionBoth = "both"
	// EdgeLinkDirectionForward lets only from→to initiate: the reverse peer keeps its full [Peer]
	// stanza (AllowedIPs, return traffic, Babel) but carries no dial Endpoint, so it can never
	// race the forward path's relay/accelerator endpoint via WireGuard endpoint roaming.
	EdgeLinkDirectionForward = "forward"
)

// Edge is an edge definition representing the connection intent between two nodes.
// Its semantics are "from actively connects to to".
type Edge struct {
	ID         string `json:"id"`
	FromNodeID string `json:"from_node_id"`
	ToNodeID   string `json:"to_node_id"`

	// Connection type: direct, public-endpoint, relay-path, candidate.
	Type string `json:"type"`

	// Peer endpoint (user input: 0 = auto-allocate, non-zero = NAT/port-forward override).
	EndpointHost string `json:"endpoint_host,omitempty"`
	EndpointPort int    `json:"endpoint_port,omitempty"`

	// Actual port allocated by the compiler (read-only, filled in by the compiler).
	CompiledPort int `json:"compiled_port,omitempty"`

	// Priority.
	Priority int `json:"priority,omitempty"`
	Weight   int `json:"weight,omitempty"`

	// Link role: distinguishes the primary link (primary class) from the backup link between a pair of nodes.
	// Empty / "primary" falls into the primary class — all non-backup edges between the same pair of nodes fold into one link;
	// "backup" makes each edge its own independent link, used for Babel cost-based failover.
	// See docs/spec/compiler/allocation-stability.md (Link identity with parallel edges).
	Role string `json:"role,omitempty"`

	// Transport protocol: udp, tcp.
	Transport string `json:"transport,omitempty"`

	// MimicFallback is the per-link mimic→UDP fallback POLICY. Only meaningful on a
	// transport=="tcp" (mimic) edge; ignored on a udp edge. Tri-state:
	//   ""      inherit the fleet-wide default (ControllerSettings.MimicFallbackDefault);
	//   "udp"   if mimic provisioning fails at install time, bring the link up as plain UDP;
	//   "none"  fail closed (do not fall back) — preserves mimic's censorship-evasion guarantee.
	// PURE POLICY: it feeds the renderer-input PeerInfo, NEVER the allocator (allocation stays
	// byte-identical). omitempty for back-compat: an old topology with no field loads as "" (inherit).
	// See docs/spec/data-model/edge.md §TCP transport and docs/spec/artifacts/mimic.md.
	MimicFallback string `json:"mimic_fallback,omitempty"`

	// LinkDirection is the per-edge dial-direction POLICY. Tri-state:
	//   ""        equivalent to "both" (back-compat: old topologies load with no field);
	//   "both"    both sides may initiate — today's behavior, byte-identical output;
	//   "forward" only from→to initiates (dials edge.endpoint_host, which the validator
	//             requires); the reverse peer keeps its [Peer] stanza but carries no Endpoint,
	//             so it can never race the forward path via WireGuard endpoint roaming.
	// To single-link the OTHER way, flip the edge — there is no "reverse" value (D11, one
	// spelling; see the EdgeLinkDirection* const block).
	// PURE POLICY: it gates only which PeerInfo receives a dial Endpoint, NEVER the allocator
	// (ports / transit IPs / link-locals / pins are direction-blind and stay byte-identical).
	// omitempty for back-compat. See docs/spec/data-model/edge.md §Link direction.
	LinkDirection string `json:"link_direction,omitempty"`

	// Whether the edge is enabled.
	IsEnabled bool `json:"is_enabled"`

	// Notes.
	Notes string `json:"notes,omitempty"`

	// === Allocation pins (read-write): written back by the compiler, persisted by the frontend, and round-tripped verbatim ===
	// These six fields bind the resources this link is allocated (listen ports, the transit IP pair, the IPv6 link-local pair)
	// to a specific edge, reusing the existing "write-back + localStorage" round-trip path of overlay_ip / compiled_port
	// (no new transport). On the next compile the compiler prefers to keep existing pins rather than recompute by array position,
	// so a superset topology reproduces byte-identical allocation values for every existing edge (incremental expansion does not disturb unchanged nodes).
	//
	// Pins are oriented by the owning edge's FromNodeID/ToNodeID: from_* is the value on this edge's from side,
	// to_* is the value on the to side; the reverse edge for the same pair of nodes carries the same pair of values, mirrored.
	// Transit and link-local resources are either fully pinned as a pair or not pinned at all. Listen ports are paired on
	// ordinary links; a client link is the endpoint-specific exception because the client uses one shared wg0, so its port
	// stays zero while the non-client endpoint retains one valid sticky listen-port pin. CompiledPort remains only the
	// effective dial-port echo (including an explicit endpoint_port override), not the sticky allocation authority.
	// See docs/spec/compiler/allocation-stability.md and docs/spec/data-model/edge.md (Allocation pins).

	// Listen-port pins for the from / to side interfaces. Only a client endpoint lacks a per-link port;
	// the opposite non-client endpoint still owns and persists its real per-link listen port.
	PinnedFromPort int `json:"pinned_from_port,omitempty"`
	PinnedToPort   int `json:"pinned_to_port,omitempty"`

	// Transit IP pins for the from / to side (drawn from the owning domain's transit_cidr address pool).
	PinnedFromTransitIP string `json:"pinned_from_transit_ip,omitempty"`
	PinnedToTransitIP   string `json:"pinned_to_transit_ip,omitempty"`

	// IPv6 link-local pins for the from / to side (drawn from fe80::/10).
	PinnedFromLinkLocal string `json:"pinned_from_link_local,omitempty"`
	PinnedToLinkLocal   string `json:"pinned_to_link_local,omitempty"`
}

// RoutePolicy is a route-policy definition.
type RoutePolicy struct {
	ID              string `json:"id"`
	DomainID        string `json:"domain_id"`
	DestinationCIDR string `json:"destination_cidr"`
	NextHopNodeID   string `json:"next_hop_node_id,omitempty"`
	Metric          int    `json:"metric,omitempty"`
	Notes           string `json:"notes,omitempty"`

	SourceSelector string `json:"source_selector,omitempty"`
	Action         string `json:"action,omitempty"`
	ApplyToNodeID  string `json:"apply_to_node_id,omitempty"`
}
