// Babel config renderer — the TypeScript mirror of internal/renderer/babel.go + babel_presets.go.
//
// Each non-client node runs babeld over its WireGuard tunnel interfaces. The template string below is
// COPIED VERBATIM from babel.go:74-95 (babelConfigTemplate), including every {{- -}} chomp marker, so
// the rendered bytes match the Go oracle. The C1 byte-stability fix (sorting peers by interface name
// before both the interface loop AND the client-/32 redistribute loop) is reproduced exactly: a benign
// edge reorder MUST NOT churn a node's babeld.conf bytes (the harness's edge-reorder fixtures pin this).

import {
  deriveRoleSemantics,
  type RoleSemantics,
} from '../capabilities';
import type { Domain, Node, PeerInfo, Topology } from '../model';
import { generateRouterID } from '../peers';
import { renderTemplate } from './template';

// babelLocalPort is the babeld control-socket port (local-port). Mirrors renderer.babelLocalPort
// (babel.go:14) — a named constant rather than a template literal.
const babelLocalPort = 33123;

// Timer defaults for the role presets. Mirror babel_presets.go:23-28.
const defaultHelloInterval = 4;
const defaultUpdateInterval = 16;

// BabelRolePreset describes the default Babel link-tuning values for a role. Mirrors
// renderer.BabelRolePreset (babel_presets.go:7-17).
interface BabelRolePreset {
  defaultCost: number;
  helloInterval: number;
  updateInterval: number;
}

// getBabelRolePreset returns the Babel preset for the given role. Mirrors
// renderer.GetBabelRolePreset (babel_presets.go:31-65): only relay carries a non-zero default cost
// (96); every role uses the same hello/update timers; the default branch is "peer".
function getBabelRolePreset(role: string): BabelRolePreset {
  switch (role) {
    case 'router':
      return { defaultCost: 0, helloInterval: defaultHelloInterval, updateInterval: defaultUpdateInterval };
    case 'relay':
      return { defaultCost: 96, helloInterval: defaultHelloInterval, updateInterval: defaultUpdateInterval };
    case 'gateway':
      return { defaultCost: 0, helloInterval: defaultHelloInterval, updateInterval: defaultUpdateInterval };
    default: // "peer"
      return { defaultCost: 0, helloInterval: defaultHelloInterval, updateInterval: defaultUpdateInterval };
  }
}

// babelConfigTemplate is copied VERBATIM from babel.go:74-95. Data fields (Go names): NodeName,
// NodeRole, RouterID, LocalPort, HelloInterval, UpdateInterval, LocalRedistributePrefixes (string[]),
// KernelRedistributePrefixes (string[]), Interfaces ([{Name, Type, Cost}]). The interface line uses
// $.HelloInterval / $.UpdateInterval (root access from inside the range) and .Cost (the range element).
const babelConfigTemplate = `# Babel configuration for {{ .NodeName }}
# Generated by Overlay Network Config Orchestrator
# Role: {{ .NodeRole }}

router-id {{ .RouterID }}
local-port {{ .LocalPort }}
skip-kernel-setup false

# Route redistribution
{{ range .LocalRedistributePrefixes -}}
redistribute local ip {{ . }} allow
{{ end -}}
{{ range .KernelRedistributePrefixes -}}
redistribute ip {{ . }} allow
{{ end -}}
# Deny all other local routes
redistribute local deny

# WireGuard tunnel interfaces
{{ range .Interfaces -}}
interface {{ .Name }} type {{ .Type }}{{ if gt $.HelloInterval 0 }} hello-interval {{ $.HelloInterval }}{{ end }}{{ if gt $.UpdateInterval 0 }} update-interval {{ $.UpdateInterval }}{{ end }}{{ if gt .Cost 0 }} rxcost {{ .Cost }}{{ end }}
{{ end }}`;

// BabelInterface mirrors renderer.BabelInterface (babel.go:63-72).
interface BabelInterfaceData {
  Name: string;
  Type: string;
  Cost: number;
}

// shouldRunBabel reports whether the node needs to run Babel. Mirrors renderer.shouldRunBabel
// (babel.go:241-251): clients never run babeld, and a non-"babel" routing mode disables it.
function shouldRunBabel(node: Node, domain: Domain | undefined): boolean {
  if (node.role === 'client') {
    return false;
  }
  if (domain !== undefined && domain.routing_mode !== 'babel') {
    return false;
  }
  return true;
}

// renderBabelConfig renders the Babel configuration for a single node, or "" when the node does not run
// Babel. Mirrors renderer.RenderBabelConfig (babel.go:98-200) step-for-step, including:
//   - the C1 sortedPeers sort by interfaceName BEFORE both the interface loop and the client-/32 loop;
//   - skipping IsClientPeer tunnels in the interface loop (D73);
//   - rxcost preferring the edge LinkCost > 0 over the role preset default (D63);
//   - the local- vs kernel-redistribute split (self-/32, domain-CIDR -> local; extra_prefixes,
//     default-route -> kernel; client-/32 -> local).
export function renderBabelConfig(
  node: Node,
  peers: PeerInfo[],
  domain: Domain | undefined,
): string {
  if (!shouldRunBabel(node, domain)) {
    return '';
  }

  const semantics: RoleSemantics = deriveRoleSemantics(node);
  const preset = getBabelRolePreset(node.role);

  // Generate the router-id (use the pinned router_id when present).
  let routerID = node.router_id ?? '';
  if (routerID === '') {
    routerID = generateRouterID(node.id);
  }

  const localRedistributePrefixes: string[] = [];
  const kernelRedistributePrefixes: string[] = [];
  const interfaces: BabelInterfaceData[] = [];

  // C1: sort a COPY of the peers by interface name BEFORE both loops, so the output depends only on
  // link identity, not edge-array position (babel.go:130-133). A benign edge reorder must not churn the
  // bytes. The unique per-peer interface name is the stable key.
  const sortedPeers = [...peers].sort((a, b) =>
    a.interfaceName < b.interfaceName ? -1 : a.interfaceName > b.interfaceName ? 1 : 0,
  );

  // Each peer corresponds to one WireGuard tunnel interface; skip client tunnels (D73).
  for (const p of sortedPeers) {
    if (p.isClientPeer) {
      continue;
    }
    // rxcost prefers the edge's explicit LinkCost > 0; else the role preset default (D63).
    let cost = preset.defaultCost;
    if (p.linkCost > 0) {
      cost = p.linkCost;
    }
    interfaces.push({ Name: p.interfaceName, Type: 'tunnel', Cost: cost });
  }

  // self-/32: redistribute local (the dummy0 OverlayIP/32 connected route — protected invariant).
  if (semantics.babelAnnounce.announceSelf && (node.overlay_ip ?? '') !== '') {
    localRedistributePrefixes.push((node.overlay_ip as string) + '/32');
  }

  // domain-CIDR aggregate: redistribute local (the plan-6.5-deferred no-op line, kept unchanged).
  if (
    semantics.babelAnnounce.announceDomainCIDR &&
    domain !== undefined &&
    domain.cidr !== ''
  ) {
    localRedistributePrefixes.push(domain.cidr);
  }

  // extra_prefixes: kernel connected routes -> the non-local form (D41).
  if (semantics.babelAnnounce.announceExtraPrefixes) {
    kernelRedistributePrefixes.push(...(node.extra_prefixes ?? []));
  }

  // default route 0.0.0.0/0: the gateway WAN default -> the non-local form (D40).
  if (semantics.babelAnnounce.announceDefault) {
    kernelRedistributePrefixes.push('0.0.0.0/0');
  }

  // client-/32: the router-side injected kernel route -> redistribute local. Sorted-peer order (C1).
  for (const p of sortedPeers) {
    if (p.isClientPeer && p.clientOverlayIP !== '') {
      localRedistributePrefixes.push(p.clientOverlayIP + '/32');
    }
  }

  return renderTemplate('babeld.conf', babelConfigTemplate, {
    NodeName: node.name,
    NodeRole: node.role,
    RouterID: routerID,
    LocalPort: babelLocalPort,
    HelloInterval: preset.helloInterval,
    UpdateInterval: preset.updateInterval,
    LocalRedistributePrefixes: localRedistributePrefixes,
    KernelRedistributePrefixes: kernelRedistributePrefixes,
    Interfaces: interfaces,
  });
}

// renderAllBabelConfigs renders the Babel configuration for every node, keyed by node ID; a node that
// does not run Babel is omitted (its config is ""). Mirrors renderer.RenderAllBabelConfigs
// (babel.go:203-238).
export function renderAllBabelConfigs(
  topo: Topology,
  peerMap: Record<string, PeerInfo[]>,
): Record<string, string> {
  const configs: Record<string, string> = {};

  const domainMap = new Map<string, Domain>();
  for (const d of topo.domains) {
    domainMap.set(d.id, d);
  }

  const nodeMap = new Map<string, Node>();
  for (const n of topo.nodes) {
    nodeMap.set(n.id, n);
  }

  for (const nodeID of Object.keys(peerMap)) {
    const node = nodeMap.get(nodeID);
    if (node === undefined) {
      continue;
    }
    const domain = domainMap.get(node.domain_id);
    const config = renderBabelConfig(node, peerMap[nodeID], domain);
    if (config !== '') {
      configs[nodeID] = config;
    }
  }

  return configs;
}
