// Deploy-script renderer — the TypeScript mirror of internal/renderer/deploy.go.
//
// Unlike the WireGuard / Babel / sysctl / install renderers, deploy.go uses NO text/template (verified
// 0 {{- -}} markers): it builds the bash + PowerShell deploy scripts by direct string concatenation
// (strings.Builder + fmt.Fprintf). This port reproduces that string building DIRECTLY — the static
// blocks are copied verbatim and the per-node interpolations use the same escaping idioms
// (bashSingleQuote for bash contexts, powerShellArgQuote for PowerShell contexts). The hardcoded SNAT
// transit literals "10.10.0.0/24" at deploy.go:310/370/482/568 are replicated VERBATIM — byte-equality
// is the contract; any "fix" would change Go and refresh the goldens, never diverge here.

import { bashSingleQuote, powerShellArgQuote } from '../escape';
import type { Domain, Node, PeerInfo, Topology } from '../model';
import { safeInstallerFileName } from '../naming';

// DeployNodeInfo holds per-node SSH and artifact info for deploy-script generation. Mirrors
// renderer.DeployNodeInfo (deploy.go:13-24).
interface DeployNodeInfo {
  NodeID: string;
  NodeName: string;
  SafeInstallerName: string;
  SSHTarget: string;
  SSHPort: number;
  SSHKeyPath: string;
  HasSSH: boolean;
  WgInterfaces: string[];
  HasBabel: boolean;
  IsClient: boolean;
}

// shouldRunBabel reports whether a node runs Babel for the deploy-script HasBabel fallback. Mirrors
// renderer.shouldRunBabel (babel.go:241-251), used by deploy.go only when babelConfigs is unavailable
// (D61). The conformance path always passes the compiled babelConfigs, so this fallback is unused there
// — but it is ported for fidelity with RenderDeployScripts' full signature behavior.
function shouldRunBabel(node: Node, domain: Domain | undefined): boolean {
  if (node.role === 'client') {
    return false;
  }
  if (domain !== undefined && domain.routing_mode !== 'babel') {
    return false;
  }
  return true;
}

// buildSSHOpts returns [sshOpts, scpOpts]. sshOpts has a LEADING space when non-empty (for "ssh%s
// target" formatting); scpOpts has NO leading space (for "scp %s ..." formatting). Mirrors
// renderer.buildSSHOpts (deploy.go:121-155): the -i key path goes through the same escaping idiom as
// the target/name (bashSingleQuote for bash, powerShellArgQuote for PowerShell) — never Go's %q, which
// is not shell-safe.
function buildSSHOpts(
  node: DeployNodeInfo,
  quoteStyle: 'bash' | 'powershell',
): [string, string] {
  const sshParts: string[] = [];
  const scpParts: string[] = [];

  if (node.SSHPort > 0) {
    sshParts.push('-p ' + node.SSHPort);
    scpParts.push('-P ' + node.SSHPort);
  }
  if (node.SSHKeyPath !== '') {
    if (quoteStyle === 'bash') {
      const keyArg = '-i ' + bashSingleQuote(node.SSHKeyPath);
      sshParts.push(keyArg);
      scpParts.push(keyArg);
    } else {
      const keyArg = '-i ' + powerShellArgQuote(node.SSHKeyPath);
      sshParts.push(keyArg);
      scpParts.push(keyArg);
    }
  }

  let sshOpts = '';
  if (sshParts.length > 0) {
    sshOpts = ' ' + sshParts.join(' ');
  }
  const scpOpts = scpParts.join(' ');
  return [sshOpts, scpOpts];
}

// renderBashDeploy builds the bash deploy script. Mirrors renderer.renderBashDeploy (deploy.go:157-435)
// string-by-string. The static header/footer blocks are copied VERBATIM (raw-string literals in Go);
// the em-dash "—" in the UNINSTALL banner is a literal multi-byte UTF-8 glyph preserved here.
function renderBashDeploy(projectName: string, nodes: DeployNodeInfo[]): string {
  let b = '';

  b += `#!/usr/bin/env bash
# Auto-deploy script for project: ${projectName}
# Generated by Overlay Network Config Orchestrator
#
# Usage:
#   bash deploy-all.sh [--clean] <path-to-artifacts.zip>    Deploy overlay
#   bash deploy-all.sh --uninstall <path-to-artifacts.zip>   Remove overlay from all nodes
#
# Options:
#   --clean      Remove ALL existing WireGuard interfaces (wg*) before deploying.
#                Use this when switching from a single-interface (wg0) layout to
#                per-peer interfaces, or vice versa.
#   --uninstall  Completely remove the overlay from all nodes via SSH.
#                Stops all WireGuard interfaces, removes configs, stops Babel,
#                removes dummy0, and reloads systemd. No installer upload needed.
#
# This script SSHs into each configured node. Nodes without SSH details are skipped.
# SSH failures are caught per-node and do not abort the entire run.

set -uo pipefail

CLEAN=0
UNINSTALL=0
ARTIFACTS_ZIP=""

for arg in "$@"; do
    case "$arg" in
        --clean) CLEAN=1 ;;
        --uninstall|-u) UNINSTALL=1 ;;
        *) ARTIFACTS_ZIP="$arg" ;;
    esac
done

if [ "$UNINSTALL" -eq 0 ] && [ -z "$ARTIFACTS_ZIP" ]; then
    echo "Usage: $0 [--clean] <path-to-artifacts.zip>"
    echo "       $0 --uninstall"
    echo ""
    echo "Options:"
    echo "  --clean      Remove all existing WireGuard interfaces before deploying"
    echo "  --uninstall  Completely remove the overlay from all nodes"
    echo ""
    echo "Download the artifacts ZIP from the web UI (Export Artifacts button),"
    echo "then run this script pointing at the downloaded file."
    exit 1
fi

WORKDIR=""
if [ -n "$ARTIFACTS_ZIP" ]; then
    if [ ! -f "$ARTIFACTS_ZIP" ]; then
        echo "ERROR: File not found: $ARTIFACTS_ZIP" >&2
        exit 1
    fi

    # Extract to a temp directory
    WORKDIR="$(mktemp -d -t overlay-deploy-XXXXXX)"
    cleanup() { rm -rf "$WORKDIR"; }
    trap cleanup EXIT

    echo "Extracting artifacts..."
    unzip -q "$ARTIFACTS_ZIP" -d "$WORKDIR"
fi

if [ "$UNINSTALL" -eq 1 ]; then
    echo ""
    echo "*** UNINSTALL MODE — overlay will be removed from all nodes ***"
    echo ""
fi

FAILED=0
SKIPPED=0
SUCCESS=0

`;

  for (const node of nodes) {
    b += `# --- Node: ${node.NodeName} ---\n`;

    const targetQuoted = bashSingleQuote(node.SSHTarget);
    const nameQuoted = bashSingleQuote(node.NodeName);

    const installerFile = node.SafeInstallerName;
    const remoteInstaller = node.NodeID + '-install.sh';
    if (!node.HasSSH) {
      b += `echo ""
echo "=== "${nameQuoted}": SKIPPED (no SSH details configured) ==="
SKIPPED=$((SKIPPED + 1))
`;
      b += '\n';
      continue;
    }

    const [sshOpts, scpOpts] = buildSSHOpts(node, 'bash');

    let scpCmd = 'scp';
    if (scpOpts !== '') {
      scpCmd = 'scp ' + scpOpts;
    }

    // Build the inline uninstall script for this node (runs on the REMOTE node inside a quoted
    // heredoc; the node name is single-quoted-escaped, the interfaces are bare tokens).
    let uninstallCmds = '';
    uninstallCmds += 'set -uo pipefail\n';
    uninstallCmds += `echo '[Stage 1/4] Stopping WireGuard interfaces on '${nameQuoted}'...'\n`;

    for (const iface of node.WgInterfaces) {
      uninstallCmds += `wg-quick down ${iface} 2>/dev/null || true\n`;
      uninstallCmds += `systemctl disable wg-quick@${iface} 2>/dev/null || true\n`;
      uninstallCmds += `rm -f /etc/wireguard/${iface}.conf\n`;
    }

    uninstallCmds +=
      'for _i in $(wg show interfaces 2>/dev/null); do wg-quick down "$_i" 2>/dev/null || true; systemctl disable "wg-quick@$_i" 2>/dev/null || true; done\n';
    uninstallCmds += 'rm -f /etc/wireguard/*.conf\n';

    if (node.HasBabel) {
      uninstallCmds += `echo '[Stage 2/4] Stopping Babel routing daemon on '${nameQuoted}'...'\n`;
      uninstallCmds += 'systemctl stop babeld 2>/dev/null || true\n';
      uninstallCmds += 'systemctl disable babeld 2>/dev/null || true\n';
      uninstallCmds += 'rm -f /etc/babel/babeld.conf /etc/babeld.conf\n';
      uninstallCmds += 'rm -rf /etc/systemd/system/babeld.service.d\n';
    }

    uninstallCmds += `echo '[Stage 3/4] Removing overlay network configuration on '${nameQuoted}'...'\n`;
    uninstallCmds += 'rm -f /etc/sysctl.d/99-overlay.conf\n';
    uninstallCmds += 'sysctl --system > /dev/null 2>&1 || true\n';

    if (!node.IsClient) {
      uninstallCmds += 'nft delete table inet overlay-snat 2>/dev/null || true\n';
      uninstallCmds +=
        "iptables -t nat -D POSTROUTING -o 'wg-+' -s 10.10.0.0/24 -j SNAT --to-source $(ip -4 addr show dummy0 2>/dev/null | grep -oP 'inet \\K[^/]+' || echo 0.0.0.0) 2>/dev/null || true\n";
      uninstallCmds += 'systemctl disable overlay-snat.service 2>/dev/null || true\n';
      uninstallCmds += 'rm -f /etc/systemd/system/overlay-snat.service\n';
      uninstallCmds += 'ip link del dummy0 2>/dev/null || true\n';
      uninstallCmds += 'systemctl disable overlay-dummy.service 2>/dev/null || true\n';
      uninstallCmds += 'rm -f /etc/systemd/system/overlay-dummy.service\n';
    }

    uninstallCmds += `echo '[Stage 4/4] Reloading systemd on '${nameQuoted}'...'\n`;
    uninstallCmds +=
      "systemctl daemon-reload || { echo 'ERROR: systemctl daemon-reload failed' >&2; exit 1; }\n";
    uninstallCmds += `echo 'Overlay removed from '${nameQuoted}'.'\n`;

    // The big interpolated deploy/uninstall block. Every %s that carried SSHTarget is filled with
    // targetQuoted; every %s that carried NodeName with nameQuoted (mirrors deploy.go:331-415's
    // positional fills). The scp destination renders 'target':/tmp/<id>-install.sh — the :/tmp suffix
    // sits outside the closing quote (valid scp syntax).
    b += `echo ""
if [ "$UNINSTALL" -eq 1 ]; then
    echo "=== Uninstalling from "${nameQuoted}" ("${targetQuoted}") ==="
    if ! ssh${sshOpts} ${targetQuoted} "echo ok" >/dev/null 2>&1; then
        echo "  ERROR: SSH connection to "${nameQuoted}" failed." >&2
        FAILED=$((FAILED + 1))
    else
        if ssh${sshOpts} ${targetQuoted} sudo bash -s <<'UNINSTALL_EOF'; then
${uninstallCmds}
UNINSTALL_EOF
            echo "  SUCCESS: "${nameQuoted}" uninstalled."
            SUCCESS=$((SUCCESS + 1))
        else
            echo "  ERROR: Uninstall failed on "${nameQuoted}" (exit code: $?)." >&2
            FAILED=$((FAILED + 1))
        fi
    fi
else
    echo "=== Deploying to "${nameQuoted}" ("${targetQuoted}") ==="
    INSTALLER="$WORKDIR/${installerFile}"
    if [ ! -f "$INSTALLER" ]; then
        echo "  WARNING: Installer ${installerFile} not found in archive, skipping."
        SKIPPED=$((SKIPPED + 1))
    else
        # Test SSH connectivity first
        if ! ssh${sshOpts} ${targetQuoted} "echo ok" >/dev/null 2>&1; then
            echo "  ERROR: SSH connection to "${nameQuoted}" failed." >&2
            FAILED=$((FAILED + 1))
        else
            # Clean previous WireGuard configs if requested
            if [ "$CLEAN" -eq 1 ]; then
                echo "  Cleaning existing WireGuard interfaces on "${nameQuoted}"..."
                ssh${sshOpts} ${targetQuoted} sudo bash -s <<'CLEAN_EOF' 2>/dev/null || true
for iface in $(ip -o link show type wireguard 2>/dev/null | awk -F: '{print $2}' | tr -d ' '); do
    wg-quick down "$iface" 2>/dev/null || ip link del "$iface" 2>/dev/null || true
done
rm -f /etc/wireguard/wg*.conf
nft delete table inet overlay-snat 2>/dev/null || true
_snat_ip=$(ip -4 addr show dummy0 2>/dev/null | grep -oP 'inet \\K[^/]+' || true)
[ -n "$_snat_ip" ] && iptables -t nat -D POSTROUTING -o 'wg-+' -s 10.10.0.0/24 -j SNAT --to-source "$_snat_ip" 2>/dev/null || true
systemctl disable overlay-snat.service 2>/dev/null || true
rm -f /etc/systemd/system/overlay-snat.service
CLEAN_EOF
            fi

            if ${scpCmd} "$INSTALLER" ${targetQuoted}:/tmp/${remoteInstaller}; then
                if ssh${sshOpts} ${targetQuoted} "sudo bash /tmp/${remoteInstaller} && rm -f /tmp/${remoteInstaller}"; then
                    echo "  SUCCESS: "${nameQuoted}" deployed."
                    SUCCESS=$((SUCCESS + 1))
                else
                    echo "  ERROR: Installation script failed on "${nameQuoted}" (exit code: $?)." >&2
                    FAILED=$((FAILED + 1))
                fi
            else
                echo "  ERROR: SCP upload to "${nameQuoted}" failed." >&2
                FAILED=$((FAILED + 1))
            fi
        fi
    fi
fi
`;
    b += '\n';
  }

  b += `echo ""
echo "============================================================"
if [ "$UNINSTALL" -eq 1 ]; then
    echo "  Uninstall Summary"
else
    echo "  Deploy Summary"
fi
echo "  Success: $SUCCESS  Skipped: $SKIPPED  Failed: $FAILED"
echo "============================================================"

if [ "$FAILED" -gt 0 ]; then
    exit 1
fi
`;

  return b;
}

// renderPS1Deploy builds the PowerShell deploy script. Mirrors renderer.renderPS1Deploy
// (deploy.go:437-686) string-by-string. The here-string body (@'...'@) is the REMOTE bash, so the node
// name inside it uses bashSingleQuote; the PowerShell Write-Host / & ssh|scp argument sites use
// powerShellArgQuote. The em-dash "—" in the UNINSTALL banner is a literal glyph preserved here.
function renderPS1Deploy(projectName: string, nodes: DeployNodeInfo[]): string {
  let b = '';

  b += `# Auto-deploy script for project: ${projectName}
# Generated by Overlay Network Config Orchestrator
#
# Usage:
#   .\\deploy-all.ps1 -ArtifactsZip <path-to-artifacts.zip> [-Clean]    Deploy overlay
#   .\\deploy-all.ps1 -Uninstall                                         Remove overlay
#
# Options:
#   -Clean      Remove ALL existing WireGuard interfaces (wg*) before deploying.
#   -Uninstall  Completely remove the overlay from all nodes via SSH.
#               No artifacts ZIP needed.

param(
    [string]$ArtifactsZip,

    [switch]$Clean,

    [switch]$Uninstall
)

$ErrorActionPreference = "Continue"

if (-not $Uninstall -and [string]::IsNullOrEmpty($ArtifactsZip)) {
    Write-Host "Usage: .\\deploy-all.ps1 -ArtifactsZip <path> [-Clean]"
    Write-Host "       .\\deploy-all.ps1 -Uninstall"
    exit 1
}

$WorkDir = $null

if (-not [string]::IsNullOrEmpty($ArtifactsZip)) {
    if (-not (Test-Path $ArtifactsZip)) {
        Write-Error "File not found: $ArtifactsZip"
        exit 1
    }

    # Extract to temp
    $WorkDir = Join-Path ([System.IO.Path]::GetTempPath()) ("overlay-deploy-" + [System.Guid]::NewGuid().ToString("N").Substring(0,8))
    New-Item -ItemType Directory -Path $WorkDir -Force | Out-Null
}

# Clean script sent to remote via stdin (single-quoted — no PS expansion)
$CleanScript = 'for iface in $(ip -o link show type wireguard 2>/dev/null | awk -F: ''{print $2}'' | tr -d " "); do wg-quick down "$iface" 2>/dev/null || ip link del "$iface" 2>/dev/null || true; done; rm -f /etc/wireguard/wg*.conf; nft delete table inet overlay-snat 2>/dev/null || true; _snat_ip=$(ip -4 addr show dummy0 2>/dev/null | grep -oP ''inet \\K[^/]+'' || true); [ -n "$_snat_ip" ] && iptables -t nat -D POSTROUTING -o ''wg-+'' -s 10.10.0.0/24 -j SNAT --to-source "$_snat_ip" 2>/dev/null || true; systemctl disable overlay-snat.service 2>/dev/null || true; rm -f /etc/systemd/system/overlay-snat.service'

try {
    if ($WorkDir) {
        Write-Host "Extracting artifacts..."
        Expand-Archive -Path $ArtifactsZip -DestinationPath $WorkDir -Force
    }

    if ($Uninstall) {
        Write-Host ""
        Write-Host "*** UNINSTALL MODE — overlay will be removed from all nodes ***" -ForegroundColor Yellow
        Write-Host ""
    }

    $Failed = 0
    $Skipped = 0
    $Success = 0

`;

  for (const node of nodes) {
    const installerFile = node.SafeInstallerName;
    const remoteInstaller = node.NodeID + '-install.sh';

    const targetPSArg = powerShellArgQuote(node.SSHTarget);
    const namePSStr = powerShellArgQuote(node.NodeName);
    const nameBashQuoted = bashSingleQuote(node.NodeName);
    const scpDestPSArg = powerShellArgQuote(
      node.SSHTarget + ':/tmp/' + remoteInstaller,
    );

    if (!node.HasSSH) {
      b += `    Write-Host ""
    Write-Host ("=== " + ${namePSStr} + ": SKIPPED (no SSH details configured) ===")
    $Skipped++
`;
      b += '\n';
      continue;
    }

    const [sshOpts, scpOpts] = buildSSHOpts(node, 'powershell');

    let scpCmd = 'scp';
    if (scpOpts !== '') {
      scpCmd = 'scp ' + scpOpts;
    }

    // The inline uninstall script (REMOTE bash; node name via bashSingleQuote).
    let uninstallCmds = '';
    uninstallCmds += 'set -uo pipefail\n';
    uninstallCmds += `echo '[Stage 1/4] Stopping WireGuard interfaces on '${nameBashQuoted}'...'\n`;
    for (const iface of node.WgInterfaces) {
      uninstallCmds += `wg-quick down ${iface} 2>/dev/null || true\n`;
      uninstallCmds += `systemctl disable wg-quick@${iface} 2>/dev/null || true\n`;
      uninstallCmds += `rm -f /etc/wireguard/${iface}.conf\n`;
    }
    uninstallCmds +=
      'for _i in $(wg show interfaces 2>/dev/null); do wg-quick down "$_i" 2>/dev/null || true; systemctl disable "wg-quick@$_i" 2>/dev/null || true; done\n';
    uninstallCmds += 'rm -f /etc/wireguard/*.conf\n';
    if (node.HasBabel) {
      uninstallCmds += `echo '[Stage 2/4] Stopping Babel routing daemon on '${nameBashQuoted}'...'\n`;
      uninstallCmds += 'systemctl stop babeld 2>/dev/null || true\n';
      uninstallCmds += 'systemctl disable babeld 2>/dev/null || true\n';
      uninstallCmds += 'rm -f /etc/babel/babeld.conf /etc/babeld.conf\n';
      uninstallCmds += 'rm -rf /etc/systemd/system/babeld.service.d\n';
    }
    uninstallCmds += `echo '[Stage 3/4] Removing overlay network configuration on '${nameBashQuoted}'...'\n`;
    uninstallCmds += 'rm -f /etc/sysctl.d/99-overlay.conf\n';
    uninstallCmds += 'sysctl --system > /dev/null 2>&1 || true\n';
    if (!node.IsClient) {
      uninstallCmds += 'nft delete table inet overlay-snat 2>/dev/null || true\n';
      uninstallCmds +=
        "_snat_ip=$(ip -4 addr show dummy0 2>/dev/null | grep -oP 'inet \\K[^/]+' || true)\n";
      uninstallCmds +=
        '[ -n "$_snat_ip" ] && iptables -t nat -D POSTROUTING -o \'wg-+\' -s 10.10.0.0/24 -j SNAT --to-source "$_snat_ip" 2>/dev/null || true\n';
      uninstallCmds += 'systemctl disable overlay-snat.service 2>/dev/null || true\n';
      uninstallCmds += 'rm -f /etc/systemd/system/overlay-snat.service\n';
      uninstallCmds += 'ip link del dummy0 2>/dev/null || true\n';
      uninstallCmds += 'systemctl disable overlay-dummy.service 2>/dev/null || true\n';
      uninstallCmds += 'rm -f /etc/systemd/system/overlay-dummy.service\n';
    }
    uninstallCmds += `echo '[Stage 4/4] Reloading systemd on '${nameBashQuoted}'...'\n`;
    uninstallCmds += 'systemctl daemon-reload\n';
    uninstallCmds += `echo 'Overlay removed from '${nameBashQuoted}'.'\n`;

    // The interpolated PowerShell deploy/uninstall block. Write-Host lines use string concatenation (+)
    // so the escaped (already double-quoted) PowerShell value is a complete sub-expression; the & ssh /
    // & scp call sites take targetPSArg, and the one scp destination takes the whole pre-quoted
    // scpDestPSArg. The here-string body is the literal uninstallCmds (no trailing newline after it in
    // Go: the body ends with the last echo's '\n' and is closed by '@ on the same following line).
    b += `    Write-Host ""
    if ($Uninstall) {
        Write-Host ("=== Uninstalling from " + ${namePSStr} + " (" + ${targetPSArg} + ") ===")
        $sshTest = & ssh${sshOpts} ${targetPSArg} "echo ok" 2>&1
        if ($LASTEXITCODE -ne 0) {
            Write-Host ("  ERROR: SSH connection to " + ${namePSStr} + " failed.") -ForegroundColor Red
            $Failed++
        } else {
            $uninstallScript = @'
${uninstallCmds}'@
            $uninstallScript | & ssh${sshOpts} ${targetPSArg} sudo bash -s
            if ($LASTEXITCODE -ne 0) {
                Write-Host ("  ERROR: Uninstall failed on " + ${namePSStr} + ".") -ForegroundColor Red
                $Failed++
            } else {
                Write-Host ("  SUCCESS: " + ${namePSStr} + " uninstalled.")
                $Success++
            }
        }
    } else {
        Write-Host ("=== Deploying to " + ${namePSStr} + " (" + ${targetPSArg} + ") ===")
        $Installer = Join-Path $WorkDir "${installerFile}"
        if (-not (Test-Path $Installer)) {
            Write-Warning "Installer ${installerFile} not found in archive, skipping."
            $Skipped++
        } else {
            $sshTest = & ssh${sshOpts} ${targetPSArg} "echo ok" 2>&1
            if ($LASTEXITCODE -ne 0) {
                Write-Host ("  ERROR: SSH connection to " + ${namePSStr} + " failed.") -ForegroundColor Red
                $Failed++
            } else {
                if ($Clean) {
                    Write-Host ("  Cleaning existing WireGuard interfaces on " + ${namePSStr} + "...")
                    $CleanScript | & ssh${sshOpts} ${targetPSArg} sudo bash -s 2>$null
                }

                & ${scpCmd} $Installer ${scpDestPSArg}
                if ($LASTEXITCODE -ne 0) {
                    Write-Host ("  ERROR: SCP upload to " + ${namePSStr} + " failed.") -ForegroundColor Red
                    $Failed++
                } else {
                    & ssh${sshOpts} ${targetPSArg} "sudo bash /tmp/${remoteInstaller} && rm -f /tmp/${remoteInstaller}"
                    if ($LASTEXITCODE -ne 0) {
                        Write-Host ("  ERROR: Installation script failed on " + ${namePSStr} + " (exit code: $LASTEXITCODE).") -ForegroundColor Red
                        $Failed++
                    } else {
                        Write-Host ("  SUCCESS: " + ${namePSStr} + " deployed.")
                        $Success++
                    }
                }
            }
        }
    }
`;
    b += '\n';
  }

  b += `    Write-Host ""
    Write-Host "============================================================"
    if ($Uninstall) {
        Write-Host "  Uninstall Summary"
    } else {
        Write-Host "  Deploy Summary"
    }
    Write-Host "  Success: $Success  Skipped: $Skipped  Failed: $Failed"
    Write-Host "============================================================"

    if ($Failed -gt 0) {
        exit 1
    }
} finally {
    if ($WorkDir) { Remove-Item -Recurse -Force $WorkDir -ErrorAction SilentlyContinue }
}
`;

  return b;
}

// renderDeployScripts generates the bash + PowerShell deploy scripts for a topology. Mirrors
// renderer.RenderDeployScripts (deploy.go:38-116): per-node SSH/artifact info is collected (ssh_alias
// wins over ssh_host; client nodes use a single wg0; HasBabel comes from the compiled babelConfigs when
// available, else the domain-aware shouldRunBabel fallback). Returns { bash, ps1 }.
export function renderDeployScripts(
  topo: Topology,
  peerMap: Record<string, PeerInfo[]>,
  babelConfigs: Record<string, string> | null,
): { bash: string; ps1: string } {
  const domainMap = new Map<string, Domain>();
  for (const d of topo.domains) {
    domainMap.set(d.id, d);
  }

  const nodes: DeployNodeInfo[] = [];
  for (const node of topo.nodes) {
    const info: DeployNodeInfo = {
      NodeID: node.id,
      NodeName: node.name,
      SafeInstallerName: safeInstallerFileName(node.name),
      SSHTarget: '',
      SSHPort: 22,
      SSHKeyPath: '',
      HasSSH: false,
      WgInterfaces: [],
      HasBabel: false,
      IsClient: node.role === 'client',
    };

    if (node.ssh_alias !== undefined && node.ssh_alias !== '') {
      info.SSHTarget = node.ssh_alias;
      info.SSHPort = 0; // alias → let ssh_config decide
      info.HasSSH = true;
    } else if (node.ssh_host !== undefined && node.ssh_host !== '') {
      let user = node.ssh_user ?? '';
      if (user === '') {
        user = 'root';
      }
      info.SSHTarget = `${user}@${node.ssh_host}`;
      info.HasSSH = true;
    }

    if (node.ssh_port !== undefined && node.ssh_port > 0) {
      info.SSHPort = node.ssh_port;
    }
    info.SSHKeyPath = node.ssh_key_path ?? '';

    // Collect WireGuard interface names from the peer map.
    const peers = peerMap[node.id];
    if (peers !== undefined) {
      for (const p of peers) {
        info.WgInterfaces.push(p.interfaceName);
      }
    }
    if (info.IsClient) {
      info.WgInterfaces = ['wg0'];
    }

    // HasBabel: from the compiled configs when available, else the domain-aware fallback (D61).
    if (babelConfigs !== null) {
      if (babelConfigs[node.id] !== undefined) {
        info.HasBabel = true;
      }
    } else {
      info.HasBabel = shouldRunBabel(node, domainMap.get(node.domain_id));
    }

    nodes.push(info);
  }

  const bash = renderBashDeploy(topo.project.name, nodes);
  const ps1 = renderPS1Deploy(topo.project.name, nodes);
  return { bash, ps1 };
}
