// sysctl config renderer — the TypeScript mirror of internal/renderer/sysctl.go.
//
// A forwarding node (router/relay/gateway) gets ip_forward=1 + rp_filter=0 (loose, so Babel's
// asymmetric routing survives the kernel reverse-path check); a non-forwarding peer/client gets
// rp_filter=2. The template string below is COPIED VERBATIM from sysctl.go:13-34 (sysctlConfigTemplate).
//
// BYTE HAZARD: the Go template's comment lines carry SIGNIFICANT TRAILING WHITESPACE ("#  IPv4 ",
// "#  rp_filter  Babel ") and full-width-parenthesis glyphs (（）) — the golden files keep those bytes.
// A normal multi-line TS template literal would lose the trailing spaces to the editor/ESLint
// no-trailing-spaces rule, silently reddening the harness. To keep the bytes EXACT and lint-safe, the
// template is assembled from an array of lines joined by "\n" (so every trailing space is explicit and
// visible in the source) — the resulting string is byte-identical to the Go const.

import type { Node, Topology } from '../model';
import { renderTemplate } from './template';

// sysctlConfigTemplate is byte-identical to sysctl.go:13-34. Each array element is one source line; the
// join reproduces the Go raw-string newlines (including the trailing blank line from the final "\n").
// Trailing spaces on the comment lines are intentional and load-bearing (see the BYTE HAZARD note).
const sysctlConfigTemplate = [
  '# Sysctl configuration for {{ .NodeName }}',
  '# Generated by Overlay Network Config Orchestrator',
  '',
  '{{- if .EnableForwarding }}',
  '',
  '#  IPv4 ',
  'net.ipv4.ip_forward = 1',
  '',
  '#  IPv6 （）',
  '# net.ipv6.conf.all.forwarding = 1',
  '',
  '# （Babel ）',
  'net.ipv4.conf.all.rp_filter = 0',
  'net.ipv4.conf.default.rp_filter = 0',
  '{{- else }}',
  '',
  '# （ peer ）',
  '#  rp_filter  Babel ',
  'net.ipv4.conf.all.rp_filter = 2',
  'net.ipv4.conf.default.rp_filter = 2',
  '{{- end }}',
  '',
].join('\n');

// renderSysctlConfig renders the sysctl configuration for a single node. Mirrors
// renderer.RenderSysctlConfig (sysctl.go:37-44): EnableForwarding is the node's inferred
// capabilities.can_forward (set by the capability-inference pass before rendering).
export function renderSysctlConfig(node: Node): string {
  return renderTemplate('sysctl.conf', sysctlConfigTemplate, {
    NodeName: node.name,
    EnableForwarding: node.capabilities.can_forward,
  });
}

// renderAllSysctlConfigs renders the sysctl configuration for every node in the topology, keyed by node
// ID. Mirrors renderer.RenderAllSysctlConfigs (sysctl.go:47-60) — iterates topo.nodes in order (a sysctl
// file is produced for every node, including clients).
export function renderAllSysctlConfigs(topo: Topology): Record<string, string> {
  const configs: Record<string, string> = {};
  for (const node of topo.nodes) {
    configs[node.id] = renderSysctlConfig(node);
  }
  return configs;
}
