// WireGuard config renderer — the TypeScript mirror of internal/renderer/wireguard.go.
//
// Each peer connection gets a dedicated per-peer WireGuard interface (the per-peer interface model);
// the client role is the exception — a single wg0. The two template strings below are COPIED VERBATIM
// from wireguard.go (wgPerPeerConfigTemplate at :52-86, wgClientConfigTemplate at :89-111), including
// every {{- -}} chomp marker, so the rendered bytes are identical to the Go oracle. The template
// engine (template.ts) is the only thing that must be correct; the harness arbitrates byte-equality.

import type { ClientPeerInfo, KeyPair, Node, PeerInfo, Topology } from '../model';
import { renderTemplate } from './template';

// wgPerPeerConfigTemplate is copied VERBATIM from wireguard.go:52-86. The template data struct uses Go
// field names (PascalCase): NodeName, InterfaceName, PrivateKey, TransitIP, ListenPort, MTU,
// LocalLinkLocal, ClientOverlayIP, and the nested Peer { Name, PublicKey, AllowedIPs, Endpoint,
// PersistentKeepalive }.
const wgPerPeerConfigTemplate = `# WireGuard per-peer interface: {{ .InterfaceName }}
# Node: {{ .NodeName }} -> Peer: {{ .Peer.Name }}
# Generated by Overlay Network Config Orchestrator

[Interface]
PrivateKey = {{ .PrivateKey }}
Address = {{ .TransitIP }}/32
Table = off
{{- if gt .ListenPort 0 }}
ListenPort = {{ .ListenPort }}
{{- end }}
{{- if gt .MTU 0 }}
MTU = {{ .MTU }}
{{- end }}

# Add IPv6 link-local for Babel
PostUp = ip -6 addr add {{ .LocalLinkLocal }}/64 dev %i 2>/dev/null || true
PostDown = ip -6 addr del {{ .LocalLinkLocal }}/64 dev %i 2>/dev/null || true
{{- if .ClientOverlayIP }}
# Route client overlay IP through this interface (discovered by Babel)
PostUp = ip route replace {{ .ClientOverlayIP }}/32 dev %i 2>/dev/null || true
PostDown = ip route del {{ .ClientOverlayIP }}/32 dev %i 2>/dev/null || true
{{- end }}

# Peer: {{ .Peer.Name }}
[Peer]
PublicKey = {{ .Peer.PublicKey }}
AllowedIPs = {{ .Peer.AllowedIPs }}
{{- if .Peer.Endpoint }}
Endpoint = {{ .Peer.Endpoint }}
{{- end }}
{{- if gt .Peer.PersistentKeepalive 0 }}
PersistentKeepalive = {{ .Peer.PersistentKeepalive }}
{{- end }}
`;

// wgClientConfigTemplate is copied VERBATIM from wireguard.go:89-111. Data fields: NodeName,
// PrivateKey, OverlayIP, ListenPort, MTU, RouterPublicKey, RouterEndpoint, AllowedIPs.
const wgClientConfigTemplate = `# WireGuard client interface: wg0
# Node: {{ .NodeName }} (client)
# Generated by Overlay Network Config Orchestrator

[Interface]
PrivateKey = {{ .PrivateKey }}
Address = {{ .OverlayIP }}/32
{{- if gt .ListenPort 0 }}
ListenPort = {{ .ListenPort }}
{{- end }}
{{- if gt .MTU 0 }}
MTU = {{ .MTU }}
{{- end }}

# Peer: Router
[Peer]
PublicKey = {{ .RouterPublicKey }}
AllowedIPs = {{ .AllowedIPs }}
{{- if .RouterEndpoint }}
Endpoint = {{ .RouterEndpoint }}
{{- end }}
PersistentKeepalive = 25
`;

// renderClientWireGuardConfig renders the wg0 config for a client node. Mirrors
// renderer.RenderClientWireGuardConfig (wireguard.go:126-144): AllowedIPs joins the client's domain
// CIDRs with ", "; an empty join falls back to "0.0.0.0/0".
export function renderClientWireGuardConfig(clientInfo: ClientPeerInfo): string {
  let allowedIPs = clientInfo.domainCIDRs.join(', ');
  if (allowedIPs === '') {
    allowedIPs = '0.0.0.0/0';
  }

  return renderTemplate('wg0.conf', wgClientConfigTemplate, {
    NodeName: clientInfo.nodeName,
    PrivateKey: clientInfo.privateKey,
    OverlayIP: clientInfo.overlayIP,
    ListenPort: clientInfo.listenPort,
    MTU: clientInfo.mtu,
    RouterPublicKey: clientInfo.routerPublicKey,
    RouterEndpoint: clientInfo.routerEndpoint,
    AllowedIPs: allowedIPs,
  });
}

// renderPerPeerWireGuardConfig renders the config for a single per-peer WireGuard interface. Mirrors
// renderer.RenderPerPeerWireGuardConfig (wireguard.go:153-173): the interface MTU is taken from
// peer.mtu (mimic link −12, non-mimic == node.mtu); AllowedIPs joins peer.allowedIPs with ", ".
export function renderPerPeerWireGuardConfig(
  node: Node,
  peer: PeerInfo,
  keys: KeyPair,
): string {
  return renderTemplate(peer.interfaceName + '.conf', wgPerPeerConfigTemplate, {
    NodeName: node.name,
    InterfaceName: peer.interfaceName,
    PrivateKey: keys.privateKey,
    TransitIP: peer.localTransitIP,
    ListenPort: peer.listenPort,
    MTU: peer.mtu,
    LocalLinkLocal: peer.localLinkLocal,
    ClientOverlayIP: peer.clientOverlayIP,
    Peer: {
      Name: peer.nodeName,
      PublicKey: peer.publicKey,
      AllowedIPs: peer.allowedIPs.join(', '),
      Endpoint: peer.endpoint,
      PersistentKeepalive: peer.persistentKeepalive,
    },
  });
}

// renderAllWireGuardConfigs renders every per-peer WireGuard config for every node. Mirrors
// renderer.RenderAllWireGuardConfigs (wireguard.go:177-210): the returned record is keyed
// "nodeID:interfaceName" (the per-file key the export layer splits into wireguard/<iface>.conf). A node
// in the peer map with no key entry is a hard error, matching the Go side.
//
// NOTE: this renders ONLY the per-peer interfaces (the peer map). Client wg0 configs are produced by
// renderClientWireGuardConfig + the compile orchestrator, exactly as the Go RenderAll family does
// (RenderAllWireGuardConfigs does not iterate clients; the client wg0 is keyed "nodeID:wg0" by the
// All-renderer aggregator in render.go). The conformance gate drives client fixtures through the same
// path so wg0 is covered.
export function renderAllWireGuardConfigs(
  topo: Topology,
  peerMap: Record<string, PeerInfo[]>,
  keys: Map<string, KeyPair>,
): Record<string, string> {
  const configs: Record<string, string> = {};

  const nodeMap = new Map<string, Node>();
  for (const n of topo.nodes) {
    nodeMap.set(n.id, n);
  }

  for (const nodeID of Object.keys(peerMap)) {
    const node = nodeMap.get(nodeID);
    if (node === undefined) {
      continue;
    }

    const key = keys.get(nodeID);
    if (key === undefined) {
      throw new Error(`node ${nodeID} is missing its key`);
    }

    for (const peer of peerMap[nodeID]) {
      const config = renderPerPeerWireGuardConfig(node, peer, key);
      configs[nodeID + ':' + peer.interfaceName] = config;
    }
  }

  return configs;
}
